// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.block;

import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.Block;
import javax.annotation.Nonnull;
import net.minecraftforge.fml.common.registry.GameRegistry;

@GameRegistry.ObjectHolder("twilightforest")
@Nonnull
public class TFBlocks
{
    public static final Block twilight_log;
    public static final BlockLeaves twilight_leaves;
    public static final Block firefly;
    public static final BlockTFPortal twilight_portal;
    public static final Block maze_stone;
    public static final Block hedge;
    public static final Block boss_spawner;
    public static final Block firefly_jar;
    public static final Block twilight_plant;
    public static final Block cicada;
    public static final Block root;
    public static final Block uncrafting_table;
    public static final Block fire_jet;
    public static final Block naga_stone;
    public static final BlockBush twilight_sapling;
    public static final Block magic_log;
    public static final Block magic_log_core;
    public static final BlockLeaves magic_leaves;
    public static final Block moonworm;
    public static final Block tower_wood;
    public static final BlockTFTowerDevice tower_device;
    public static final Block tower_translucent;
    public static final Block trophy;
    public static final Block stronghold_shield;
    public static final Block trophy_pedestal;
    public static final Block aurora_block;
    public static final Block underbrick;
    public static final Block thorns;
    public static final Block burnt_thorns;
    public static final Block thorn_rose;
    public static final BlockLeaves twilight_leaves_3;
    public static final Block deadrock;
    public static final Block dark_leaves;
    public static final Block aurora_pillar;
    public static final BlockSlab aurora_slab;
    public static final BlockSlab double_aurora_slab;
    public static final Block trollsteinn;
    public static final Block wispy_cloud;
    public static final Block fluffy_cloud;
    public static final Block giant_cobblestone;
    public static final Block giant_log;
    public static final Block giant_leaves;
    public static final Block giant_obsidian;
    public static final Block uberous_soil;
    public static final Block huge_stalk;
    public static final Block huge_mushgloom;
    public static final Block trollvidr;
    public static final Block unripe_trollber;
    public static final Block trollber;
    public static final Block knightmetal_block;
    public static final Block huge_lilypad;
    public static final Block huge_waterlily;
    public static final Block slider;
    public static final Block castle_brick;
    public static final Block castle_stairs;
    public static final Block castle_pillar;
    public static final Block castle_rune_brick;
    public static final Block force_field;
    public static final Block cinder_furnace;
    public static final Block cinder_furnace_lit;
    public static final Block cinder_log;
    public static final Block castle_door;
    public static final Block castle_door_vanished;
    public static final Block experiment_115;
    public static final Block miniature_structure;
    public static final Block block_storage;
    public static final Block spiral_bricks;
    public static final Block etched_nagastone;
    public static final Block nagastone_pillar;
    public static final Block nagastone_stairs;
    public static final Block etched_nagastone_mossy;
    public static final Block nagastone_pillar_mossy;
    public static final Block nagastone_stairs_mossy;
    public static final Block etched_nagastone_weathered;
    public static final Block nagastone_pillar_weathered;
    public static final Block nagastone_stairs_weathered;
    public static final Block auroralized_glass;
    public static final Block castle_stairs_brick;
    public static final Block castle_stairs_cracked;
    public static final Block castle_stairs_worn;
    public static final Block castle_stairs_mossy;
    public static final BlockTFLadderBars iron_ladder;
    public static final Block terrorcotta_circle;
    public static final Block terrorcotta_diagonal;
    public static final Block stone_twist;
    public static final Block stone_twist_thin;
    public static final BlockTF twilight_oak_planks;
    public static final BlockTFStairs twilight_oak_stairs;
    public static final BlockTFSlab twilight_oak_doubleslab;
    public static final BlockTFSlab twilight_oak_slab;
    public static final BlockTFButtonWood twilight_oak_button;
    public static final BlockTFFence twilight_oak_fence;
    public static final BlockTFFenceGate twilight_oak_gate;
    public static final BlockTFPressurePlate twilight_oak_plate;
    public static final BlockTF canopy_planks;
    public static final BlockTFStairs canopy_stairs;
    public static final BlockTFSlab canopy_doubleslab;
    public static final BlockTFSlab canopy_slab;
    public static final BlockTFButtonWood canopy_button;
    public static final BlockTFFence canopy_fence;
    public static final BlockTFFenceGate canopy_gate;
    public static final BlockTFPressurePlate canopy_plate;
    public static final BlockTF mangrove_planks;
    public static final BlockTFStairs mangrove_stairs;
    public static final BlockTFSlab mangrove_doubleslab;
    public static final BlockTFSlab mangrove_slab;
    public static final BlockTFButtonWood mangrove_button;
    public static final BlockTFFence mangrove_fence;
    public static final BlockTFFenceGate mangrove_gate;
    public static final BlockTFPressurePlate mangrove_plate;
    public static final BlockTF dark_planks;
    public static final BlockTFStairs dark_stairs;
    public static final BlockTFSlab dark_doubleslab;
    public static final BlockTFSlab dark_slab;
    public static final BlockTFButtonWood dark_button;
    public static final BlockTFFence dark_fence;
    public static final BlockTFFenceGate dark_gate;
    public static final BlockTFPressurePlate dark_plate;
    public static final BlockTF time_planks;
    public static final BlockTFStairs time_stairs;
    public static final BlockTFSlab time_doubleslab;
    public static final BlockTFSlab time_slab;
    public static final BlockTFButtonWood time_button;
    public static final BlockTFFence time_fence;
    public static final BlockTFFenceGate time_gate;
    public static final BlockTFPressurePlate time_plate;
    public static final BlockTF trans_planks;
    public static final BlockTFStairs trans_stairs;
    public static final BlockTFSlab trans_doubleslab;
    public static final BlockTFSlab trans_slab;
    public static final BlockTFButtonWood trans_button;
    public static final BlockTFFence trans_fence;
    public static final BlockTFFenceGate trans_gate;
    public static final BlockTFPressurePlate trans_plate;
    public static final BlockTF mine_planks;
    public static final BlockTFStairs mine_stairs;
    public static final BlockTFSlab mine_doubleslab;
    public static final BlockTFSlab mine_slab;
    public static final BlockTFButtonWood mine_button;
    public static final BlockTFFence mine_fence;
    public static final BlockTFFenceGate mine_gate;
    public static final BlockTFPressurePlate mine_plate;
    public static final BlockTF sort_planks;
    public static final BlockTFStairs sort_stairs;
    public static final BlockTFSlab sort_doubleslab;
    public static final BlockTFSlab sort_slab;
    public static final BlockTFButtonWood sort_button;
    public static final BlockTFFence sort_fence;
    public static final BlockTFFenceGate sort_gate;
    public static final BlockTFPressurePlate sort_plate;
    
    private static <T> T iCantBelieveItsNotNull() {
        return null;
    }
    
    static {
        twilight_log = iCantBelieveItsNotNull();
        twilight_leaves = iCantBelieveItsNotNull();
        firefly = iCantBelieveItsNotNull();
        twilight_portal = iCantBelieveItsNotNull();
        maze_stone = iCantBelieveItsNotNull();
        hedge = iCantBelieveItsNotNull();
        boss_spawner = iCantBelieveItsNotNull();
        firefly_jar = iCantBelieveItsNotNull();
        twilight_plant = iCantBelieveItsNotNull();
        cicada = iCantBelieveItsNotNull();
        root = iCantBelieveItsNotNull();
        uncrafting_table = iCantBelieveItsNotNull();
        fire_jet = iCantBelieveItsNotNull();
        naga_stone = iCantBelieveItsNotNull();
        twilight_sapling = iCantBelieveItsNotNull();
        magic_log = iCantBelieveItsNotNull();
        magic_log_core = iCantBelieveItsNotNull();
        magic_leaves = iCantBelieveItsNotNull();
        moonworm = iCantBelieveItsNotNull();
        tower_wood = iCantBelieveItsNotNull();
        tower_device = iCantBelieveItsNotNull();
        tower_translucent = iCantBelieveItsNotNull();
        trophy = iCantBelieveItsNotNull();
        stronghold_shield = iCantBelieveItsNotNull();
        trophy_pedestal = iCantBelieveItsNotNull();
        aurora_block = iCantBelieveItsNotNull();
        underbrick = iCantBelieveItsNotNull();
        thorns = iCantBelieveItsNotNull();
        burnt_thorns = iCantBelieveItsNotNull();
        thorn_rose = iCantBelieveItsNotNull();
        twilight_leaves_3 = iCantBelieveItsNotNull();
        deadrock = iCantBelieveItsNotNull();
        dark_leaves = iCantBelieveItsNotNull();
        aurora_pillar = iCantBelieveItsNotNull();
        aurora_slab = iCantBelieveItsNotNull();
        double_aurora_slab = iCantBelieveItsNotNull();
        trollsteinn = iCantBelieveItsNotNull();
        wispy_cloud = iCantBelieveItsNotNull();
        fluffy_cloud = iCantBelieveItsNotNull();
        giant_cobblestone = iCantBelieveItsNotNull();
        giant_log = iCantBelieveItsNotNull();
        giant_leaves = iCantBelieveItsNotNull();
        giant_obsidian = iCantBelieveItsNotNull();
        uberous_soil = iCantBelieveItsNotNull();
        huge_stalk = iCantBelieveItsNotNull();
        huge_mushgloom = iCantBelieveItsNotNull();
        trollvidr = iCantBelieveItsNotNull();
        unripe_trollber = iCantBelieveItsNotNull();
        trollber = iCantBelieveItsNotNull();
        knightmetal_block = iCantBelieveItsNotNull();
        huge_lilypad = iCantBelieveItsNotNull();
        huge_waterlily = iCantBelieveItsNotNull();
        slider = iCantBelieveItsNotNull();
        castle_brick = iCantBelieveItsNotNull();
        castle_stairs = iCantBelieveItsNotNull();
        castle_pillar = iCantBelieveItsNotNull();
        castle_rune_brick = iCantBelieveItsNotNull();
        force_field = iCantBelieveItsNotNull();
        cinder_furnace = iCantBelieveItsNotNull();
        cinder_furnace_lit = iCantBelieveItsNotNull();
        cinder_log = iCantBelieveItsNotNull();
        castle_door = iCantBelieveItsNotNull();
        castle_door_vanished = iCantBelieveItsNotNull();
        experiment_115 = iCantBelieveItsNotNull();
        miniature_structure = iCantBelieveItsNotNull();
        block_storage = iCantBelieveItsNotNull();
        spiral_bricks = iCantBelieveItsNotNull();
        etched_nagastone = iCantBelieveItsNotNull();
        nagastone_pillar = iCantBelieveItsNotNull();
        nagastone_stairs = iCantBelieveItsNotNull();
        etched_nagastone_mossy = iCantBelieveItsNotNull();
        nagastone_pillar_mossy = iCantBelieveItsNotNull();
        nagastone_stairs_mossy = iCantBelieveItsNotNull();
        etched_nagastone_weathered = iCantBelieveItsNotNull();
        nagastone_pillar_weathered = iCantBelieveItsNotNull();
        nagastone_stairs_weathered = iCantBelieveItsNotNull();
        auroralized_glass = iCantBelieveItsNotNull();
        castle_stairs_brick = iCantBelieveItsNotNull();
        castle_stairs_cracked = iCantBelieveItsNotNull();
        castle_stairs_worn = iCantBelieveItsNotNull();
        castle_stairs_mossy = iCantBelieveItsNotNull();
        iron_ladder = iCantBelieveItsNotNull();
        terrorcotta_circle = iCantBelieveItsNotNull();
        terrorcotta_diagonal = iCantBelieveItsNotNull();
        stone_twist = iCantBelieveItsNotNull();
        stone_twist_thin = iCantBelieveItsNotNull();
        twilight_oak_planks = iCantBelieveItsNotNull();
        twilight_oak_stairs = iCantBelieveItsNotNull();
        twilight_oak_doubleslab = iCantBelieveItsNotNull();
        twilight_oak_slab = iCantBelieveItsNotNull();
        twilight_oak_button = iCantBelieveItsNotNull();
        twilight_oak_fence = iCantBelieveItsNotNull();
        twilight_oak_gate = iCantBelieveItsNotNull();
        twilight_oak_plate = iCantBelieveItsNotNull();
        canopy_planks = iCantBelieveItsNotNull();
        canopy_stairs = iCantBelieveItsNotNull();
        canopy_doubleslab = iCantBelieveItsNotNull();
        canopy_slab = iCantBelieveItsNotNull();
        canopy_button = iCantBelieveItsNotNull();
        canopy_fence = iCantBelieveItsNotNull();
        canopy_gate = iCantBelieveItsNotNull();
        canopy_plate = iCantBelieveItsNotNull();
        mangrove_planks = iCantBelieveItsNotNull();
        mangrove_stairs = iCantBelieveItsNotNull();
        mangrove_doubleslab = iCantBelieveItsNotNull();
        mangrove_slab = iCantBelieveItsNotNull();
        mangrove_button = iCantBelieveItsNotNull();
        mangrove_fence = iCantBelieveItsNotNull();
        mangrove_gate = iCantBelieveItsNotNull();
        mangrove_plate = iCantBelieveItsNotNull();
        dark_planks = iCantBelieveItsNotNull();
        dark_stairs = iCantBelieveItsNotNull();
        dark_doubleslab = iCantBelieveItsNotNull();
        dark_slab = iCantBelieveItsNotNull();
        dark_button = iCantBelieveItsNotNull();
        dark_fence = iCantBelieveItsNotNull();
        dark_gate = iCantBelieveItsNotNull();
        dark_plate = iCantBelieveItsNotNull();
        time_planks = iCantBelieveItsNotNull();
        time_stairs = iCantBelieveItsNotNull();
        time_doubleslab = iCantBelieveItsNotNull();
        time_slab = iCantBelieveItsNotNull();
        time_button = iCantBelieveItsNotNull();
        time_fence = iCantBelieveItsNotNull();
        time_gate = iCantBelieveItsNotNull();
        time_plate = iCantBelieveItsNotNull();
        trans_planks = iCantBelieveItsNotNull();
        trans_stairs = iCantBelieveItsNotNull();
        trans_doubleslab = iCantBelieveItsNotNull();
        trans_slab = iCantBelieveItsNotNull();
        trans_button = iCantBelieveItsNotNull();
        trans_fence = iCantBelieveItsNotNull();
        trans_gate = iCantBelieveItsNotNull();
        trans_plate = iCantBelieveItsNotNull();
        mine_planks = iCantBelieveItsNotNull();
        mine_stairs = iCantBelieveItsNotNull();
        mine_doubleslab = iCantBelieveItsNotNull();
        mine_slab = iCantBelieveItsNotNull();
        mine_button = iCantBelieveItsNotNull();
        mine_fence = iCantBelieveItsNotNull();
        mine_gate = iCantBelieveItsNotNull();
        mine_plate = iCantBelieveItsNotNull();
        sort_planks = iCantBelieveItsNotNull();
        sort_stairs = iCantBelieveItsNotNull();
        sort_doubleslab = iCantBelieveItsNotNull();
        sort_slab = iCantBelieveItsNotNull();
        sort_button = iCantBelieveItsNotNull();
        sort_fence = iCantBelieveItsNotNull();
        sort_gate = iCantBelieveItsNotNull();
        sort_plate = iCantBelieveItsNotNull();
    }
}
