// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.world.registration;

import net.minecraft.world.level.block.HugeMushroomBlock;
import net.minecraft.world.level.block.state.properties.Property;
import twilightforest.block.TorchberryPlantBlock;
import net.minecraft.world.level.block.SaplingBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.RotatedPillarBlock;
import twilightforest.block.TFBlocks;
import twilightforest.block.HollowLogHorizontal;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

public final class BlockConstants
{
    public static final BlockState BIRCH_LOG;
    public static final BlockState HOLLOW_BIRCH_LOG;
    public static final BlockState OAK_LOG;
    public static final BlockState HOLLOW_OAK_LOG;
    public static final BlockState SPRUCE_LOG;
    public static final BlockState HOLLOW_SPRUCE_LOG;
    public static final BlockState SPRUCE_LEAVES;
    public static final BlockState SPRUCE_SAPLING;
    public static final BlockState TF_OAK_LOG;
    public static final BlockState HOLLOW_TF_OAK_LOG;
    public static final BlockState TF_OAK_WOOD;
    public static final BlockState TF_OAK_LEAVES;
    public static final BlockState TF_OAK_SAPLING;
    public static final BlockState CANOPY_LOG;
    public static final BlockState HOLLOW_CANOPY_LOG;
    public static final BlockState CANOPY_LEAVES;
    public static final BlockState CANOPY_SAPLING;
    public static final BlockState MANGROVE_LOG;
    public static final BlockState HOLLOW_MANGROVE_LOG;
    public static final BlockState MANGROVE_WOOD;
    public static final BlockState MANGROVE_LEAVES;
    public static final BlockState MANGROVE_SAPLING;
    public static final BlockState DARKWOOD_LOG;
    public static final BlockState DARKWOOD_LEAVES;
    public static final BlockState HARDENED_DARK_LEAVES;
    public static final BlockState DARKWOOD_SAPLING;
    public static final BlockState TIME_LOG;
    public static final BlockState TIME_WOOD;
    public static final BlockState TIME_LEAVES;
    public static final BlockState TRANSFORM_LOG;
    public static final BlockState TRANSFORM_LEAVES;
    public static final BlockState TRANSFORM_SAPLING;
    public static final BlockState MINING_LOG;
    public static final BlockState MINING_WOOD;
    public static final BlockState MINING_LEAVES;
    public static final BlockState SORT_LOG;
    public static final BlockState SORT_LEAVES;
    public static final BlockState SORT_SAPLING;
    public static final BlockState RAINBOW_LEAVES;
    public static final BlockState RAINBOW_SAPLING;
    public static final BlockState ROOTS;
    public static final BlockState GRASS;
    public static final BlockState TALL_GRASS;
    public static final BlockState FERN;
    public static final BlockState TALL_FERN;
    public static final BlockState POPPY;
    public static final BlockState DANDELION;
    public static final BlockState RED_TULIP;
    public static final BlockState ORANGE_TULIP;
    public static final BlockState PINK_TULIP;
    public static final BlockState WHITE_TULIP;
    public static final BlockState ALLIUM;
    public static final BlockState AZURE;
    public static final BlockState ORCHID;
    public static final BlockState LILY;
    public static final BlockState CORNFLOWER;
    public static final BlockState OXEYE;
    public static final BlockState MAYAPPLE;
    public static final BlockState FIDDLEHEAD;
    public static final BlockState MUSHGLOOM;
    public static final BlockState FIRE_JET;
    public static final BlockState SMOKER;
    public static final BlockState AIR;
    public static final BlockState LAVA;
    public static final BlockState WATER;
    public static final BlockState MYCELIUM;
    public static final BlockState UBEROUS_SOIL;
    public static final BlockState DIRT;
    public static final BlockState SAND;
    public static final BlockState STONE;
    public static final BlockState GRASS_BLOCK;
    public static final BlockState PODZOL;
    public static final BlockState COARSE_DIRT;
    public static final BlockState CICADA_JAR;
    public static final BlockState FIREFLY_JAR;
    public static final BlockState TROLLVIDR;
    public static final BlockState TORCHBERRIES;
    public static final BlockState ROOT_STRAND;
    public static final BlockState HANGING_ROOTS;
    public static final BlockState PUMPKIN;
    public static final BlockState DEAD_BUSH;
    public static final BlockState BROWN_MUSHROOM;
    public static final BlockState RED_MUSHROOM;
    public static final BlockState JACK_O_LANTERN;
    public static final BlockState DEADROCK;
    public static final BlockState WEATHERED_DEADROCK;
    public static final BlockState CRACKED_DEADROCK;
    public static final BlockState SNOW;
    public static final BlockState POWDER_SNOW;
    public static final BlockState ICE;
    public static final BlockState PACKED_ICE;
    public static final BlockState MUSHROOM_STEM;
    public static final BlockState MUSHROOM_CAP_RED;
    public static final BlockState MUSHROOM_CAP_BROWN;
    
    static {
        BIRCH_LOG = Blocks.f_50001_.m_49966_();
        HOLLOW_BIRCH_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_BIRCH_LOG_HORIZONTAL.get()).m_49966_();
        OAK_LOG = Blocks.f_49999_.m_49966_();
        HOLLOW_OAK_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_OAK_LOG_HORIZONTAL.get()).m_49966_();
        SPRUCE_LOG = Blocks.f_50000_.m_49966_();
        HOLLOW_SPRUCE_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_SPRUCE_LOG_HORIZONTAL.get()).m_49966_();
        SPRUCE_LEAVES = Blocks.f_50051_.m_49966_();
        SPRUCE_SAPLING = Blocks.f_50747_.m_49966_();
        TF_OAK_LOG = ((RotatedPillarBlock)TFBlocks.TWILIGHT_OAK_LOG.get()).m_49966_();
        HOLLOW_TF_OAK_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_TWILIGHT_OAK_LOG_HORIZONTAL.get()).m_49966_();
        TF_OAK_WOOD = ((RotatedPillarBlock)TFBlocks.TWILIGHT_OAK_WOOD.get()).m_49966_();
        TF_OAK_LEAVES = ((Block)TFBlocks.TWILIGHT_OAK_LEAVES.get()).m_49966_();
        TF_OAK_SAPLING = ((SaplingBlock)TFBlocks.TWILIGHT_OAK_SAPLING.get()).m_49966_();
        CANOPY_LOG = ((RotatedPillarBlock)TFBlocks.CANOPY_LOG.get()).m_49966_();
        HOLLOW_CANOPY_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_CANOPY_LOG_HORIZONTAL.get()).m_49966_();
        CANOPY_LEAVES = ((Block)TFBlocks.CANOPY_LEAVES.get()).m_49966_();
        CANOPY_SAPLING = ((SaplingBlock)TFBlocks.CANOPY_SAPLING.get()).m_49966_();
        MANGROVE_LOG = ((RotatedPillarBlock)TFBlocks.MANGROVE_LOG.get()).m_49966_();
        HOLLOW_MANGROVE_LOG = ((HollowLogHorizontal)TFBlocks.HOLLOW_MANGROVE_LOG_HORIZONTAL.get()).m_49966_();
        MANGROVE_WOOD = ((RotatedPillarBlock)TFBlocks.MANGROVE_WOOD.get()).m_49966_();
        MANGROVE_LEAVES = ((Block)TFBlocks.MANGROVE_LEAVES.get()).m_49966_();
        MANGROVE_SAPLING = ((SaplingBlock)TFBlocks.MANGROVE_SAPLING.get()).m_49966_();
        DARKWOOD_LOG = ((RotatedPillarBlock)TFBlocks.DARK_LOG.get()).m_49966_();
        DARKWOOD_LEAVES = ((Block)TFBlocks.DARK_LEAVES.get()).m_49966_();
        HARDENED_DARK_LEAVES = ((Block)TFBlocks.HARDENED_DARK_LEAVES.get()).m_49966_();
        DARKWOOD_SAPLING = ((SaplingBlock)TFBlocks.DARKWOOD_SAPLING.get()).m_49966_();
        TIME_LOG = ((RotatedPillarBlock)TFBlocks.TIME_LOG.get()).m_49966_();
        TIME_WOOD = ((RotatedPillarBlock)TFBlocks.TIME_WOOD.get()).m_49966_();
        TIME_LEAVES = ((Block)TFBlocks.TIME_LEAVES.get()).m_49966_();
        TRANSFORM_LOG = ((RotatedPillarBlock)TFBlocks.TRANSFORMATION_LOG.get()).m_49966_();
        TRANSFORM_LEAVES = ((Block)TFBlocks.TRANSFORMATION_LEAVES.get()).m_49966_();
        TRANSFORM_SAPLING = ((SaplingBlock)TFBlocks.TRANSFORMATION_SAPLING.get()).m_49966_();
        MINING_LOG = ((RotatedPillarBlock)TFBlocks.MINING_LOG.get()).m_49966_();
        MINING_WOOD = ((RotatedPillarBlock)TFBlocks.MINING_WOOD.get()).m_49966_();
        MINING_LEAVES = ((Block)TFBlocks.MINING_LEAVES.get()).m_49966_();
        SORT_LOG = ((RotatedPillarBlock)TFBlocks.SORTING_LOG.get()).m_49966_();
        SORT_LEAVES = ((Block)TFBlocks.SORTING_LEAVES.get()).m_49966_();
        SORT_SAPLING = ((SaplingBlock)TFBlocks.SORTING_SAPLING.get()).m_49966_();
        RAINBOW_LEAVES = ((Block)TFBlocks.RAINBOW_OAK_LEAVES.get()).m_49966_();
        RAINBOW_SAPLING = ((SaplingBlock)TFBlocks.RAINBOW_OAK_SAPLING.get()).m_49966_();
        ROOTS = ((Block)TFBlocks.ROOT_BLOCK.get()).m_49966_();
        GRASS = Blocks.f_50034_.m_49966_();
        TALL_GRASS = Blocks.f_50359_.m_49966_();
        FERN = Blocks.f_50035_.m_49966_();
        TALL_FERN = Blocks.f_50360_.m_49966_();
        POPPY = Blocks.f_50112_.m_49966_();
        DANDELION = Blocks.f_50111_.m_49966_();
        RED_TULIP = Blocks.f_50116_.m_49966_();
        ORANGE_TULIP = Blocks.f_50117_.m_49966_();
        PINK_TULIP = Blocks.f_50119_.m_49966_();
        WHITE_TULIP = Blocks.f_50118_.m_49966_();
        ALLIUM = Blocks.f_50114_.m_49966_();
        AZURE = Blocks.f_50115_.m_49966_();
        ORCHID = Blocks.f_50113_.m_49966_();
        LILY = Blocks.f_50071_.m_49966_();
        CORNFLOWER = Blocks.f_50121_.m_49966_();
        OXEYE = Blocks.f_50120_.m_49966_();
        MAYAPPLE = ((Block)TFBlocks.MAYAPPLE.get()).m_49966_();
        FIDDLEHEAD = ((Block)TFBlocks.FIDDLEHEAD.get()).m_49966_();
        MUSHGLOOM = ((Block)TFBlocks.MUSHGLOOM.get()).m_49966_();
        FIRE_JET = ((Block)TFBlocks.FIRE_JET.get()).m_49966_();
        SMOKER = ((Block)TFBlocks.SMOKER.get()).m_49966_();
        AIR = Blocks.f_50016_.m_49966_();
        LAVA = Blocks.f_49991_.m_49966_();
        WATER = Blocks.f_49990_.m_49966_();
        MYCELIUM = Blocks.f_50195_.m_49966_();
        UBEROUS_SOIL = ((Block)TFBlocks.UBEROUS_SOIL.get()).m_49966_();
        DIRT = Blocks.f_50493_.m_49966_();
        SAND = Blocks.f_49992_.m_49966_();
        STONE = Blocks.f_50069_.m_49966_();
        GRASS_BLOCK = Blocks.f_50440_.m_49966_();
        PODZOL = Blocks.f_50599_.m_49966_();
        COARSE_DIRT = Blocks.f_50546_.m_49966_();
        CICADA_JAR = ((Block)TFBlocks.CICADA_JAR.get()).m_49966_();
        FIREFLY_JAR = ((Block)TFBlocks.FIREFLY_JAR.get()).m_49966_();
        TROLLVIDR = ((Block)TFBlocks.TROLLVIDR.get()).m_49966_();
        TORCHBERRIES = (BlockState)((Block)TFBlocks.TORCHBERRY_PLANT.get()).m_49966_().m_61124_((Property)TorchberryPlantBlock.HAS_BERRIES, (Comparable)true);
        ROOT_STRAND = ((Block)TFBlocks.ROOT_STRAND.get()).m_49966_();
        HANGING_ROOTS = Blocks.f_152548_.m_49966_();
        PUMPKIN = Blocks.f_50133_.m_49966_();
        DEAD_BUSH = Blocks.f_50036_.m_49966_();
        BROWN_MUSHROOM = Blocks.f_50072_.m_49966_();
        RED_MUSHROOM = Blocks.f_50073_.m_49966_();
        JACK_O_LANTERN = Blocks.f_50144_.m_49966_();
        DEADROCK = ((Block)TFBlocks.DEADROCK.get()).m_49966_();
        WEATHERED_DEADROCK = ((Block)TFBlocks.WEATHERED_DEADROCK.get()).m_49966_();
        CRACKED_DEADROCK = ((Block)TFBlocks.CRACKED_DEADROCK.get()).m_49966_();
        SNOW = Blocks.f_50127_.m_49966_();
        POWDER_SNOW = Blocks.f_152499_.m_49966_();
        ICE = Blocks.f_50126_.m_49966_();
        PACKED_ICE = Blocks.f_50354_.m_49966_();
        MUSHROOM_STEM = Blocks.f_50182_.m_49966_();
        MUSHROOM_CAP_RED = (BlockState)Blocks.f_50181_.m_49966_().m_61124_((Property)HugeMushroomBlock.f_54132_, (Comparable)false);
        MUSHROOM_CAP_BROWN = (BlockState)Blocks.f_50180_.m_49966_().m_61124_((Property)HugeMushroomBlock.f_54132_, (Comparable)false);
    }
}
