// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.client.model;

import net.minecraftforge.eventbus.api.SubscribeEvent;
import twilightforest.client.model.entity.MoonwormModel;
import twilightforest.client.renderer.tileentity.CasketTileEntityRenderer;
import twilightforest.client.model.entity.FireflyModel;
import twilightforest.client.model.entity.CicadaModel;
import twilightforest.client.model.entity.legacy.UrGhastLegacyModel;
import twilightforest.client.model.entity.legacy.UpperGoblinKnightLegacyModel;
import twilightforest.client.model.entity.legacy.TrollLegacyModel;
import twilightforest.client.model.entity.legacy.TinyBirdLegacyModel;
import twilightforest.client.model.entity.legacy.SquirrelLegacyModel;
import twilightforest.client.model.entity.legacy.SnowQueenLegacyModel;
import twilightforest.client.model.entity.legacy.SlimeBeetleLegacyModel;
import twilightforest.client.model.entity.legacy.RedcapLegacyModel;
import twilightforest.client.model.entity.legacy.RavenLegacyModel;
import twilightforest.client.model.entity.legacy.QuestRamLegacyModel;
import twilightforest.client.model.entity.legacy.PinchBeetleLegacyModel;
import twilightforest.client.model.entity.legacy.NagaLegacyModel;
import twilightforest.client.model.entity.legacy.MinotaurLegacyModel;
import twilightforest.client.model.entity.legacy.MinoshroomLegacyModel;
import twilightforest.client.model.entity.legacy.LowerGoblinKnightLegacyModel;
import twilightforest.client.model.entity.legacy.KoboldLegacyModel;
import twilightforest.client.model.entity.legacy.HydraNeckLegacyModel;
import twilightforest.client.model.entity.legacy.HydraHeadLegacyModel;
import twilightforest.client.model.entity.legacy.HydraLegacyModel;
import twilightforest.client.model.entity.legacy.HelmetCrabLegacyModel;
import twilightforest.client.model.entity.legacy.FireBeetleLegacyModel;
import twilightforest.client.model.entity.legacy.DeerLegacyModel;
import twilightforest.client.model.entity.legacy.BoarLegacyModel;
import twilightforest.client.model.entity.legacy.BlockChainGoblinLegacyModel;
import twilightforest.client.model.entity.legacy.BighornLegacyModel;
import twilightforest.client.model.entity.YetiModel;
import twilightforest.client.model.entity.WraithModel;
import twilightforest.client.model.entity.UrGhastModel;
import twilightforest.client.model.entity.UpperGoblinKnightModel;
import twilightforest.client.model.entity.TrollModel;
import net.minecraft.client.model.SilverfishModel;
import twilightforest.client.model.entity.TinyBirdModel;
import twilightforest.client.model.entity.UnstableIceCoreModel;
import twilightforest.client.model.entity.SquirrelModel;
import twilightforest.client.model.entity.SpikeBlockModel;
import twilightforest.client.model.entity.SnowQueenModel;
import twilightforest.client.model.entity.SlimeBeetleModel;
import twilightforest.client.model.entity.SkeletonDruidModel;
import twilightforest.client.model.entity.RedcapModel;
import twilightforest.client.model.entity.RavenModel;
import twilightforest.client.model.entity.QuestRamModel;
import twilightforest.client.model.entity.ProtectionBoxModel;
import twilightforest.client.model.entity.PinchBeetleModel;
import twilightforest.client.model.entity.PenguinModel;
import twilightforest.client.model.entity.NagaModel;
import twilightforest.client.model.entity.MosquitoSwarmModel;
import twilightforest.client.model.entity.MinotaurModel;
import twilightforest.client.model.entity.MinoshroomModel;
import net.minecraft.client.model.SlimeModel;
import twilightforest.client.model.entity.LowerGoblinKnightModel;
import twilightforest.client.model.entity.LichModel;
import twilightforest.client.model.entity.KoboldModel;
import twilightforest.client.model.entity.KnightPhantomModel;
import twilightforest.client.model.entity.IceCrystalModel;
import twilightforest.client.model.entity.HydraNeckModel;
import twilightforest.client.model.entity.HydraMortarModel;
import twilightforest.client.model.entity.HydraModel;
import twilightforest.client.model.entity.HydraHeadModel;
import net.minecraft.client.model.WolfModel;
import twilightforest.client.model.entity.HelmetCrabModel;
import twilightforest.client.model.entity.HarbingerCubeModel;
import twilightforest.client.model.entity.FireBeetleModel;
import twilightforest.client.model.entity.DeerModel;
import twilightforest.client.model.entity.DeathTomeModel;
import twilightforest.client.model.entity.CubeOfAnnihilationModel;
import twilightforest.client.model.entity.ChainModel;
import twilightforest.client.model.entity.TFGhastModel;
import twilightforest.client.model.entity.CarminiteGolemModel;
import net.minecraft.client.model.SpiderModel;
import twilightforest.client.model.entity.BunnyModel;
import twilightforest.client.model.entity.BoarModel;
import twilightforest.client.model.entity.BlockChainGoblinModel;
import twilightforest.client.model.entity.BighornFurLayer;
import twilightforest.client.model.entity.BighornModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import twilightforest.client.model.entity.AlphaYetiModel;
import twilightforest.client.model.entity.AdherentModel;
import twilightforest.client.model.tileentity.legacy.UrGhastTrophyLegacyModel;
import twilightforest.client.model.tileentity.legacy.SnowQueenTrophyLegacyModel;
import twilightforest.client.model.tileentity.legacy.QuestRamTrophyLegacyModel;
import twilightforest.client.model.tileentity.legacy.MinoshroomTrophyLegacyModel;
import twilightforest.client.model.tileentity.legacy.HydraTrophyLegacyModel;
import twilightforest.client.model.tileentity.UrGhastTrophyModel;
import twilightforest.client.model.tileentity.SnowQueenTrophyModel;
import twilightforest.client.model.tileentity.QuestRamTrophyModel;
import twilightforest.client.model.tileentity.NagaTrophyModel;
import twilightforest.client.model.tileentity.MinoshroomTrophyModel;
import twilightforest.client.model.tileentity.LichTrophyModel;
import twilightforest.client.model.tileentity.KnightPhantomTrophyModel;
import twilightforest.client.model.tileentity.HydraTrophyModel;
import java.util.function.Supplier;
import twilightforest.client.model.tileentity.AlphaYetiTrophyModel;
import twilightforest.client.model.armor.YetiArmorModel;
import twilightforest.client.model.armor.PhantomArmorModel;
import twilightforest.client.model.armor.KnightmetalArmorModel;
import twilightforest.client.model.armor.FieryArmorModel;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import twilightforest.client.model.armor.ArcticArmorModel;
import net.minecraft.client.model.geom.LayerDefinitions;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = "twilightforest", value = { Dist.CLIENT }, bus = Mod.EventBusSubscriber.Bus.MOD)
public class TFLayerDefinitions
{
    @SubscribeEvent
    public static void registerLayers(final EntityRenderersEvent.RegisterLayerDefinitions event) {
        event.registerLayerDefinition(TFModelLayers.ARCTIC_ARMOR_INNER, () -> LayerDefinition.m_171565_(ArcticArmorModel.addPieces(LayerDefinitions.f_171107_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.ARCTIC_ARMOR_OUTER, () -> LayerDefinition.m_171565_(ArcticArmorModel.addPieces(LayerDefinitions.f_171106_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.FIERY_ARMOR_INNER, () -> LayerDefinition.m_171565_(FieryArmorModel.m_170681_(LayerDefinitions.f_171107_, 0.0f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.FIERY_ARMOR_OUTER, () -> LayerDefinition.m_171565_(FieryArmorModel.m_170681_(LayerDefinitions.f_171106_, 0.0f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.KNIGHTMETAL_ARMOR_INNER, () -> LayerDefinition.m_171565_(KnightmetalArmorModel.setup(LayerDefinitions.f_171107_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.KNIGHTMETAL_ARMOR_OUTER, () -> LayerDefinition.m_171565_(KnightmetalArmorModel.setup(LayerDefinitions.f_171106_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.PHANTOM_ARMOR_INNER, () -> LayerDefinition.m_171565_(PhantomArmorModel.addPieces(LayerDefinitions.f_171107_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.PHANTOM_ARMOR_OUTER, () -> LayerDefinition.m_171565_(PhantomArmorModel.addPieces(LayerDefinitions.f_171106_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.YETI_ARMOR_INNER, () -> LayerDefinition.m_171565_(YetiArmorModel.addPieces(LayerDefinitions.f_171107_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.YETI_ARMOR_OUTER, () -> LayerDefinition.m_171565_(YetiArmorModel.addPieces(LayerDefinitions.f_171106_), 64, 32));
        event.registerLayerDefinition(TFModelLayers.ALPHA_YETI_TROPHY, (Supplier)AlphaYetiTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.HYDRA_TROPHY, (Supplier)HydraTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.KNIGHT_PHANTOM_TROPHY, (Supplier)KnightPhantomTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.LICH_TROPHY, (Supplier)LichTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.MINOSHROOM_TROPHY, (Supplier)MinoshroomTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.NAGA_TROPHY, (Supplier)NagaTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.QUEST_RAM_TROPHY, (Supplier)QuestRamTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.SNOW_QUEEN_TROPHY, (Supplier)SnowQueenTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.UR_GHAST_TROPHY, (Supplier)UrGhastTrophyModel::createHead);
        event.registerLayerDefinition(TFModelLayers.LEGACY_HYDRA_TROPHY, (Supplier)HydraTrophyLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_MINOSHROOM_TROPHY, (Supplier)MinoshroomTrophyLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_QUEST_RAM_TROPHY, (Supplier)QuestRamTrophyLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_SNOW_QUEEN_TROPHY, (Supplier)SnowQueenTrophyLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_UR_GHAST_TROPHY, (Supplier)UrGhastTrophyLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.ADHERENT, (Supplier)AdherentModel::create);
        event.registerLayerDefinition(TFModelLayers.ALPHA_YETI, (Supplier)AlphaYetiModel::create);
        event.registerLayerDefinition(TFModelLayers.ARMORED_GIANT, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.BIGHORN_SHEEP, (Supplier)BighornModel::create);
        event.registerLayerDefinition(TFModelLayers.BIGHORN_SHEEP_FUR, (Supplier)BighornFurLayer::create);
        event.registerLayerDefinition(TFModelLayers.BLOCKCHAIN_GOBLIN, (Supplier)BlockChainGoblinModel::create);
        event.registerLayerDefinition(TFModelLayers.BOAR, (Supplier)BoarModel::create);
        event.registerLayerDefinition(TFModelLayers.BUNNY, (Supplier)BunnyModel::create);
        event.registerLayerDefinition(TFModelLayers.CARMINITE_BROODLING, (Supplier)SpiderModel::m_170985_);
        event.registerLayerDefinition(TFModelLayers.CARMINITE_GOLEM, (Supplier)CarminiteGolemModel::create);
        event.registerLayerDefinition(TFModelLayers.CARMINITE_GHASTGUARD, (Supplier)TFGhastModel::create);
        event.registerLayerDefinition(TFModelLayers.CARMINITE_GHASTLING, (Supplier)TFGhastModel::create);
        event.registerLayerDefinition(TFModelLayers.CHAIN, (Supplier)ChainModel::create);
        event.registerLayerDefinition(TFModelLayers.CUBE_OF_ANNIHILATION, (Supplier)CubeOfAnnihilationModel::create);
        event.registerLayerDefinition(TFModelLayers.DEATH_TOME, (Supplier)DeathTomeModel::create);
        event.registerLayerDefinition(TFModelLayers.DEER, (Supplier)DeerModel::create);
        event.registerLayerDefinition(TFModelLayers.FIRE_BEETLE, (Supplier)FireBeetleModel::create);
        event.registerLayerDefinition(TFModelLayers.GIANT_MINER, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.HARBINGER_CUBE, (Supplier)HarbingerCubeModel::create);
        event.registerLayerDefinition(TFModelLayers.HEDGE_SPIDER, (Supplier)SpiderModel::m_170985_);
        event.registerLayerDefinition(TFModelLayers.HELMET_CRAB, (Supplier)HelmetCrabModel::create);
        event.registerLayerDefinition(TFModelLayers.HOSTILE_WOLF, (Supplier)WolfModel::m_171088_);
        event.registerLayerDefinition(TFModelLayers.HYDRA_HEAD, (Supplier)HydraHeadModel::create);
        event.registerLayerDefinition(TFModelLayers.HYDRA, (Supplier)HydraModel::create);
        event.registerLayerDefinition(TFModelLayers.HYDRA_MORTAR, (Supplier)HydraMortarModel::create);
        event.registerLayerDefinition(TFModelLayers.HYDRA_NECK, (Supplier)HydraNeckModel::create);
        event.registerLayerDefinition(TFModelLayers.ICE_CRYSTAL, (Supplier)IceCrystalModel::create);
        event.registerLayerDefinition(TFModelLayers.KING_SPIDER, (Supplier)SpiderModel::m_170985_);
        event.registerLayerDefinition(TFModelLayers.KNIGHT_PHANTOM, (Supplier)KnightPhantomModel::create);
        event.registerLayerDefinition(TFModelLayers.KOBOLD, (Supplier)KoboldModel::create);
        event.registerLayerDefinition(TFModelLayers.LICH_MINION, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 64, 64));
        event.registerLayerDefinition(TFModelLayers.LICH, (Supplier)LichModel::create);
        event.registerLayerDefinition(TFModelLayers.LOWER_GOBLIN_KNIGHT, (Supplier)LowerGoblinKnightModel::create);
        event.registerLayerDefinition(TFModelLayers.LOYAL_ZOMBIE, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 64, 64));
        event.registerLayerDefinition(TFModelLayers.MAZE_SLIME, (Supplier)SlimeModel::m_170958_);
        event.registerLayerDefinition(TFModelLayers.MAZE_SLIME_OUTER, (Supplier)SlimeModel::m_170956_);
        event.registerLayerDefinition(TFModelLayers.MINOSHROOM, (Supplier)MinoshroomModel::create);
        event.registerLayerDefinition(TFModelLayers.MINOTAUR, (Supplier)MinotaurModel::create);
        event.registerLayerDefinition(TFModelLayers.MIST_WOLF, (Supplier)WolfModel::m_171088_);
        event.registerLayerDefinition(TFModelLayers.MOSQUITO_SWARM, (Supplier)MosquitoSwarmModel::create);
        event.registerLayerDefinition(TFModelLayers.NAGA, (Supplier)NagaModel::create);
        event.registerLayerDefinition(TFModelLayers.NAGA_BODY, (Supplier)NagaModel::create);
        event.registerLayerDefinition(TFModelLayers.NOOP, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 0, 0));
        event.registerLayerDefinition(TFModelLayers.PENGUIN, (Supplier)PenguinModel::create);
        event.registerLayerDefinition(TFModelLayers.PINCH_BEETLE, (Supplier)PinchBeetleModel::create);
        event.registerLayerDefinition(TFModelLayers.PROTECTION_BOX, () -> LayerDefinition.m_171565_(ProtectionBoxModel.createMesh(), 16, 16));
        event.registerLayerDefinition(TFModelLayers.QUEST_RAM, (Supplier)QuestRamModel::create);
        event.registerLayerDefinition(TFModelLayers.RAVEN, (Supplier)RavenModel::create);
        event.registerLayerDefinition(TFModelLayers.REDCAP, (Supplier)RedcapModel::create);
        event.registerLayerDefinition(TFModelLayers.REDCAP_ARMOR_INNER, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(new CubeDeformation(0.25f), 0.7f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.REDCAP_ARMOR_OUTER, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(new CubeDeformation(0.65f), 0.7f), 64, 32));
        event.registerLayerDefinition(TFModelLayers.RISING_ZOMBIE, () -> LayerDefinition.m_171565_(HumanoidModel.m_170681_(CubeDeformation.f_171458_, 0.0f), 64, 64));
        event.registerLayerDefinition(TFModelLayers.ROVING_CUBE, (Supplier)CubeOfAnnihilationModel::create);
        event.registerLayerDefinition(TFModelLayers.SKELETON_DRUID, (Supplier)SkeletonDruidModel::create);
        event.registerLayerDefinition(TFModelLayers.SKELETON_DRUID_INNER_ARMOR, () -> SkeletonDruidModel.create(LayerDefinitions.f_171107_));
        event.registerLayerDefinition(TFModelLayers.SKELETON_DRUID_OUTER_ARMOR, () -> SkeletonDruidModel.create(LayerDefinitions.f_171106_));
        event.registerLayerDefinition(TFModelLayers.SLIME_BEETLE, (Supplier)SlimeBeetleModel::create);
        event.registerLayerDefinition(TFModelLayers.SLIME_BEETLE_TAIL, (Supplier)SlimeBeetleModel::create);
        event.registerLayerDefinition(TFModelLayers.SNOW_QUEEN, (Supplier)SnowQueenModel::create);
        event.registerLayerDefinition(TFModelLayers.CHAIN_BLOCK, (Supplier)SpikeBlockModel::create);
        event.registerLayerDefinition(TFModelLayers.SQUIRREL, (Supplier)SquirrelModel::create);
        event.registerLayerDefinition(TFModelLayers.STABLE_ICE_CORE, (Supplier)UnstableIceCoreModel::create);
        event.registerLayerDefinition(TFModelLayers.SWARM_SPIDER, (Supplier)SpiderModel::m_170985_);
        event.registerLayerDefinition(TFModelLayers.TINY_BIRD, (Supplier)TinyBirdModel::create);
        event.registerLayerDefinition(TFModelLayers.TOWERWOOD_BORER, (Supplier)SilverfishModel::m_170928_);
        event.registerLayerDefinition(TFModelLayers.TROLL, (Supplier)TrollModel::create);
        event.registerLayerDefinition(TFModelLayers.UNSTABLE_ICE_CORE, (Supplier)UnstableIceCoreModel::create);
        event.registerLayerDefinition(TFModelLayers.UPPER_GOBLIN_KNIGHT, (Supplier)UpperGoblinKnightModel::create);
        event.registerLayerDefinition(TFModelLayers.UR_GHAST, (Supplier)UrGhastModel::create);
        event.registerLayerDefinition(TFModelLayers.WINTER_WOLF, (Supplier)WolfModel::m_171088_);
        event.registerLayerDefinition(TFModelLayers.WRAITH, (Supplier)WraithModel::create);
        event.registerLayerDefinition(TFModelLayers.YETI, (Supplier)YetiModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_BIGHORN_SHEEP, (Supplier)BighornLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_BLOCKCHAIN_GOBLIN, (Supplier)BlockChainGoblinLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_BOAR, (Supplier)BoarLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_DEER, (Supplier)DeerLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_FIRE_BEETLE, (Supplier)FireBeetleLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_HELMET_CRAB, (Supplier)HelmetCrabLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_HYDRA, (Supplier)HydraLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_HYDRA_HEAD, (Supplier)HydraHeadLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_HYDRA_NECK, (Supplier)HydraNeckLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_KOBOLD, (Supplier)KoboldLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_LOWER_GOBLIN_KNIGHT, (Supplier)LowerGoblinKnightLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_MINOSHROOM, (Supplier)MinoshroomLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_MINOTAUR, (Supplier)MinotaurLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_NAGA, (Supplier)NagaLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_NAGA_BODY, (Supplier)NagaLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_PINCH_BEETLE, (Supplier)PinchBeetleLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_QUEST_RAM, (Supplier)QuestRamLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_RAVEN, (Supplier)RavenLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_REDCAP, (Supplier)RedcapLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_SLIME_BEETLE, (Supplier)SlimeBeetleLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_SLIME_BEETLE_TAIL, (Supplier)SlimeBeetleLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_SNOW_QUEEN, (Supplier)SnowQueenLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_SQUIRREL, (Supplier)SquirrelLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_TINY_BIRD, (Supplier)TinyBirdLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_TROLL, (Supplier)TrollLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_UPPER_GOBLIN_KNIGHT, (Supplier)UpperGoblinKnightLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.LEGACY_UR_GHAST, (Supplier)UrGhastLegacyModel::create);
        event.registerLayerDefinition(TFModelLayers.CICADA, (Supplier)CicadaModel::create);
        event.registerLayerDefinition(TFModelLayers.FIREFLY, (Supplier)FireflyModel::create);
        event.registerLayerDefinition(TFModelLayers.KEEPSAKE_CASKET, (Supplier)CasketTileEntityRenderer::create);
        event.registerLayerDefinition(TFModelLayers.MOONWORM, (Supplier)MoonwormModel::create);
    }
}
