// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.client.model;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.model.geom.ModelLayerLocation;

public class TFModelLayers
{
    public static final ModelLayerLocation ARCTIC_ARMOR_INNER;
    public static final ModelLayerLocation ARCTIC_ARMOR_OUTER;
    public static final ModelLayerLocation FIERY_ARMOR_INNER;
    public static final ModelLayerLocation FIERY_ARMOR_OUTER;
    public static final ModelLayerLocation KNIGHTMETAL_ARMOR_INNER;
    public static final ModelLayerLocation KNIGHTMETAL_ARMOR_OUTER;
    public static final ModelLayerLocation PHANTOM_ARMOR_INNER;
    public static final ModelLayerLocation PHANTOM_ARMOR_OUTER;
    public static final ModelLayerLocation YETI_ARMOR_INNER;
    public static final ModelLayerLocation YETI_ARMOR_OUTER;
    public static final ModelLayerLocation ALPHA_YETI_TROPHY;
    public static final ModelLayerLocation HYDRA_TROPHY;
    public static final ModelLayerLocation KNIGHT_PHANTOM_TROPHY;
    public static final ModelLayerLocation LICH_TROPHY;
    public static final ModelLayerLocation MINOSHROOM_TROPHY;
    public static final ModelLayerLocation NAGA_TROPHY;
    public static final ModelLayerLocation QUEST_RAM_TROPHY;
    public static final ModelLayerLocation SNOW_QUEEN_TROPHY;
    public static final ModelLayerLocation UR_GHAST_TROPHY;
    public static final ModelLayerLocation LEGACY_HYDRA_TROPHY;
    public static final ModelLayerLocation LEGACY_MINOSHROOM_TROPHY;
    public static final ModelLayerLocation LEGACY_QUEST_RAM_TROPHY;
    public static final ModelLayerLocation LEGACY_SNOW_QUEEN_TROPHY;
    public static final ModelLayerLocation LEGACY_UR_GHAST_TROPHY;
    public static final ModelLayerLocation ADHERENT;
    public static final ModelLayerLocation ALPHA_YETI;
    public static final ModelLayerLocation ARMORED_GIANT;
    public static final ModelLayerLocation BIGHORN_SHEEP;
    public static final ModelLayerLocation BIGHORN_SHEEP_FUR;
    public static final ModelLayerLocation BLOCKCHAIN_GOBLIN;
    public static final ModelLayerLocation BOAR;
    public static final ModelLayerLocation BUNNY;
    public static final ModelLayerLocation CARMINITE_BROODLING;
    public static final ModelLayerLocation CARMINITE_GHASTGUARD;
    public static final ModelLayerLocation CARMINITE_GHASTLING;
    public static final ModelLayerLocation CARMINITE_GOLEM;
    public static final ModelLayerLocation CHAIN;
    public static final ModelLayerLocation DEATH_TOME;
    public static final ModelLayerLocation DEER;
    public static final ModelLayerLocation FIRE_BEETLE;
    public static final ModelLayerLocation GIANT_MINER;
    public static final ModelLayerLocation HARBINGER_CUBE;
    public static final ModelLayerLocation HEDGE_SPIDER;
    public static final ModelLayerLocation HELMET_CRAB;
    public static final ModelLayerLocation HOSTILE_WOLF;
    public static final ModelLayerLocation HYDRA;
    public static final ModelLayerLocation HYDRA_HEAD;
    public static final ModelLayerLocation HYDRA_NECK;
    public static final ModelLayerLocation ICE_CRYSTAL;
    public static final ModelLayerLocation KING_SPIDER;
    public static final ModelLayerLocation KNIGHT_PHANTOM;
    public static final ModelLayerLocation KOBOLD;
    public static final ModelLayerLocation LICH;
    public static final ModelLayerLocation LICH_MINION;
    public static final ModelLayerLocation LOWER_GOBLIN_KNIGHT;
    public static final ModelLayerLocation LOYAL_ZOMBIE;
    public static final ModelLayerLocation MAZE_SLIME;
    public static final ModelLayerLocation MAZE_SLIME_OUTER;
    public static final ModelLayerLocation MINOSHROOM;
    public static final ModelLayerLocation MINOTAUR;
    public static final ModelLayerLocation MIST_WOLF;
    public static final ModelLayerLocation MOSQUITO_SWARM;
    public static final ModelLayerLocation NAGA;
    public static final ModelLayerLocation NAGA_BODY;
    public static final ModelLayerLocation NOOP;
    public static final ModelLayerLocation PENGUIN;
    public static final ModelLayerLocation PINCH_BEETLE;
    public static final ModelLayerLocation QUEST_RAM;
    public static final ModelLayerLocation RAVEN;
    public static final ModelLayerLocation REDCAP;
    public static final ModelLayerLocation REDCAP_ARMOR_OUTER;
    public static final ModelLayerLocation REDCAP_ARMOR_INNER;
    public static final ModelLayerLocation RISING_ZOMBIE;
    public static final ModelLayerLocation ROVING_CUBE;
    public static final ModelLayerLocation SKELETON_DRUID;
    public static final ModelLayerLocation SKELETON_DRUID_INNER_ARMOR;
    public static final ModelLayerLocation SKELETON_DRUID_OUTER_ARMOR;
    public static final ModelLayerLocation SLIME_BEETLE;
    public static final ModelLayerLocation SLIME_BEETLE_TAIL;
    public static final ModelLayerLocation SNOW_QUEEN;
    public static final ModelLayerLocation SQUIRREL;
    public static final ModelLayerLocation STABLE_ICE_CORE;
    public static final ModelLayerLocation SWARM_SPIDER;
    public static final ModelLayerLocation TINY_BIRD;
    public static final ModelLayerLocation TOWERWOOD_BORER;
    public static final ModelLayerLocation TROLL;
    public static final ModelLayerLocation UNSTABLE_ICE_CORE;
    public static final ModelLayerLocation UPPER_GOBLIN_KNIGHT;
    public static final ModelLayerLocation UR_GHAST;
    public static final ModelLayerLocation WINTER_WOLF;
    public static final ModelLayerLocation WRAITH;
    public static final ModelLayerLocation YETI;
    public static final ModelLayerLocation LEGACY_BIGHORN_SHEEP;
    public static final ModelLayerLocation LEGACY_BLOCKCHAIN_GOBLIN;
    public static final ModelLayerLocation LEGACY_BOAR;
    public static final ModelLayerLocation LEGACY_DEER;
    public static final ModelLayerLocation LEGACY_FIRE_BEETLE;
    public static final ModelLayerLocation LEGACY_HELMET_CRAB;
    public static final ModelLayerLocation LEGACY_HYDRA;
    public static final ModelLayerLocation LEGACY_HYDRA_HEAD;
    public static final ModelLayerLocation LEGACY_HYDRA_NECK;
    public static final ModelLayerLocation LEGACY_KOBOLD;
    public static final ModelLayerLocation LEGACY_LOWER_GOBLIN_KNIGHT;
    public static final ModelLayerLocation LEGACY_MINOSHROOM;
    public static final ModelLayerLocation LEGACY_MINOTAUR;
    public static final ModelLayerLocation LEGACY_NAGA;
    public static final ModelLayerLocation LEGACY_NAGA_BODY;
    public static final ModelLayerLocation LEGACY_PINCH_BEETLE;
    public static final ModelLayerLocation LEGACY_QUEST_RAM;
    public static final ModelLayerLocation LEGACY_RAVEN;
    public static final ModelLayerLocation LEGACY_REDCAP;
    public static final ModelLayerLocation LEGACY_SLIME_BEETLE;
    public static final ModelLayerLocation LEGACY_SLIME_BEETLE_TAIL;
    public static final ModelLayerLocation LEGACY_SNOW_QUEEN;
    public static final ModelLayerLocation LEGACY_SQUIRREL;
    public static final ModelLayerLocation LEGACY_TINY_BIRD;
    public static final ModelLayerLocation LEGACY_TROLL;
    public static final ModelLayerLocation LEGACY_UPPER_GOBLIN_KNIGHT;
    public static final ModelLayerLocation LEGACY_UR_GHAST;
    public static final ModelLayerLocation CHAIN_BLOCK;
    public static final ModelLayerLocation CUBE_OF_ANNIHILATION;
    public static final ModelLayerLocation PROTECTION_BOX;
    public static final ModelLayerLocation HYDRA_MORTAR;
    public static final ModelLayerLocation CICADA;
    public static final ModelLayerLocation FIREFLY;
    public static final ModelLayerLocation KEEPSAKE_CASKET;
    public static final ModelLayerLocation MOONWORM;
    
    private static ModelLayerLocation register(final String p_171294_) {
        return register(p_171294_, "main");
    }
    
    private static ModelLayerLocation register(final String p_171301_, final String p_171302_) {
        return new ModelLayerLocation(new ResourceLocation("twilightforest", p_171301_), p_171302_);
    }
    
    static {
        ARCTIC_ARMOR_INNER = register("arctic_armor", "inner");
        ARCTIC_ARMOR_OUTER = register("arctic_armor", "outer");
        FIERY_ARMOR_INNER = register("fiery_armor", "inner");
        FIERY_ARMOR_OUTER = register("fiery_armor", "outer");
        KNIGHTMETAL_ARMOR_INNER = register("knightmetal_armor", "inner");
        KNIGHTMETAL_ARMOR_OUTER = register("knightmetal_armor", "outer");
        PHANTOM_ARMOR_INNER = register("phantom_armor", "inner");
        PHANTOM_ARMOR_OUTER = register("phantom_armor", "outer");
        YETI_ARMOR_INNER = register("yeti_armor", "inner");
        YETI_ARMOR_OUTER = register("yeti_armor", "outer");
        ALPHA_YETI_TROPHY = register("alpha_yeti_trophy");
        HYDRA_TROPHY = register("hydra_trophy");
        KNIGHT_PHANTOM_TROPHY = register("knight_phantom_trophy");
        LICH_TROPHY = register("lich_trophy");
        MINOSHROOM_TROPHY = register("minoshroom_trophy");
        NAGA_TROPHY = register("naga_trophy");
        QUEST_RAM_TROPHY = register("quest_ram_trophy");
        SNOW_QUEEN_TROPHY = register("snow_queen_trophy");
        UR_GHAST_TROPHY = register("ur_ghast_trophy");
        LEGACY_HYDRA_TROPHY = register("legacy_hydra_trophy");
        LEGACY_MINOSHROOM_TROPHY = register("legacy_minoshroom_trophy");
        LEGACY_QUEST_RAM_TROPHY = register("legacy_quest_ram_trophy");
        LEGACY_SNOW_QUEEN_TROPHY = register("legacy_snow_queen_trophy");
        LEGACY_UR_GHAST_TROPHY = register("legacy_ur_ghast_trophy");
        ADHERENT = register("adherent");
        ALPHA_YETI = register("alpha_yeti");
        ARMORED_GIANT = register("armored_giant");
        BIGHORN_SHEEP = register("bighorn_sheep");
        BIGHORN_SHEEP_FUR = register("bighorn_sheep", "fur");
        BLOCKCHAIN_GOBLIN = register("blockchain_goblin");
        BOAR = register("boar");
        BUNNY = register("bunny");
        CARMINITE_BROODLING = register("carminite_broodling");
        CARMINITE_GHASTGUARD = register("carminite_ghastguard");
        CARMINITE_GHASTLING = register("carminite_ghastling");
        CARMINITE_GOLEM = register("carminite_golem");
        CHAIN = register("chain");
        DEATH_TOME = register("death_tome");
        DEER = register("deer");
        FIRE_BEETLE = register("fire_beetle");
        GIANT_MINER = register("giant_miner");
        HARBINGER_CUBE = register("harbinger_cube");
        HEDGE_SPIDER = register("hedge_spider");
        HELMET_CRAB = register("helmet_crab");
        HOSTILE_WOLF = register("hostile_wolf");
        HYDRA = register("hydra");
        HYDRA_HEAD = register("hydra_head");
        HYDRA_NECK = register("hydra_neck");
        ICE_CRYSTAL = register("ice_crystal");
        KING_SPIDER = register("king_spider");
        KNIGHT_PHANTOM = register("knight_phantom");
        KOBOLD = register("kobold");
        LICH = register("lich");
        LICH_MINION = register("lich_minion");
        LOWER_GOBLIN_KNIGHT = register("lower_goblin_knight");
        LOYAL_ZOMBIE = register("loyal_zombie");
        MAZE_SLIME = register("maze_slime");
        MAZE_SLIME_OUTER = register("maze_slime", "outer");
        MINOSHROOM = register("minoshroom");
        MINOTAUR = register("minotaur");
        MIST_WOLF = register("mist_wolf");
        MOSQUITO_SWARM = register("mosquito_swarm");
        NAGA = register("naga");
        NAGA_BODY = register("naga_body");
        NOOP = register("noop");
        PENGUIN = register("penguin");
        PINCH_BEETLE = register("pinch_beetle");
        QUEST_RAM = register("quest_ram");
        RAVEN = register("raven");
        REDCAP = register("redcap");
        REDCAP_ARMOR_OUTER = register("redcap", "outer");
        REDCAP_ARMOR_INNER = register("redcap", "inner");
        RISING_ZOMBIE = register("rising_zombie");
        ROVING_CUBE = register("roving_cube");
        SKELETON_DRUID = register("skeleton_druid");
        SKELETON_DRUID_INNER_ARMOR = register("skeleton_druid", "inner_armor");
        SKELETON_DRUID_OUTER_ARMOR = register("skeleton_druid", "outer_armor");
        SLIME_BEETLE = register("slime_beetle");
        SLIME_BEETLE_TAIL = register("slime_beetle", "tail");
        SNOW_QUEEN = register("snow_queen");
        SQUIRREL = register("squirrel");
        STABLE_ICE_CORE = register("stable_ice_core");
        SWARM_SPIDER = register("swarm_spider");
        TINY_BIRD = register("tiny_bird");
        TOWERWOOD_BORER = register("towerwood_borer");
        TROLL = register("troll");
        UNSTABLE_ICE_CORE = register("unstable_ice_core");
        UPPER_GOBLIN_KNIGHT = register("upper_goblin_knight");
        UR_GHAST = register("ur_ghast");
        WINTER_WOLF = register("winter_wolf");
        WRAITH = register("wraith");
        YETI = register("yeti");
        LEGACY_BIGHORN_SHEEP = register("legacy_bighorn_sheep");
        LEGACY_BLOCKCHAIN_GOBLIN = register("legacy_blockchain_goblin");
        LEGACY_BOAR = register("legacy_boar");
        LEGACY_DEER = register("legacy_deer");
        LEGACY_FIRE_BEETLE = register("legacy_fire_beetle");
        LEGACY_HELMET_CRAB = register("legacy_helmet_crab");
        LEGACY_HYDRA = register("legacy_hydra");
        LEGACY_HYDRA_HEAD = register("legacy_hydra_head");
        LEGACY_HYDRA_NECK = register("legacy_hydra_neck");
        LEGACY_KOBOLD = register("legacy_kobold");
        LEGACY_LOWER_GOBLIN_KNIGHT = register("legacy_lower_goblin_knight");
        LEGACY_MINOSHROOM = register("legacy_minoshroom");
        LEGACY_MINOTAUR = register("legacy_minotaur");
        LEGACY_NAGA = register("legacy_naga");
        LEGACY_NAGA_BODY = register("legacy_naga_body");
        LEGACY_PINCH_BEETLE = register("legacy_pinch_beetle");
        LEGACY_QUEST_RAM = register("legacy_quest_ram");
        LEGACY_RAVEN = register("legacy_raven");
        LEGACY_REDCAP = register("legacy_redcap");
        LEGACY_SLIME_BEETLE = register("legacy_slime_beetle");
        LEGACY_SLIME_BEETLE_TAIL = register("legacy_slime_beetle", "tail");
        LEGACY_SNOW_QUEEN = register("legacy_snow_queen");
        LEGACY_SQUIRREL = register("legacy_squirrel");
        LEGACY_TINY_BIRD = register("legacy_tiny_bird");
        LEGACY_TROLL = register("legacy_troll");
        LEGACY_UPPER_GOBLIN_KNIGHT = register("legacy_upper_goblin_knight");
        LEGACY_UR_GHAST = register("legacy_ur_ghast");
        CHAIN_BLOCK = register("chain_block");
        CUBE_OF_ANNIHILATION = register("cube_of_annihilation");
        PROTECTION_BOX = register("protection_box");
        HYDRA_MORTAR = register("hydra_mortar");
        CICADA = register("cicada");
        FIREFLY = register("firefly");
        KEEPSAKE_CASKET = register("keepsake_casket");
        MOONWORM = register("moonworm");
    }
}
