// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.worldgen;

import net.minecraft.state.Property;
import net.minecraft.block.HugeMushroomBlock;
import net.minecraft.block.Block;
import twilightforest.block.TFBlocks;
import net.minecraft.block.RotatedPillarBlock;
import net.minecraft.block.Blocks;
import net.minecraft.block.BlockState;

public final class BlockConstants
{
    public static final BlockState SPRUCE_LOG;
    public static final BlockState SPRUCE_LEAVES;
    public static final BlockState JUNGLE_LOG;
    public static final BlockState OAK_LEAVES;
    public static final BlockState TOAK_LOG;
    public static final BlockState TOAK_WOOD;
    public static final BlockState TOAK_LEAVES;
    public static final BlockState CANOPY_LOG;
    public static final BlockState CANOPY_LEAVES;
    public static final BlockState MANGROVE_LOG;
    public static final BlockState MANGROVE_WOOD;
    public static final BlockState MANGROVE_LEAVES;
    public static final BlockState DARKWOOD_LOG;
    public static final BlockState DARKWOOD_LEAVES;
    public static final BlockState TIME_LOG;
    public static final BlockState TIME_WOOD;
    public static final BlockState TIME_LEAVES;
    public static final BlockState TRANSFORM_LOG;
    public static final BlockState TRANSFORM_LEAVES;
    public static final BlockState MINING_LOG;
    public static final BlockState MINING_WOOD;
    public static final BlockState MINING_LEAVES;
    public static final BlockState SORT_LOG;
    public static final BlockState SORT_LEAVES;
    public static final BlockState RAINBOW_LEAVES;
    public static final BlockState ROOTS;
    public static final BlockState GRASS;
    public static final BlockState TALL_GRASS;
    public static final BlockState FERN;
    public static final BlockState TALL_FERN;
    public static final BlockState POPPY;
    public static final BlockState DANDELION;
    public static final BlockState RED_TULIP;
    public static final BlockState ORANGE_TULIP;
    public static final BlockState PINK_TULIP;
    public static final BlockState WHITE_TULIP;
    public static final BlockState ALLIUM;
    public static final BlockState AZURE;
    public static final BlockState ORCHID;
    public static final BlockState LILY;
    public static final BlockState CORNFLOWER;
    public static final BlockState OXEYE;
    public static final BlockState MAYAPPLE;
    public static final BlockState FIDDLEHEAD;
    public static final BlockState MUSHGLOOM;
    public static final BlockState FIRE_JET;
    public static final BlockState SMOKER;
    public static final BlockState AIR;
    public static final BlockState MYCELIUM;
    public static final BlockState UBEROUS_SOIL;
    public static final BlockState DIRT;
    public static final BlockState STONE;
    public static final BlockState GRASS_BLOCK;
    public static final BlockState PODZOL;
    public static final BlockState COARSE_DIRT;
    public static final BlockState FIREFLY_JAR;
    public static final BlockState PUMPKIN;
    public static final BlockState DEAD_BUSH;
    public static final BlockState BROWN_MUSHROOM;
    public static final BlockState JACK_O_LANTERN;
    public static final BlockState DEADROCK;
    public static final BlockState WEATHERED_DEADROCK;
    public static final BlockState CRACKED_DEADROCK;
    public static final BlockState SNOW;
    public static final BlockState PACKED_ICE;
    public static final BlockState MUSHROOM_STEM;
    public static final BlockState MUSHROOM_CAP_RED;
    public static final BlockState MUSHROOM_CAP_BROWN;
    
    static {
        SPRUCE_LOG = Blocks.field_196618_L.func_176223_P();
        SPRUCE_LEAVES = Blocks.field_196645_X.func_176223_P();
        JUNGLE_LOG = Blocks.field_196620_N.func_176223_P();
        OAK_LEAVES = Blocks.field_196642_W.func_176223_P();
        TOAK_LOG = ((RotatedPillarBlock)TFBlocks.oak_log.get()).func_176223_P();
        TOAK_WOOD = ((RotatedPillarBlock)TFBlocks.oak_wood.get()).func_176223_P();
        TOAK_LEAVES = ((Block)TFBlocks.oak_leaves.get()).func_176223_P();
        CANOPY_LOG = ((RotatedPillarBlock)TFBlocks.canopy_log.get()).func_176223_P();
        CANOPY_LEAVES = ((Block)TFBlocks.canopy_leaves.get()).func_176223_P();
        MANGROVE_LOG = ((RotatedPillarBlock)TFBlocks.mangrove_log.get()).func_176223_P();
        MANGROVE_WOOD = ((RotatedPillarBlock)TFBlocks.mangrove_wood.get()).func_176223_P();
        MANGROVE_LEAVES = ((Block)TFBlocks.mangrove_leaves.get()).func_176223_P();
        DARKWOOD_LOG = ((RotatedPillarBlock)TFBlocks.dark_log.get()).func_176223_P();
        DARKWOOD_LEAVES = ((Block)TFBlocks.dark_leaves.get()).func_176223_P();
        TIME_LOG = ((RotatedPillarBlock)TFBlocks.time_log.get()).func_176223_P();
        TIME_WOOD = ((RotatedPillarBlock)TFBlocks.time_wood.get()).func_176223_P();
        TIME_LEAVES = ((Block)TFBlocks.time_leaves.get()).func_176223_P();
        TRANSFORM_LOG = ((RotatedPillarBlock)TFBlocks.transformation_log.get()).func_176223_P();
        TRANSFORM_LEAVES = ((Block)TFBlocks.transformation_leaves.get()).func_176223_P();
        MINING_LOG = ((RotatedPillarBlock)TFBlocks.mining_log.get()).func_176223_P();
        MINING_WOOD = ((RotatedPillarBlock)TFBlocks.mining_wood.get()).func_176223_P();
        MINING_LEAVES = ((Block)TFBlocks.mining_leaves.get()).func_176223_P();
        SORT_LOG = ((RotatedPillarBlock)TFBlocks.sorting_log.get()).func_176223_P();
        SORT_LEAVES = ((Block)TFBlocks.sorting_leaves.get()).func_176223_P();
        RAINBOW_LEAVES = ((Block)TFBlocks.rainboak_leaves.get()).func_176223_P();
        ROOTS = ((Block)TFBlocks.root.get()).func_176223_P();
        GRASS = Blocks.field_150349_c.func_176223_P();
        TALL_GRASS = Blocks.field_196804_gh.func_176223_P();
        FERN = Blocks.field_196554_aH.func_176223_P();
        TALL_FERN = Blocks.field_196805_gi.func_176223_P();
        POPPY = Blocks.field_196606_bd.func_176223_P();
        DANDELION = Blocks.field_196605_bc.func_176223_P();
        RED_TULIP = Blocks.field_196612_bh.func_176223_P();
        ORANGE_TULIP = Blocks.field_196613_bi.func_176223_P();
        PINK_TULIP = Blocks.field_196615_bk.func_176223_P();
        WHITE_TULIP = Blocks.field_196614_bj.func_176223_P();
        ALLIUM = Blocks.field_196609_bf.func_176223_P();
        AZURE = Blocks.field_196610_bg.func_176223_P();
        ORCHID = Blocks.field_196607_be.func_176223_P();
        LILY = Blocks.field_222383_bA.func_176223_P();
        CORNFLOWER = Blocks.field_222387_by.func_176223_P();
        OXEYE = Blocks.field_196616_bl.func_176223_P();
        MAYAPPLE = ((Block)TFBlocks.mayapple.get()).func_176223_P();
        FIDDLEHEAD = ((Block)TFBlocks.fiddlehead.get()).func_176223_P();
        MUSHGLOOM = ((Block)TFBlocks.mushgloom.get()).func_176223_P();
        FIRE_JET = ((Block)TFBlocks.fire_jet.get()).func_176223_P();
        SMOKER = ((Block)TFBlocks.smoker.get()).func_176223_P();
        AIR = Blocks.field_150350_a.func_176223_P();
        MYCELIUM = Blocks.field_150391_bh.func_176223_P();
        UBEROUS_SOIL = ((Block)TFBlocks.uberous_soil.get()).func_176223_P();
        DIRT = Blocks.field_150346_d.func_176223_P();
        STONE = Blocks.field_150348_b.func_176223_P();
        GRASS_BLOCK = Blocks.field_196658_i.func_176223_P();
        PODZOL = Blocks.field_196661_l.func_176223_P();
        COARSE_DIRT = Blocks.field_196660_k.func_176223_P();
        FIREFLY_JAR = ((Block)TFBlocks.firefly_jar.get()).func_176223_P();
        PUMPKIN = Blocks.field_150423_aK.func_176223_P();
        DEAD_BUSH = Blocks.field_196555_aI.func_176223_P();
        BROWN_MUSHROOM = Blocks.field_150338_P.func_176223_P();
        JACK_O_LANTERN = Blocks.field_196628_cT.func_176223_P();
        DEADROCK = ((Block)TFBlocks.deadrock.get()).func_176223_P();
        WEATHERED_DEADROCK = ((Block)TFBlocks.deadrock_weathered.get()).func_176223_P();
        CRACKED_DEADROCK = ((Block)TFBlocks.deadrock_cracked.get()).func_176223_P();
        SNOW = Blocks.field_196604_cC.func_176223_P();
        PACKED_ICE = Blocks.field_150403_cj.func_176223_P();
        MUSHROOM_STEM = Blocks.field_196706_do.func_176223_P();
        MUSHROOM_CAP_RED = (BlockState)Blocks.field_150419_aX.func_176223_P().func_206870_a((Property)HugeMushroomBlock.field_196460_A, (Comparable)false);
        MUSHROOM_CAP_BROWN = (BlockState)Blocks.field_150420_aW.func_176223_P().func_206870_a((Property)HugeMushroomBlock.field_196460_A, (Comparable)false);
    }
}
