// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.worldgen;

import twilightforest.TFSounds;
import net.minecraft.world.gen.blockstateprovider.WeightedBlockStateProvider;
import net.minecraft.world.gen.feature.NoFeatureConfig;
import net.minecraft.world.gen.feature.MultipleRandomFeatureConfig;
import net.minecraft.world.gen.feature.TwoFeatureChoiceConfig;
import java.util.Set;
import com.google.common.collect.ImmutableSet;
import net.minecraft.block.Blocks;
import net.minecraft.world.gen.feature.OreFeatureConfig;
import twilightforest.world.feature.config.CaveStalactiteConfig;
import net.minecraft.world.gen.feature.SphereReplaceConfig;
import net.minecraft.world.gen.feature.BlockStateFeatureConfig;
import java.util.List;
import net.minecraft.world.gen.feature.SingleRandomFeature;
import net.minecraft.world.gen.feature.AbstractFeatureSizeType;
import net.minecraft.world.gen.trunkplacer.AbstractTrunkPlacer;
import net.minecraft.world.gen.foliageplacer.FoliagePlacer;
import net.minecraft.world.gen.feature.TwoLayerFeature;
import net.minecraft.world.gen.trunkplacer.StraightTrunkPlacer;
import net.minecraft.world.gen.foliageplacer.BushFoliagePlacer;
import net.minecraft.world.gen.feature.FeatureSpread;
import net.minecraft.world.gen.placement.IPlacementConfig;
import net.minecraft.world.gen.placement.AtSurfaceWithExtraConfig;
import net.minecraft.world.gen.placement.Placement;
import twilightforest.world.feature.TFBiomeFeatures;
import twilightforest.TwilightForestMod;
import net.minecraft.world.gen.feature.Features;
import net.minecraft.world.gen.blockplacer.SimpleBlockPlacer;
import net.minecraft.world.gen.feature.IFeatureConfig;
import net.minecraft.world.gen.blockplacer.BlockPlacer;
import net.minecraft.world.gen.blockstateprovider.BlockStateProvider;
import net.minecraft.world.gen.blockplacer.DoublePlantBlockPlacer;
import net.minecraft.world.gen.blockstateprovider.SimpleBlockStateProvider;
import net.minecraft.client.audio.BackgroundMusicSelector;
import net.minecraft.world.gen.feature.BlockClusterFeatureConfig;
import java.util.function.Supplier;
import com.google.common.collect.ImmutableList;
import twilightforest.TFConfig;
import net.minecraft.world.gen.placement.ConfiguredPlacement;
import twilightforest.world.feature.config.TFTreeFeatureConfig;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.BaseTreeFeatureConfig;
import net.minecraft.world.gen.feature.ConfiguredFeature;

public final class ConfiguredFeatures
{
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> TWILIGHT_OAK_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> SWAMPY_OAK_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> CANOPY_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> FIREFLY_CANOPY_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> DEAD_CANOPY_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> MANGROVE_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> DARKWOOD_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> DARKWOOD_LANTERN_TREE_BASE;
    public static final ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>> TIME_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> TRANSFORM_TREE_BASE;
    public static final ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>> MINING_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> SORT_TREE_BASE;
    public static final ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>> DENSE_OAK_TREE_BASE;
    public static final ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>> HOLLOW_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> RAINBOW_OAK_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> LARGE_RAINBOW_OAK_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> BROWN_CANOPY_MUSHROOM_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> RED_CANOPY_MUSHROOM_TREE_BASE;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> MEGA_SPRUCE_NO_PODZOL_BASE;
    private static final ConfiguredPlacement<?> DEFAULT_TREE_PLACEMENT;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ?> SNOW_SPRUCE;
    public static final ConfiguredFeature<?, ?> SNOW_SPRUCE_SNOWY;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> OAK_DARK_FOREST;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> BIRCH_DARK_FOREST;
    public static final ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>> BUSH_DARK_FOREST;
    public static final ConfiguredFeature<?, ?> CANOPY_TREES;
    public static final ConfiguredFeature<?, ?> FIREFLY_CANOPY_TREES;
    public static final ConfiguredFeature<?, ?> FIREFLY_CANOPY_TREE_MIX;
    public static final ConfiguredFeature<?, ?> DEAD_CANOPY_TREES;
    public static final ConfiguredFeature<?, ?> RAINBOW_OAK_TREES;
    public static final ConfiguredFeature<?, ?> LARGE_RAINBOW_OAK_TREES;
    public static final ConfiguredFeature<?, ?> MANGROVE_TREES;
    public static final ConfiguredFeature<?, ?> DARKWOOD_TREES;
    public static final ConfiguredFeature<?, ?> DARKWOOD_LANTERN_TREES;
    public static final ConfiguredFeature<?, ?> TWILIGHT_OAK_TREES;
    public static final ConfiguredFeature<?, ?> SAVANNAH_OAK_TREES;
    public static final ConfiguredFeature<?, ?> SWAMPY_OAK_TREES;
    public static final ConfiguredFeature<?, ?> HOLLOW_OAK_TREES;
    public static final ConfiguredFeature<?, ?> MEGA_SPRUCE_TREES;
    public static final ConfiguredFeature<?, ?> OAK_DARK_FOREST_TREES;
    public static final ConfiguredFeature<?, ?> BIRCH_DARK_FOREST_TREES;
    public static final ConfiguredFeature<?, ?> BUSH_DARK_FOREST_TREES;
    public static final ConfiguredFeature<?, ?> WELL;
    public static final ConfiguredFeature<?, ?> DRUID_HUT;
    public static final ConfiguredFeature<?, ?> GRAVEYARD;
    public static final ConfiguredFeature<?, ?> BIG_MUSHGLOOM;
    public static final ConfiguredFeature<?, ?> FALLEN_LEAVES;
    public static final ConfiguredFeature<?, ?> FIDDLEHEAD;
    public static final ConfiguredFeature<?, ?> FIRE_JET;
    public static final ConfiguredFeature<?, ?> FOUNDATION;
    public static final ConfiguredFeature<?, ?> GROVE_RUINS;
    public static final ConfiguredFeature<?, ?> HOLLOW_LOG;
    public static final ConfiguredFeature<?, ?> HOLLOW_STUMP;
    public static final ConfiguredFeature<?, ?> HUGE_LILY_PAD;
    public static final ConfiguredFeature<?, ?> HUGE_WATER_LILY;
    public static final ConfiguredFeature<?, ?> LAMPPOST;
    public static final ConfiguredFeature<?, ?> MONOLITH;
    public static final ConfiguredFeature<?, ?> MUSHGLOOM_CLUSTER;
    public static final ConfiguredFeature<?, ?> MYCELIUM_BLOB;
    public static final ConfiguredFeature<?, ?> OUTSIDE_STALAGMITE;
    public static final ConfiguredFeature<?, ?> PLANT_ROOTS;
    public static final ConfiguredFeature<?, ?> PUMPKIN_LAMPPOST;
    public static final ConfiguredFeature<?, ?> SMALL_LOG;
    public static final ConfiguredFeature<?, ?> SMOKER;
    public static final ConfiguredFeature<?, ?> STONE_CIRCLE;
    public static final ConfiguredFeature<?, ?> THORNS;
    public static final ConfiguredFeature<?, ?> TORCH_BERRIES;
    public static final ConfiguredFeature<?, ?> TROLL_ROOTS;
    public static final ConfiguredFeature<?, ?> WEBS;
    public static final ConfiguredFeature<?, ?> WOOD_ROOTS_SPREAD;
    public static final ConfiguredFeature<?, ?> SNOW_UNDER_TREES;
    public static final ConfiguredFeature<?, ?> SMALL_GRANITE;
    public static final ConfiguredFeature<?, ?> SMALL_DIORITE;
    public static final ConfiguredFeature<?, ?> SMALL_ANDESITE;
    public static final ConfiguredFeature<?, ?> DARK_MUSHGLOOMS;
    public static final ConfiguredFeature<?, ?> DARK_PUMPKINS;
    public static final ConfiguredFeature<?, ?> DARK_GRASS;
    public static final ConfiguredFeature<?, ?> DARK_FERNS;
    public static final ConfiguredFeature<?, ?> DARK_MUSHROOMS;
    public static final ConfiguredFeature<?, ?> DARK_DEAD_BUSHES;
    public static final ConfiguredFeature<?, ?> VANILLA_TF_OAK;
    public static final ConfiguredFeature<?, ?> VANILLA_TF_BIRCH;
    public static final ConfiguredFeature<?, ?> VANILLA_TF_BIG_MUSH;
    public static final ConfiguredFeature<?, ?> CANOPY_MUSHROOMS_SPARSE;
    public static final ConfiguredFeature<?, ?> CANOPY_MUSHROOMS_DENSE;
    public static final ConfiguredFeature<?, ?> OAK_TREES_SPARSE;
    public static final ConfiguredFeature<?, ?> HOLLOW_TREE_PLACER;
    private static TFConfig.Common.Dimension.WorldGenWeights weights;
    private static final ImmutableList<Supplier<ConfiguredFeature<?, ?>>> COMMON_FEATURES;
    public static final ConfiguredFeature<?, ?> RANDOM_COMMON_FEATURE;
    public static final ConfiguredFeature<?, ?> RANDOM_FALLEN_FEATURE;
    public static final ConfiguredFeature<?, ?> RANDOM_WATER_FEATURE;
    public static final BlockClusterFeatureConfig SMALL_FLOWER_CONFIG;
    public static final ImmutableList<Supplier<ConfiguredFeature<?, ?>>> FOREST_GRASS;
    public static final ImmutableList<Supplier<ConfiguredFeature<?, ?>>> OTHER_GRASS;
    public static final ConfiguredFeature<?, ?> GRASS_PLACER;
    public static final ConfiguredFeature<?, ?> FOREST_GRASS_PLACER;
    public static final ConfiguredFeature<?, ?> FLOWER_PLACER;
    public static final BackgroundMusicSelector TFMUSICTYPE;
    
    static {
        TWILIGHT_OAK_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/twilight_oak"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.TWILIGHT_OAK));
        SWAMPY_OAK_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/swampy_oak"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.SWAMPY_OAK));
        CANOPY_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/canopy_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.CANOPY_TREE));
        FIREFLY_CANOPY_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/firefly_canopy_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.CANOPY_TREE_FIREFLY));
        DEAD_CANOPY_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/dead_canopy_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.CANOPY_TREE_DEAD));
        MANGROVE_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/mangrove_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.MANGROVE_TREE));
        DARKWOOD_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/darkwood_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.DARK_CANOPY_TREE.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.DARKWOOD_TREE));
        DARKWOOD_LANTERN_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/darkwood_lantern_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.DARK_CANOPY_TREE.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.DARKWOOD_LANTERN_TREE));
        TIME_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/time_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.TREE_OF_TIME.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.TIME_TREE));
        TRANSFORM_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/transform_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.TRANSFORM_TREE));
        MINING_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/mining_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.MINERS_TREE.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.MINING_TREE));
        SORT_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/sort_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.SORT_TREE));
        DENSE_OAK_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/dense_oak_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.CANOPY_OAK.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.DENSE_OAK));
        HOLLOW_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/hollow_tree"), (net.minecraft.world.gen.feature.ConfiguredFeature<TFTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.HOLLOW_TREE.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.HOLLOW_TREE));
        RAINBOW_OAK_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/rainbow_oak"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.RAINBOAK_TREE));
        LARGE_RAINBOW_OAK_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/large_rainbow_oak"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.LARGE_RAINBOAK_TREE));
        BROWN_CANOPY_MUSHROOM_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mushroom/base/brown_canopy_mushroom"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.MUSHROOM_BROWN));
        RED_CANOPY_MUSHROOM_TREE_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mushroom/base/red_canopy_mushroom"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)Feature.field_236291_c_.func_225566_b_((IFeatureConfig)TreeConfigurations.MUSHROOM_RED));
        MEGA_SPRUCE_NO_PODZOL_BASE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/mega_spruce_no_podzol"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.SNOW_TREE.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.BIG_SPRUCE));
        DEFAULT_TREE_PLACEMENT = (ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE_WITHHEIGHTMAP.func_242728_a();
        SNOW_SPRUCE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("snow_spruce"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ?>)((Feature)TFBiomeFeatures.SNOW_TREE.get()).func_225566_b_(Features.field_243866_bL.func_242767_c()));
        SNOW_SPRUCE_SNOWY = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("snow_spruce_snowy"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.SNOW_SPRUCE.func_227228_a_(Features.Placements.field_244001_l).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(0, 0.1f, 1))));
        OAK_DARK_FOREST = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/oak_dark_forest"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.DARK_CANOPY_TREE.get()).func_225566_b_(Features.field_243862_bH.func_242767_c()));
        BIRCH_DARK_FOREST = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/birch_dark_forest"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.DARK_CANOPY_TREE.get()).func_225566_b_(Features.field_243864_bJ.func_242767_c()));
        BUSH_DARK_FOREST = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/base/bush_dark_forest"), (net.minecraft.world.gen.feature.ConfiguredFeature<BaseTreeFeatureConfig, ? extends Feature<?>>)((Feature)TFBiomeFeatures.DARK_CANOPY_TREE.get()).func_225566_b_((IFeatureConfig)new BaseTreeFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.JUNGLE_LOG), (BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.OAK_LEAVES), (FoliagePlacer)new BushFoliagePlacer(FeatureSpread.func_242252_a(2), FeatureSpread.func_242252_a(1), 2), (AbstractTrunkPlacer)new StraightTrunkPlacer(1, 0, 0), (AbstractFeatureSizeType)new TwoLayerFeature(0, 0, 0)).func_225568_b_()));
        CANOPY_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/canopy_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.CANOPY_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        FIREFLY_CANOPY_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/firefly_canopy_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.FIREFLY_CANOPY_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        FIREFLY_CANOPY_TREE_MIX = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/firefly_canopy_tree_mix"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_204620_ao.func_225566_b_((IFeatureConfig)new SingleRandomFeature((List)ImmutableList.of(() -> ConfiguredFeatures.CANOPY_TREE_BASE, () -> ConfiguredFeatures.FIREFLY_CANOPY_TREE_BASE))).func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        DEAD_CANOPY_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/dead_canopy_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.DEAD_CANOPY_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        RAINBOW_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/rainbow_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.RAINBOW_OAK_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        LARGE_RAINBOW_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/large_rainbow_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.LARGE_RAINBOW_OAK_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        MANGROVE_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/mangrove_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.MANGROVE_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        DARKWOOD_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/darkwood_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)ConfiguredFeatures.DARKWOOD_TREE_BASE.func_227228_a_(Features.Placements.field_244001_l).func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_242731_b(2)).func_242732_c(2)).func_242728_a());
        DARKWOOD_LANTERN_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/darkwood_lantern_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)ConfiguredFeatures.DARKWOOD_LANTERN_TREE_BASE.func_227228_a_(Features.Placements.field_244001_l).func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_242731_b(4)).func_242732_c(2)).func_242728_a());
        TWILIGHT_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/twilight_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.TWILIGHT_OAK_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(3, 0.6f, 1))));
        SAVANNAH_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/savannah_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.TWILIGHT_OAK_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT));
        SWAMPY_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/swampy_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.SWAMPY_OAK_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(3, 0.6f, 1))));
        HOLLOW_OAK_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/hollow_oak_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.HOLLOW_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Features.Placements.field_244001_l));
        MEGA_SPRUCE_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/mega_spruce_no_podzol"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)ConfiguredFeatures.MEGA_SPRUCE_NO_PODZOL_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_242728_a()).func_242732_c(4));
        OAK_DARK_FOREST_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/oak_dark_forest_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.OAK_DARK_FOREST.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Features.Placements.field_244001_l).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(2, 0.6f, 1))).func_242728_a());
        BIRCH_DARK_FOREST_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/birch_dark_forest_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.BIRCH_DARK_FOREST.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Features.Placements.field_244001_l).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(2, 0.6f, 1))).func_242728_a());
        BUSH_DARK_FOREST_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/bush_dark_forest_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)ConfiguredFeatures.BUSH_DARK_FOREST.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227228_a_(Features.Placements.field_244001_l).func_227228_a_(Placement.field_242902_f.func_227446_a_((IPlacementConfig)new AtSurfaceWithExtraConfig(2, 0.6f, 1))).func_242728_a());
        WELL = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("well"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.WELL.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l));
        DRUID_HUT = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("druid_hut"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DRUID_HUT.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l));
        GRAVEYARD = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("graveyard"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.GRAVEYARD.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_242729_a(95));
        BIG_MUSHGLOOM = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("big_mushgloom"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.BIG_MUSHGLOOM.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        FALLEN_LEAVES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("fallen_leaves"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FALLEN_LEAVES.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        FIDDLEHEAD = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("fiddlehead"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_227248_z_.func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.FIDDLEHEAD), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227315_a_(16).func_227322_d_()));
        FIRE_JET = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("fire_jet"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FIRE_JET.get()).func_225566_b_((IFeatureConfig)new BlockStateFeatureConfig(BlockConstants.FIRE_JET)).func_227228_a_(Features.Placements.field_244001_l));
        FOUNDATION = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("foundation"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FOUNDATION.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        GROVE_RUINS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("grove_ruins"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.GROVE_RUINS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        HOLLOW_LOG = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("hollow_log"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FALLEN_HOLLOW_LOG.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        HOLLOW_STUMP = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("hollow_stump"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.HOLLOW_STUMP.get()).func_225566_b_((IFeatureConfig)TreeConfigurations.HOLLOW_TREE).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        HUGE_LILY_PAD = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("huge_lily_pad"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.HUGE_LILY_PAD.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        HUGE_WATER_LILY = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("huge_water_lily"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.HUGE_WATER_LILY.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        LAMPPOST = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("lamppost"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.LAMPPOSTS.get()).func_225566_b_((IFeatureConfig)new BlockStateFeatureConfig(BlockConstants.FIREFLY_JAR)).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_243996_g).func_242728_a());
        MONOLITH = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("monolith"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((Feature)TFBiomeFeatures.MONOLITH.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(1));
        MUSHGLOOM_CLUSTER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mushgloom_cluster"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_227248_z_.func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.MUSHGLOOM), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227315_a_(8).func_227322_d_()));
        MYCELIUM_BLOB = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mycelium_blob"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.MYCELIUM_BLOB.get()).func_225566_b_((IFeatureConfig)new SphereReplaceConfig(BlockConstants.MYCELIUM, FeatureSpread.func_242253_a(4, 2), 3, (List)ImmutableList.of((Object)BlockConstants.GRASS_BLOCK))).func_227228_a_(Features.Placements.field_244002_m).func_242728_a());
        OUTSIDE_STALAGMITE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("outside_stalagmite"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.OUTSIDE_STALAGMITE.get()).func_225566_b_((IFeatureConfig)new CaveStalactiteConfig(BlockConstants.STONE, 3.0f, 5, 10, false)).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        PLANT_ROOTS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("plant_roots"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((Feature)TFBiomeFeatures.PLANT_ROOTS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(4));
        PUMPKIN_LAMPPOST = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("pumpkin_lamppost"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.LAMPPOSTS.get()).func_225566_b_((IFeatureConfig)new BlockStateFeatureConfig(BlockConstants.JACK_O_LANTERN)).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_243996_g).func_242728_a());
        SMALL_LOG = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("small_log"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FALLEN_SMALL_LOG.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        SMOKER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("smoker"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.FIRE_JET.get()).func_225566_b_((IFeatureConfig)new BlockStateFeatureConfig(BlockConstants.SMOKER)).func_227228_a_(Features.Placements.field_244001_l));
        STONE_CIRCLE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("stone_circle"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((Feature)TFBiomeFeatures.STONE_CIRCLE.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(1));
        THORNS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("thorns"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)((Feature)TFBiomeFeatures.THORNS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_242733_d(95)).func_227228_a_(Features.Placements.field_244001_l).func_242731_b(50)).func_242732_c(85));
        TORCH_BERRIES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("torch_berries"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((Feature)TFBiomeFeatures.TORCH_BERRIES.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(4));
        TROLL_ROOTS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("troll_roots"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)((Feature)TFBiomeFeatures.TROLL_ROOTS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(4)).func_242732_c(8));
        WEBS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("webs"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((Feature)TFBiomeFeatures.WEBS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(60));
        WOOD_ROOTS_SPREAD = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("ore/wood_roots_spread"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)((Feature)TFBiomeFeatures.WOOD_ROOTS.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_242733_d(30)).func_242728_a()).func_242731_b(20));
        SNOW_UNDER_TREES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("snow_under_trees"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.SNOW_UNDER_TREES.get()).func_225566_b_((IFeatureConfig)IFeatureConfig.field_202429_e));
        SMALL_GRANITE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("small_granite"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)Feature.field_202290_aj.func_225566_b_((IFeatureConfig)new OreFeatureConfig(OreFeatureConfig.FillerBlockType.field_241882_a, Blocks.field_196650_c.func_176223_P(), 16)).func_242733_d(60)).func_242728_a()).func_242731_b(5));
        SMALL_DIORITE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("small_diorite"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)Feature.field_202290_aj.func_225566_b_((IFeatureConfig)new OreFeatureConfig(OreFeatureConfig.FillerBlockType.field_241882_a, Blocks.field_196654_e.func_176223_P(), 16)).func_242733_d(60)).func_242728_a()).func_242731_b(5));
        SMALL_ANDESITE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("small_andesite"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)Feature.field_202290_aj.func_225566_b_((IFeatureConfig)new OreFeatureConfig(OreFeatureConfig.FillerBlockType.field_241882_a, Blocks.field_196656_g.func_176223_P(), 16)).func_242733_d(60)).func_242728_a()).func_242731_b(5));
        DARK_MUSHGLOOMS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_mushglooms"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.MUSHGLOOM), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(64).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m).func_242729_a(10));
        DARK_PUMPKINS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_pumpkins"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.PUMPKIN), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(16).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m).func_242729_a(30));
        DARK_GRASS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_grass"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.GRASS), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(128).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m).func_242731_b(4));
        DARK_FERNS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_ferns"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.FERN), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(128).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m).func_242731_b(4));
        DARK_MUSHROOMS = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_mushrooms"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.BROWN_MUSHROOM), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(64).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m));
        DARK_DEAD_BUSHES = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("dark_dead_bushes"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((Feature)TFBiomeFeatures.DARK_FOREST_PLACER.get()).func_225566_b_((IFeatureConfig)new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.DEAD_BUSH), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227316_a_((Set)ImmutableSet.of((Object)BlockConstants.GRASS_BLOCK.func_177230_c())).func_227315_a_(32).func_227317_b_().func_227322_d_()).func_227228_a_(Features.Placements.field_244002_m).func_242729_a(15));
        VANILLA_TF_OAK = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/vanilla/vanilla_tf_oak"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_236291_c_.func_225566_b_(Features.field_243862_bH.func_242767_c()).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l));
        VANILLA_TF_BIRCH = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/vanilla/vanilla_tf_birch"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_236291_c_.func_225566_b_(Features.field_243864_bJ.func_242767_c()).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l));
        VANILLA_TF_BIG_MUSH = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/vanilla/vanilla_tf_big_mush"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_202293_am.func_225566_b_((IFeatureConfig)new TwoFeatureChoiceConfig(() -> Features.field_243861_bG, () -> Features.field_243860_bF)).func_227228_a_((ConfiguredPlacement)TwilightFeatures.CONFIGURED_PLACEMENT_NOTFSTRUCTURE).func_227228_a_(Features.Placements.field_244001_l));
        CANOPY_MUSHROOMS_SPARSE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mushroom/canopy_mushrooms_sparse"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.BROWN_CANOPY_MUSHROOM_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227227_a_(0.15f), (Object)ConfiguredFeatures.RED_CANOPY_MUSHROOM_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227227_a_(0.05f)), ConfiguredFeatures.CANOPY_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT))).func_227228_a_(Features.Placements.field_243996_g).func_242728_a()).func_242731_b(8));
        CANOPY_MUSHROOMS_DENSE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("mushroom/canopy_mushrooms_dense"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.BROWN_CANOPY_MUSHROOM_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227227_a_(0.675f), (Object)ConfiguredFeatures.RED_CANOPY_MUSHROOM_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT).func_227227_a_(0.225f)), ConfiguredFeatures.CANOPY_TREE_BASE.func_227228_a_((ConfiguredPlacement)ConfiguredFeatures.DEFAULT_TREE_PLACEMENT))).func_227228_a_(Features.Placements.field_243996_g).func_242728_a()).func_242731_b(8));
        OAK_TREES_SPARSE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/oak_trees_sparse"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.HOLLOW_OAK_TREES.func_227227_a_(0.05f), (Object)ConfiguredFeatures.SAVANNAH_OAK_TREES.func_227227_a_(0.35f)), Feature.field_227245_q_.func_225566_b_((IFeatureConfig)NoFeatureConfig.field_236559_b_))).func_227228_a_(Features.Placements.field_243996_g).func_242728_a()).func_242731_b(1));
        HOLLOW_TREE_PLACER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("tree/hollow_placer"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.HOLLOW_OAK_TREES.func_227227_a_(0.01f), (Object)ConfiguredFeatures.HOLLOW_OAK_TREES.func_227227_a_(0.01f)), Feature.field_227245_q_.func_225566_b_((IFeatureConfig)NoFeatureConfig.field_236559_b_))).func_227228_a_(Features.Placements.field_244001_l).func_242731_b(1));
        ConfiguredFeatures.weights = TFConfig.COMMON_CONFIG.DIMENSION.worldGenWeights;
        COMMON_FEATURES = ImmutableList.of(() -> ConfiguredFeatures.DRUID_HUT.func_242729_a((int)ConfiguredFeatures.weights.druidHutWeight.get() / 4), () -> ConfiguredFeatures.WELL.func_242729_a((int)ConfiguredFeatures.weights.wellWeight.get() / 2), () -> ConfiguredFeatures.GROVE_RUINS.func_242729_a((int)ConfiguredFeatures.weights.groveRuinsWeight.get() / 2), () -> ConfiguredFeatures.MONOLITH.func_242729_a((int)ConfiguredFeatures.weights.monolithWeight.get() / 2), () -> ConfiguredFeatures.OUTSIDE_STALAGMITE.func_242729_a((int)ConfiguredFeatures.weights.stalagmiteWeight.get() / 2), () -> ConfiguredFeatures.STONE_CIRCLE.func_242729_a((int)ConfiguredFeatures.weights.stoneCircleWeight.get() / 2), () -> ConfiguredFeatures.FOUNDATION.func_242729_a((int)ConfiguredFeatures.weights.foundationWeight.get() / 2), () -> ConfiguredFeatures.HOLLOW_LOG.func_242729_a((int)ConfiguredFeatures.weights.fallenHollowLogWeight.get() / 2), () -> ConfiguredFeatures.HOLLOW_STUMP.func_242729_a((int)ConfiguredFeatures.weights.hollowStumpWeight.get() / 2), () -> ConfiguredFeatures.SMALL_LOG.func_242729_a((int)ConfiguredFeatures.weights.fallenSmallLogWeight.get() / 2));
        RANDOM_COMMON_FEATURE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("random_common"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)Feature.field_204620_ao.func_225566_b_((IFeatureConfig)new SingleRandomFeature((List)ConfiguredFeatures.COMMON_FEATURES)).func_227228_a_(Features.Placements.field_244001_l).func_242728_a());
        RANDOM_FALLEN_FEATURE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("random_fallen"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.FOUNDATION.func_227227_a_(0.05f), (Object)ConfiguredFeatures.HOLLOW_LOG.func_227227_a_(0.05f), (Object)ConfiguredFeatures.HOLLOW_STUMP.func_227227_a_(0.05f), (Object)ConfiguredFeatures.SMALL_LOG.func_227227_a_(0.1f)), Feature.field_227245_q_.func_225566_b_((IFeatureConfig)NoFeatureConfig.field_236559_b_))).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(1));
        RANDOM_WATER_FEATURE = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("random_water"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_202292_al.func_225566_b_((IFeatureConfig)new MultipleRandomFeatureConfig((List)ImmutableList.of((Object)ConfiguredFeatures.HUGE_LILY_PAD.func_227227_a_(0.5f), (Object)ConfiguredFeatures.HUGE_WATER_LILY.func_227227_a_(0.2f)), Features.field_243810_aI)).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(5));
        SMALL_FLOWER_CONFIG = new BlockClusterFeatureConfig.Builder((BlockStateProvider)new WeightedBlockStateProvider().func_227407_a_(BlockConstants.POPPY, 1).func_227407_a_(BlockConstants.DANDELION, 1).func_227407_a_(BlockConstants.RED_TULIP, 1).func_227407_a_(BlockConstants.ORANGE_TULIP, 1).func_227407_a_(BlockConstants.PINK_TULIP, 1).func_227407_a_(BlockConstants.WHITE_TULIP, 1).func_227407_a_(BlockConstants.CORNFLOWER, 1).func_227407_a_(BlockConstants.LILY, 1).func_227407_a_(BlockConstants.ORCHID, 1).func_227407_a_(BlockConstants.ALLIUM, 1).func_227407_a_(BlockConstants.AZURE, 1).func_227407_a_(BlockConstants.OXEYE, 1), (BlockPlacer)SimpleBlockPlacer.field_236447_c_).func_227315_a_(128).func_227322_d_();
        FOREST_GRASS = ImmutableList.of(() -> {
            final Feature field_227248_z_ = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.MAYAPPLE), (BlockPlacer)SimpleBlockPlacer.field_236447_c_);
            final BlockClusterFeatureConfig.Builder builder;
            return field_227248_z_.func_225566_b_((IFeatureConfig)builder.func_227315_a_(4).func_227322_d_());
        }, () -> {
            final Feature field_227248_z_2 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.GRASS), (BlockPlacer)SimpleBlockPlacer.field_236447_c_);
            final BlockClusterFeatureConfig.Builder builder2;
            return field_227248_z_2.func_225566_b_((IFeatureConfig)builder2.func_227315_a_(64).func_227322_d_());
        }, () -> {
            final Feature field_227248_z_3 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.TALL_GRASS), (BlockPlacer)DoublePlantBlockPlacer.field_236444_c_);
            final BlockClusterFeatureConfig.Builder builder3;
            return field_227248_z_3.func_225566_b_((IFeatureConfig)builder3.func_227315_a_(32).func_227317_b_().func_227322_d_());
        }, () -> {
            final Feature field_227248_z_4 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.FERN), (BlockPlacer)SimpleBlockPlacer.field_236447_c_);
            final BlockClusterFeatureConfig.Builder builder4;
            return field_227248_z_4.func_225566_b_((IFeatureConfig)builder4.func_227315_a_(32).func_227322_d_());
        }, () -> {
            final Feature field_227248_z_5 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.TALL_FERN), (BlockPlacer)DoublePlantBlockPlacer.field_236444_c_);
            final BlockClusterFeatureConfig.Builder builder5;
            return field_227248_z_5.func_225566_b_((IFeatureConfig)builder5.func_227315_a_(16).func_227317_b_().func_227322_d_());
        });
        OTHER_GRASS = ImmutableList.of(() -> {
            final Feature field_227248_z_6 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.GRASS), (BlockPlacer)SimpleBlockPlacer.field_236447_c_);
            final BlockClusterFeatureConfig.Builder builder6;
            return field_227248_z_6.func_225566_b_((IFeatureConfig)builder6.func_227315_a_(64).func_227322_d_());
        }, () -> {
            final Feature field_227248_z_7 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.TALL_GRASS), (BlockPlacer)DoublePlantBlockPlacer.field_236444_c_);
            final BlockClusterFeatureConfig.Builder builder7;
            return field_227248_z_7.func_225566_b_((IFeatureConfig)builder7.func_227315_a_(32).func_227317_b_().func_227322_d_());
        }, () -> {
            final Feature field_227248_z_8 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.FERN), (BlockPlacer)SimpleBlockPlacer.field_236447_c_);
            final BlockClusterFeatureConfig.Builder builder8;
            return field_227248_z_8.func_225566_b_((IFeatureConfig)builder8.func_227315_a_(32).func_227322_d_());
        }, () -> {
            final Feature field_227248_z_9 = Feature.field_227248_z_;
            new BlockClusterFeatureConfig.Builder((BlockStateProvider)new SimpleBlockStateProvider(BlockConstants.TALL_FERN), (BlockPlacer)DoublePlantBlockPlacer.field_236444_c_);
            final BlockClusterFeatureConfig.Builder builder9;
            return field_227248_z_9.func_225566_b_((IFeatureConfig)builder9.func_227315_a_(16).func_227317_b_().func_227322_d_());
        });
        GRASS_PLACER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("grass_placer"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)((ConfiguredFeature)Feature.field_204620_ao.func_225566_b_((IFeatureConfig)new SingleRandomFeature((List)ConfiguredFeatures.OTHER_GRASS)).func_242730_a(FeatureSpread.func_242253_a(-1, 4))).func_227228_a_(Features.Placements.field_244000_k).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(30)).func_242729_a(5));
        FOREST_GRASS_PLACER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("forest_grass_placer"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)((ConfiguredFeature)((ConfiguredFeature)Feature.field_204620_ao.func_225566_b_((IFeatureConfig)new SingleRandomFeature((List)ConfiguredFeatures.FOREST_GRASS)).func_242730_a(FeatureSpread.func_242253_a(-1, 4))).func_227228_a_(Features.Placements.field_244000_k).func_227228_a_(Features.Placements.field_244001_l).func_242728_a()).func_242731_b(30)).func_242729_a(5));
        FLOWER_PLACER = TwilightFeatures.registerWorldFeature(TwilightForestMod.prefix("flower_placer"), (net.minecraft.world.gen.feature.ConfiguredFeature<?, ?>)((ConfiguredFeature)Feature.field_227247_y_.func_225566_b_((IFeatureConfig)ConfiguredFeatures.SMALL_FLOWER_CONFIG).func_227228_a_(Features.Placements.field_244000_k).func_227228_a_(Features.Placements.field_244001_l).func_242731_b(25)).func_242729_a(15));
        TFMUSICTYPE = new BackgroundMusicSelector(TFSounds.MUSIC, 1200, 12000, true);
    }
}
