// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest;

import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class TFItems
{
    public static su ARMOR_NAGA;
    public static su ARMOR_IRONWOOD;
    public static su ARMOR_FIERY;
    public static su ARMOR_STEELEAF;
    public static ul TOOL_IRONWOOD;
    public static ul TOOL_FIERY;
    public static ul TOOL_STEELEAF;
    public static uk nagaScale;
    public static uk plateNaga;
    public static uk legsNaga;
    public static uk scepterTwilight;
    public static uk scepterLifeDrain;
    public static uk scepterZombie;
    public static uk wandPacification;
    public static uk oreMeter;
    public static uk magicMap;
    public static uk mazeMap;
    public static uk oreMap;
    public static uk feather;
    public static uk magicMapFocus;
    public static uk mazeMapFocus;
    public static uk liveRoot;
    public static uk ironwoodRaw;
    public static uk ironwoodIngot;
    public static uk ironwoodHelm;
    public static uk ironwoodPlate;
    public static uk ironwoodLegs;
    public static uk ironwoodBoots;
    public static uk ironwoodSword;
    public static uk ironwoodShovel;
    public static uk ironwoodPick;
    public static uk ironwoodAxe;
    public static uk ironwoodHoe;
    public static uk torchberries;
    public static uk spawnEgg;
    public static uk venisonRaw;
    public static uk venisonCooked;
    public static uk hydraChop;
    public static uk fieryBlood;
    public static uk hydraTrophy;
    public static uk fieryIngot;
    public static uk fieryHelm;
    public static uk fieryPlate;
    public static uk fieryLegs;
    public static uk fieryBoots;
    public static uk fierySword;
    public static uk fieryPick;
    public static uk steeleafIngot;
    public static uk steeleafHelm;
    public static uk steeleafPlate;
    public static uk steeleafLegs;
    public static uk steeleafBoots;
    public static uk steeleafSword;
    public static uk steeleafShovel;
    public static uk steeleafPick;
    public static uk steeleafAxe;
    public static uk steeleafHoe;
    public static uk minotaurAxe;
    public static uk mazebreakerPick;
    public static uk transformPowder;
    public static uk meefRaw;
    public static uk meefSteak;
    public static uk meefStroganoff;
    public static uk mazeWafer;
    public static uk emptyMagicMap;
    public static uk emptyMazeMap;
    public static uk emptyOreMap;
    public static uk oreMagnet;
    public static uk crumbleHorn;
    public static uk peacockFan;
    public static uk moonwormQueen;
    public static uk charmOfLife1;
    public static uk charmOfLife2;
    public static uk charmOfKeeping1;
    public static uk charmOfKeeping2;
    public static uk charmOfKeeping3;
    
    public TFItems() {
        final int nagaScaleRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/nagascale_");
        final int ironwoodRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/ironwood_");
        final int fieryRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/fiery_");
        final int steeleafRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/steeleaf_");
        TFItems.nagaScale = new ItemTF(TwilightForestMod.idItemNagaScale).c(0).b("nagaScale");
        TFItems.plateNaga = new ItemTFNagaArmor(TwilightForestMod.idItemPlateNaga, TFItems.ARMOR_NAGA, nagaScaleRenderID, 1).c(16).b("plateNaga").d(1);
        TFItems.legsNaga = new ItemTFNagaArmor(TwilightForestMod.idItemLegsNaga, TFItems.ARMOR_NAGA, nagaScaleRenderID, 2).c(32).b("legsNaga").d(1);
        TFItems.scepterTwilight = new ItemTFTwilightWand(TwilightForestMod.idItemScepterTwilight).c(3).b("scepterTwilight").d(1).o();
        TFItems.scepterLifeDrain = new ItemTFLifeDrainWand(TwilightForestMod.idItemScepterLifeDrain).c(4).b("scepterLifeDrain").d(1).o();
        TFItems.scepterZombie = new ItemTFZombieWand(TwilightForestMod.idItemScepterZombie).c(5).b("scepterZombie").d(1).o();
        TFItems.oreMeter = new ItemTFOreMeter(TwilightForestMod.idItemOreMeter).c(7).b("oreMeter").d(1);
        TFItems.magicMap = new ItemTFMagicMap(TwilightForestMod.idItemMagicMap).c(8).b("magicMap").d(1);
        TFItems.mazeMap = new ItemTFMazeMap(TwilightForestMod.idItemMazeMap, false).c(10).b("mazeMap").d(1);
        TFItems.oreMap = new ItemTFMazeMap(TwilightForestMod.idItemOreMap, true).c(11).b("oreMap").d(1);
        TFItems.feather = new ItemTF(TwilightForestMod.idItemFeather).c(12).b("tfFeather");
        TFItems.magicMapFocus = new ItemTF(TwilightForestMod.idItemMagicMapFocus).c(13).b("magicMapFocus");
        TFItems.mazeMapFocus = new ItemTF(TwilightForestMod.idItemMazeMapFocus).c(14).b("mazeMapFocus");
        TFItems.liveRoot = new ItemTF(TwilightForestMod.idItemLiveRoot).c(1).b("liveRoot");
        TFItems.ironwoodRaw = new ItemTF(TwilightForestMod.idItemIronwoodRaw).c(17).b("ironwoodRaw");
        TFItems.ironwoodIngot = new ItemTF(TwilightForestMod.idItemIronwoodIngot).c(33).b("ironwoodIngot");
        TFItems.ironwoodHelm = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodHelm, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 0).c(49).b("ironwoodHelm").d(1);
        TFItems.ironwoodPlate = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodPlate, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 1).c(65).b("ironwoodPlate").d(1);
        TFItems.ironwoodLegs = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodLegs, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 2).c(81).b("ironwoodLegs").d(1);
        TFItems.ironwoodBoots = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodBoots, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 3).c(97).b("ironwoodBoots").d(1);
        TFItems.ironwoodSword = new ItemTFIronwoodSword(TwilightForestMod.idItemIronwoodSword, TFItems.TOOL_IRONWOOD).c(113).b("ironwoodSword").d(1);
        TFItems.ironwoodShovel = new ItemTFIronwoodShovel(TwilightForestMod.idItemIronwoodShovel, TFItems.TOOL_IRONWOOD).c(129).b("ironwoodShovel").d(1);
        TFItems.ironwoodPick = new ItemTFIronwoodPick(TwilightForestMod.idItemIronwoodPick, TFItems.TOOL_IRONWOOD).c(145).b("ironwoodPick").d(1);
        TFItems.ironwoodAxe = new ItemTFIronwoodAxe(TwilightForestMod.idItemIronwoodAxe, TFItems.TOOL_IRONWOOD).c(161).b("ironwoodAxe").d(1);
        TFItems.ironwoodHoe = new ItemTFIronwoodHoe(TwilightForestMod.idItemIronwoodHoe, TFItems.TOOL_IRONWOOD).c(177).b("ironwoodHoe").d(1);
        TFItems.torchberries = new ItemTF(TwilightForestMod.idItemTorchberries).c(19).b("torchberries");
        TFItems.spawnEgg = new ItemTFSpawnEgg(TwilightForestMod.idItemSpawnEgg).b(9, 9).b("tfspawnegg");
        TFItems.venisonRaw = new uf(TwilightForestMod.idItemVenisonRaw, 3, 0.3f, true).b(9, 6).b("venisonRaw");
        TFItems.venisonCooked = new uf(TwilightForestMod.idItemVenisonCooked, 8, 0.8f, true).b(10, 6).b("venisonCooked");
        TFItems.hydraChop = new uf(TwilightForestMod.idItemHydraChops, 18, 2.0f, true).a(ll.l.H, 5, 0, 1.0f).b(8, 5).b("hydraChop");
        TFItems.fieryBlood = new ItemTF(TwilightForestMod.idItemFieryBlood).makeRare().c(21).b("fieryBlood");
        TFItems.hydraTrophy = new ItemTF(TwilightForestMod.idItemHydraTrophy).makeRare().c(22).b("hydraTrophy");
        TFItems.fieryIngot = new ItemTF(TwilightForestMod.idItemFieryIngot).makeRare().b(4, 2).b("fieryIngot");
        TFItems.fieryHelm = new ItemTFFieryArmor(TwilightForestMod.idItemFieryHelm, TFItems.ARMOR_FIERY, fieryRenderID, 0).b(4, 3).b("fieryHelm").d(1);
        TFItems.fieryPlate = new ItemTFFieryArmor(TwilightForestMod.idItemFieryPlate, TFItems.ARMOR_FIERY, fieryRenderID, 1).b(4, 4).b("fieryPlate").d(1);
        TFItems.fieryLegs = new ItemTFFieryArmor(TwilightForestMod.idItemFieryLegs, TFItems.ARMOR_FIERY, fieryRenderID, 2).b(4, 5).b("fieryLegs").d(1);
        TFItems.fieryBoots = new ItemTFFieryArmor(TwilightForestMod.idItemFieryBoots, TFItems.ARMOR_FIERY, fieryRenderID, 3).b(4, 6).b("fieryBoots").d(1);
        TFItems.fierySword = new ItemTFFierySword(TwilightForestMod.idItemFierySword, TFItems.TOOL_FIERY).b(4, 7).b("fierySword").d(1);
        TFItems.fieryPick = new ItemTFFieryPick(TwilightForestMod.idItemFieryPick, TFItems.TOOL_FIERY).b(4, 9).b("fieryPick").d(1);
        TFItems.steeleafIngot = new ItemTF(TwilightForestMod.idItemSteeleafIngot).b(2, 2).b("steeleafIngot");
        TFItems.steeleafHelm = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafHelm, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 0).b(2, 3).b("steeleafHelm").d(1);
        TFItems.steeleafPlate = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafPlate, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 1).b(2, 4).b("steeleafPlate").d(1);
        TFItems.steeleafLegs = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafLegs, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 2).b(2, 5).b("steeleafLegs").d(1);
        TFItems.steeleafBoots = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafBoots, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 3).b(2, 6).b("steeleafBoots").d(1);
        TFItems.steeleafSword = new ItemTFSteeleafSword(TwilightForestMod.idItemSteeleafSword, TFItems.TOOL_STEELEAF).b(2, 7).b("steeleafSword").d(1);
        TFItems.steeleafShovel = new ItemTFSteeleafShovel(TwilightForestMod.idItemSteeleafShovel, TFItems.TOOL_STEELEAF).b(2, 8).b("steeleafShovel").d(1);
        TFItems.steeleafPick = new ItemTFSteeleafPick(TwilightForestMod.idItemSteeleafPick, TFItems.TOOL_STEELEAF).b(2, 9).b("steeleafPick").d(1);
        TFItems.steeleafAxe = new ItemTFSteeleafAxe(TwilightForestMod.idItemSteeleafAxe, TFItems.TOOL_STEELEAF).b(2, 10).b("steeleafAxe").d(1);
        TFItems.steeleafHoe = new ItemTFSteeleafHoe(TwilightForestMod.idItemSteeleafHoe, TFItems.TOOL_STEELEAF).b(2, 11).b("steeleafHoe").d(1);
        TFItems.minotaurAxe = new ItemTFMinotaurAxe(TwilightForestMod.idItemMinotaurAxe, ul.d).b(0, 10).b("minotaurAxe").d(1);
        TFItems.mazebreakerPick = new ItemTFMazebreakerPick(TwilightForestMod.idItemMazebreakerPick, ul.d).b(0, 9).b("mazebreakerPick").d(1);
        TFItems.transformPowder = new ItemTFTransformPowder(TwilightForestMod.idItemTransformPowder).makeRare().b(7, 1).b("transformPowder");
        TFItems.meefRaw = new uf(TwilightForestMod.idItemMeefRaw, 2, 0.3f, true).b(9, 6).b("meefRaw");
        TFItems.meefSteak = new uf(TwilightForestMod.idItemMeefSteak, 6, 0.6f, true).b(10, 6).b("meefSteak");
        TFItems.meefStroganoff = new ta(TwilightForestMod.idItemMeefStroganoff, 8).b(8, 4).b("meefStroganoff");
        TFItems.mazeWafer = new uf(TwilightForestMod.idItemMazeWafer, 4, 0.6f, true).b(12, 5).b("mazeWafer");
        TFItems.emptyMagicMap = new ItemTFEmptyMagicMap(TwilightForestMod.idItemEmptyMagicMap).b(8, 1).b("emptyMagicMap");
        TFItems.emptyMazeMap = new ItemTFEmptyMazeMap(TwilightForestMod.idItemEmptyMazeMap, false).b(10, 1).b("emptyMazeMap");
        TFItems.emptyOreMap = new ItemTFEmptyMazeMap(TwilightForestMod.idItemEmptyOreMap, true).b(11, 1).b("emptyOreMap");
        TFItems.oreMagnet = new ItemTFOreMagnet(TwilightForestMod.idItemOreMagnet).b(13, 2).b("oreMagnet");
        TFItems.crumbleHorn = new ItemTFCrumbleHorn(TwilightForestMod.idItemCrumbleHorn).b(12, 1).b("crumbleHorn");
        TFItems.peacockFan = new ItemTFPeacockFan(TwilightForestMod.idItemPeacockFan).b(13, 1).b("peacockFan");
        TFItems.moonwormQueen = new ItemTFMoonwormQueen(TwilightForestMod.idItemMoonwormQueen).b(14, 1).b("moonwormQueen");
        TFItems.charmOfLife1 = new ItemTFCharm(TwilightForestMod.idItemCharmOfLife1).b(8, 2).b("charmOfLife1");
        TFItems.charmOfLife2 = new ItemTFCharm(TwilightForestMod.idItemCharmOfLife2).b(9, 2).b("charmOfLife2");
        TFItems.charmOfKeeping1 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping1).b(10, 2).b("charmOfKeeping1");
        TFItems.charmOfKeeping2 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping2).b(11, 2).b("charmOfKeeping2");
        TFItems.charmOfKeeping3 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping3).b(12, 2).b("charmOfKeeping3");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.nagaScale, "en_US", "Naga Scale");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.plateNaga, "en_US", "Naga Scale Tunic");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.legsNaga, "en_US", "Naga Scale Leggings");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.scepterTwilight, "en_US", "Scepter of Twilight");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.scepterLifeDrain, "en_US", "Scepter of Life Draining");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.scepterZombie, "en_US", "Zombie Scepter");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.oreMeter, "en_US", "Ore Meter [WIP]");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.magicMap, "en_US", "Magic Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.mazeMap, "en_US", "Maze Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.oreMap, "en_US", "Maze/Ore Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.feather, "en_US", "Raven's Feather");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.magicMapFocus, "en_US", "Magic Map Focus");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.mazeMapFocus, "en_US", "Maze Map Focus");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.liveRoot, "en_US", "Liveroot");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodRaw, "en_US", "Raw Ironwood Materials");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodIngot, "en_US", "Ironwood Ingot");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodHelm, "en_US", "Ironwood Helm");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodPlate, "en_US", "Ironwood Plate");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodLegs, "en_US", "Ironwood Legs");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodBoots, "en_US", "Ironwood Boots");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodSword, "en_US", "Ironwood Sword");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodShovel, "en_US", "Ironwood Shovel");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodPick, "en_US", "Ironwood Pick");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodAxe, "en_US", "Ironwood Axe");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.ironwoodHoe, "en_US", "Ironwood Hoe");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.torchberries, "en_US", "Torchberries");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.spawnEgg, "en_US", "Spawn");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.venisonRaw, "en_US", "Raw Venison");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.venisonCooked, "en_US", "Venison Steak");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.hydraChop, "en_US", "Hydra Chop");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryBlood, "en_US", "Fiery Blood");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.hydraTrophy, "en_US", "Hydra Trophy [NYI]");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryIngot, "en_US", "Fiery Ingot");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryHelm, "en_US", "Fiery Helm");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryPlate, "en_US", "Fiery Plate");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryLegs, "en_US", "Fiery Legs");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryBoots, "en_US", "Fiery Boots");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fierySword, "en_US", "Fiery Sword");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.fieryPick, "en_US", "Fiery Pick");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafIngot, "en_US", "Steeleaf");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafHelm, "en_US", "Steeleaf Helm");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafPlate, "en_US", "Steeleaf Plate");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafLegs, "en_US", "Steeleaf Legs");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafBoots, "en_US", "Steeleaf Boots");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafSword, "en_US", "Steeleaf Sword");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafShovel, "en_US", "Steeleaf Shovel");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafPick, "en_US", "Steeleaf Pick");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafAxe, "en_US", "Steeleaf Axe");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.steeleafHoe, "en_US", "Steeleaf Hoe");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.minotaurAxe, "en_US", "Minotaur Axe");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.mazebreakerPick, "en_US", "Mazebreaker");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.transformPowder, "en_US", "Transformation Powder");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.meefRaw, "en_US", "Raw Meef");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.meefSteak, "en_US", "Meef Steak");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.meefStroganoff, "en_US", "Meef Stroganoff");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.mazeWafer, "en_US", "Maze Wafer");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.emptyMagicMap, "en_US", "Blank Magic Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.emptyMazeMap, "en_US", "Blank Maze Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.emptyOreMap, "en_US", "Blank Maze/Ore Map");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.oreMagnet, "en_US", "Ore Magnet");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.crumbleHorn, "en_US", "Crumble Horn");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.peacockFan, "en_US", "Peacock Feather Fan");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.moonwormQueen, "en_US", "Moonworm Queen");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.charmOfLife1, "en_US", "Charm of Life I");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.charmOfLife2, "en_US", "Charm of Life II");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.charmOfKeeping1, "en_US", "Charm of Keeping I");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.charmOfKeeping2, "en_US", "Charm of Keeping II");
        LanguageRegistry.instance().addNameForObject((Object)TFItems.charmOfKeeping3, "en_US", "Charm of Keeping III");
        LanguageRegistry.instance().addStringLocalization("enchantment.tfFireReact", "en_US", "Fiery Aura");
    }
    
    static {
        TFItems.ARMOR_NAGA = EnumHelper.addArmorMaterial("NAGA_SCALE", 21, new int[] { 2, 7, 6, 3 }, 15);
        TFItems.ARMOR_IRONWOOD = EnumHelper.addArmorMaterial("IRONWOOD", 20, new int[] { 2, 7, 5, 2 }, 15);
        TFItems.ARMOR_FIERY = EnumHelper.addArmorMaterial("FIERY", 25, new int[] { 4, 9, 7, 4 }, 10);
        TFItems.ARMOR_STEELEAF = EnumHelper.addArmorMaterial("STEELEAF", 10, new int[] { 3, 8, 6, 3 }, 9);
        TFItems.TOOL_IRONWOOD = EnumHelper.addToolMaterial("IRONWOOD", 2, 512, 6.5f, 2, 25);
        TFItems.TOOL_FIERY = EnumHelper.addToolMaterial("FIERY", 4, 1024, 9.0f, 4, 10);
        TFItems.TOOL_STEELEAF = EnumHelper.addToolMaterial("STEELEAF", 3, 131, 8.0f, 3, 9);
    }
}
