// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest;

import net.minecraft.sounds.SoundEvents;
import twilightforest.entity.TFEntities;
import net.minecraft.world.entity.animal.Parrot;
import net.minecraftforge.registries.IForgeRegistryEntry;
import net.minecraftforge.event.RegistryEvent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;

public final class TFSounds
{
    public static final SoundEvent ACID_RAIN_BURNS;
    public static final SoundEvent ALPHAYETI_ALERT;
    public static final SoundEvent ALPHAYETI_DEATH;
    public static final SoundEvent ALPHAYETI_GRAB;
    public static final SoundEvent ALPHAYETI_GROWL;
    public static final SoundEvent ALPHAYETI_HURT;
    public static final SoundEvent ALPHAYETI_ICE;
    public static final SoundEvent ALPHAYETI_PANT;
    public static final SoundEvent ALPHAYETI_ROAR;
    public static final SoundEvent ALPHAYETI_THROW;
    public static final SoundEvent BIGHORN_AMBIENT;
    public static final SoundEvent BIGHORN_DEATH;
    public static final SoundEvent BIGHORN_HURT;
    public static final SoundEvent BIGHORN_STEP;
    public static final SoundEvent BLOCKCHAIN_AMBIENT;
    public static final SoundEvent BLOCKCHAIN_COLLIDE;
    public static final SoundEvent BLOCKCHAIN_DEATH;
    public static final SoundEvent BLOCKCHAIN_FIRED;
    public static final SoundEvent BLOCKCHAIN_HIT;
    public static final SoundEvent BLOCKCHAIN_HURT;
    public static final SoundEvent BLOCK_ANNIHILATED;
    public static final SoundEvent BOAR_AMBIENT;
    public static final SoundEvent BOAR_DEATH;
    public static final SoundEvent BOAR_HURT;
    public static final SoundEvent BOAR_STEP;
    public static final SoundEvent BRITTLE_FLASK_BREAK;
    public static final SoundEvent BRITTLE_FLASK_CRACK;
    public static final SoundEvent BROODLING_AMBIENT;
    public static final SoundEvent BROODLING_DEATH;
    public static final SoundEvent BROODLING_HURT;
    public static final SoundEvent BROODLING_STEP;
    public static final SoundEvent BUILDER_OFF;
    public static final SoundEvent BUILDER_ON;
    public static final SoundEvent BUILDER_REPLACE;
    public static final SoundEvent BUILDER_CREATE;
    public static final SoundEvent BUG_SQUISH;
    public static final SoundEvent CARMINITE_GOLEM_ATTACK;
    public static final SoundEvent CARMINITE_GOLEM_DEATH;
    public static final SoundEvent CARMINITE_GOLEM_HURT;
    public static final SoundEvent CARMINITE_GOLEM_STEP;
    public static final SoundEvent CASKET_OPEN;
    public static final SoundEvent CASKET_CLOSE;
    public static final SoundEvent CASKET_LOCKED;
    public static final SoundEvent CASKET_REPAIR;
    public static final SoundEvent CHARM_KEEP;
    public static final SoundEvent CHARM_LIFE;
    public static final SoundEvent CICADA;
    public static final SoundEvent CICADA_FLYING;
    public static final SoundEvent DEER_DEATH;
    public static final SoundEvent DEER_HURT;
    public static final SoundEvent DEER_AMBIENT;
    public static final SoundEvent DWARF_DEATH;
    public static final SoundEvent DWARF_HURT;
    public static final SoundEvent DWARF_AMBIENT;
    public static final SoundEvent DOOR_ACTIVATED;
    public static final SoundEvent DOOR_REAPPEAR;
    public static final SoundEvent DOOR_VANISH;
    public static final SoundEvent FAN_WOOSH;
    public static final SoundEvent FIRE_BEETLE_DEATH;
    public static final SoundEvent FIRE_BEETLE_HURT;
    public static final SoundEvent FIRE_BEETLE_SHOOT;
    public static final SoundEvent FIRE_BEETLE_STEP;
    public static final SoundEvent FLASK_FILL;
    public static final SoundEvent GHASTGUARD_AMBIENT;
    public static final SoundEvent GHASTGUARD_DEATH;
    public static final SoundEvent GHASTGUARD_HURT;
    public static final SoundEvent GHASTGUARD_SHOOT;
    public static final SoundEvent GHASTGUARD_WARN;
    public static final SoundEvent GHASTLING_AMBIENT;
    public static final SoundEvent GHASTLING_DEATH;
    public static final SoundEvent GHASTLING_HURT;
    public static final SoundEvent GHASTLING_SHOOT;
    public static final SoundEvent GHASTLING_WARN;
    public static final SoundEvent GHAST_TRAP_ACTIVE;
    public static final SoundEvent GHAST_TRAP_AMBIENT;
    public static final SoundEvent GHAST_TRAP_ON;
    public static final SoundEvent GHAST_TRAP_SPINDOWN;
    public static final SoundEvent GHAST_TRAP_WARMUP;
    public static final SoundEvent GLASS_SWORD_BREAK;
    public static final SoundEvent GOBLIN_KNIGHT_AMBIENT;
    public static final SoundEvent GOBLIN_KNIGHT_DEATH;
    public static final SoundEvent GOBLIN_KNIGHT_HURT;
    public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_AMBIENT;
    public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_DEATH;
    public static final SoundEvent GOBLIN_KNIGHT_MUFFLED_HURT;
    public static final SoundEvent HEDGE_SPIDER_AMBIENT;
    public static final SoundEvent HEDGE_SPIDER_DEATH;
    public static final SoundEvent HEDGE_SPIDER_HURT;
    public static final SoundEvent HEDGE_SPIDER_STEP;
    public static final SoundEvent HELMET_CRAB_DEATH;
    public static final SoundEvent HELMET_CRAB_HURT;
    public static final SoundEvent HELMET_CRAB_STEP;
    public static final SoundEvent HOSTILE_WOLF_DEATH;
    public static final SoundEvent HOSTILE_WOLF_HURT;
    public static final SoundEvent HOSTILE_WOLF_AMBIENT;
    public static final SoundEvent HOSTILE_WOLF_TARGET;
    public static final SoundEvent HYDRA_DEATH;
    public static final SoundEvent HYDRA_GROWL;
    public static final SoundEvent HYDRA_HURT;
    public static final SoundEvent HYDRA_ROAR;
    public static final SoundEvent HYDRA_SHOOT;
    public static final SoundEvent HYDRA_WARN;
    public static final SoundEvent ICEBOMB_FIRED;
    public static final SoundEvent ICE_CORE_AMBIENT;
    public static final SoundEvent ICE_CORE_DEATH;
    public static final SoundEvent ICE_CORE_HURT;
    public static final SoundEvent ICE_CORE_SHOOT;
    public static final SoundEvent ICE_GUARDIAN_AMBIENT;
    public static final SoundEvent ICE_GUARDIAN_DEATH;
    public static final SoundEvent ICE_GUARDIAN_HURT;
    public static final SoundEvent JET_ACTIVE;
    public static final SoundEvent JET_POP;
    public static final SoundEvent JET_START;
    public static final SoundEvent KING_SPIDER_AMBIENT;
    public static final SoundEvent KING_SPIDER_DEATH;
    public static final SoundEvent KING_SPIDER_HURT;
    public static final SoundEvent KING_SPIDER_STEP;
    public static final SoundEvent KNIGHTMETAL_EQUIP;
    public static final SoundEvent KOBOLD_AMBIENT;
    public static final SoundEvent KOBOLD_DEATH;
    public static final SoundEvent KOBOLD_HURT;
    public static final SoundEvent KOBOLD_MUNCH;
    public static final SoundEvent LAMP_BURN;
    public static final SoundEvent LICH_AMBIENT;
    public static final SoundEvent LICH_CLONE_HURT;
    public static final SoundEvent LICH_DEATH;
    public static final SoundEvent LICH_HURT;
    public static final SoundEvent LICH_SHOOT;
    public static final SoundEvent LICH_TELEPORT;
    public static final SoundEvent LOCKED_VANISHING_BLOCK;
    public static final SoundEvent LOYAL_ZOMBIE_AMBIENT;
    public static final SoundEvent LOYAL_ZOMBIE_DEATH;
    public static final SoundEvent LOYAL_ZOMBIE_HURT;
    public static final SoundEvent LOYAL_ZOMBIE_STEP;
    public static final SoundEvent MAGNET_GRAB;
    public static final SoundEvent MAZE_SLIME_DEATH;
    public static final SoundEvent MAZE_SLIME_DEATH_SMALL;
    public static final SoundEvent MAZE_SLIME_HURT;
    public static final SoundEvent MAZE_SLIME_HURT_SMALL;
    public static final SoundEvent MAZE_SLIME_SQUISH;
    public static final SoundEvent MAZE_SLIME_SQUISH_SMALL;
    public static final SoundEvent MINION_AMBIENT;
    public static final SoundEvent MINION_DEATH;
    public static final SoundEvent MINION_HURT;
    public static final SoundEvent MINION_STEP;
    public static final SoundEvent MINION_SUMMON;
    public static final SoundEvent MINOSHROOM_AMBIENT;
    public static final SoundEvent MINOSHROOM_ATTACK;
    public static final SoundEvent MINOSHROOM_DEATH;
    public static final SoundEvent MINOSHROOM_HURT;
    public static final SoundEvent MINOSHROOM_SLAM;
    public static final SoundEvent MINOSHROOM_STEP;
    public static final SoundEvent MINOTAUR_AMBIENT;
    public static final SoundEvent MINOTAUR_ATTACK;
    public static final SoundEvent MINOTAUR_DEATH;
    public static final SoundEvent MINOTAUR_HURT;
    public static final SoundEvent MINOTAUR_STEP;
    public static final SoundEvent MISTWOLF_DEATH;
    public static final SoundEvent MISTWOLF_HURT;
    public static final SoundEvent MISTWOLF_AMBIENT;
    public static final SoundEvent MISTWOLF_TARGET;
    public static final SoundEvent MOONWORM_SQUISH;
    public static final SoundEvent MOSQUITO;
    public static final SoundEvent NAGA_HISS;
    public static final SoundEvent NAGA_HURT;
    public static final SoundEvent NAGA_RATTLE;
    public static final SoundEvent PEDESTAL_ACTIVATE;
    public static final SoundEvent PHANTOM_AMBIENT;
    public static final SoundEvent PHANTOM_DEATH;
    public static final SoundEvent PHANTOM_HURT;
    public static final SoundEvent PHANTOM_THROW_AXE;
    public static final SoundEvent PHANTOM_THROW_PICK;
    public static final SoundEvent PICKED_TORCHBERRIES;
    public static final SoundEvent PINCH_BEETLE_DEATH;
    public static final SoundEvent PINCH_BEETLE_HURT;
    public static final SoundEvent PINCH_BEETLE_STEP;
    public static final SoundEvent PORTAL_WOOSH;
    public static final SoundEvent POWDER_USE;
    public static final SoundEvent QUEST_RAM_AMBIENT;
    public static final SoundEvent QUEST_RAM_DEATH;
    public static final SoundEvent QUEST_RAM_HURT;
    public static final SoundEvent QUEST_RAM_STEP;
    public static final SoundEvent RAVEN_CAW;
    public static final SoundEvent RAVEN_SQUAWK;
    public static final SoundEvent REACTOR_AMBIENT;
    public static final SoundEvent REAPPEAR_BLOCK;
    public static final SoundEvent REAPPEAR_POOF;
    public static final SoundEvent REDCAP_AMBIENT;
    public static final SoundEvent REDCAP_DEATH;
    public static final SoundEvent REDCAP_HURT;
    public static final SoundEvent SCEPTER_DRAIN;
    public static final SoundEvent SCEPTER_PEARL;
    public static final SoundEvent SCEPTER_USE;
    public static final SoundEvent SHIELD_ADD;
    public static final SoundEvent SHIELD_BREAK;
    public static final SoundEvent SKELETON_DRUID_AMBIENT;
    public static final SoundEvent SKELETON_DRUID_DEATH;
    public static final SoundEvent SKELETON_DRUID_HURT;
    public static final SoundEvent SKELETON_DRUID_SHOOT;
    public static final SoundEvent SKELETON_DRUID_STEP;
    public static final SoundEvent SLIDER;
    public static final SoundEvent SLIME_BEETLE_DEATH;
    public static final SoundEvent SLIME_BEETLE_HURT;
    public static final SoundEvent SLIME_BEETLE_SQUISH_SMALL;
    public static final SoundEvent SLIME_BEETLE_STEP;
    public static final SoundEvent SMOKER_START;
    public static final SoundEvent SNOW_QUEEN_AMBIENT;
    public static final SoundEvent SNOW_QUEEN_ATTACK;
    public static final SoundEvent SNOW_QUEEN_BREAK;
    public static final SoundEvent SNOW_QUEEN_DEATH;
    public static final SoundEvent SNOW_QUEEN_HURT;
    public static final SoundEvent SWARM_SPIDER_AMBIENT;
    public static final SoundEvent SWARM_SPIDER_DEATH;
    public static final SoundEvent SWARM_SPIDER_HURT;
    public static final SoundEvent SWARM_SPIDER_STEP;
    public static final SoundEvent TEAR_BREAK;
    public static final SoundEvent TERMITE_AMBIENT;
    public static final SoundEvent TERMITE_DEATH;
    public static final SoundEvent TERMITE_HURT;
    public static final SoundEvent TERMITE_STEP;
    public static final SoundEvent TIME_CORE;
    public static final SoundEvent TINYBIRD_CHIRP;
    public static final SoundEvent TINYBIRD_HURT;
    public static final SoundEvent TINYBIRD_SONG;
    public static final SoundEvent TOME_DEATH;
    public static final SoundEvent TOME_HURT;
    public static final SoundEvent TOME_AMBIENT;
    public static final SoundEvent TRANSFORMATION_CORE;
    public static final SoundEvent UNCRAFTING_TABLE_ACTIVATE;
    public static final SoundEvent UNLOCK_VANISHING_BLOCK;
    public static final SoundEvent URGHAST_AMBIENT;
    public static final SoundEvent URGHAST_DEATH;
    public static final SoundEvent URGHAST_HURT;
    public static final SoundEvent URGHAST_SHOOT;
    public static final SoundEvent URGHAST_WARN;
    public static final SoundEvent VANISHING_BLOCK;
    public static final SoundEvent WINTER_WOLF_DEATH;
    public static final SoundEvent WINTER_WOLF_HURT;
    public static final SoundEvent WINTER_WOLF_AMBIENT;
    public static final SoundEvent WINTER_WOLF_SHOOT;
    public static final SoundEvent WINTER_WOLF_TARGET;
    public static final SoundEvent WRAITH_AMBIENT;
    public static final SoundEvent WRAITH_DEATH;
    public static final SoundEvent WRAITH_HURT;
    public static final SoundEvent YETI_DEATH;
    public static final SoundEvent YETI_GRAB;
    public static final SoundEvent YETI_GROWL;
    public static final SoundEvent YETI_HURT;
    public static final SoundEvent YETI_THROW;
    public static final SoundEvent ALPHAYETI_PARROT;
    public static final SoundEvent CARMINITE_GOLEM_PARROT;
    public static final SoundEvent HOSTILE_WOLF_PARROT;
    public static final SoundEvent HYDRA_PARROT;
    public static final SoundEvent ICE_CORE_PARROT;
    public static final SoundEvent KOBOLD_PARROT;
    public static final SoundEvent MINOTAUR_PARROT;
    public static final SoundEvent MOSQUITO_PARROT;
    public static final SoundEvent NAGA_PARROT;
    public static final SoundEvent REDCAP_PARROT;
    public static final SoundEvent TOME_PARROT;
    public static final SoundEvent WRAITH_PARROT;
    public static final SoundEvent MUSIC;
    public static final SoundEvent MUSIC_DISC_RADIANCE;
    public static final SoundEvent MUSIC_DISC_STEPS;
    public static final SoundEvent MUSIC_DISC_SUPERSTITIOUS;
    public static final SoundEvent MUSIC_DISC_HOME;
    public static final SoundEvent MUSIC_DISC_WAYFARER;
    public static final SoundEvent MUSIC_DISC_FINDINGS;
    public static final SoundEvent MUSIC_DISC_MAKER;
    public static final SoundEvent MUSIC_DISC_THREAD;
    public static final SoundEvent MUSIC_DISC_MOTION;
    
    private static SoundEvent createEvent(final String sound) {
        final ResourceLocation name = TwilightForestMod.prefix(sound);
        return (SoundEvent)new SoundEvent(name).setRegistryName(name);
    }
    
    static void registerSounds(final RegistryEvent.Register<SoundEvent> event) {
        event.getRegistry().registerAll((IForgeRegistryEntry[])new SoundEvent[] { TFSounds.ACID_RAIN_BURNS, TFSounds.ALPHAYETI_ALERT, TFSounds.ALPHAYETI_DEATH, TFSounds.ALPHAYETI_GRAB, TFSounds.ALPHAYETI_GROWL, TFSounds.ALPHAYETI_HURT, TFSounds.ALPHAYETI_ICE, TFSounds.ALPHAYETI_PANT, TFSounds.ALPHAYETI_ROAR, TFSounds.ALPHAYETI_THROW, TFSounds.BIGHORN_AMBIENT, TFSounds.BIGHORN_DEATH, TFSounds.BIGHORN_HURT, TFSounds.BIGHORN_STEP, TFSounds.BLOCKCHAIN_AMBIENT, TFSounds.BLOCKCHAIN_COLLIDE, TFSounds.BLOCKCHAIN_DEATH, TFSounds.BLOCKCHAIN_FIRED, TFSounds.BLOCKCHAIN_HIT, TFSounds.BLOCKCHAIN_HURT, TFSounds.BLOCK_ANNIHILATED, TFSounds.BOAR_AMBIENT, TFSounds.BOAR_DEATH, TFSounds.BOAR_HURT, TFSounds.BOAR_STEP, TFSounds.BRITTLE_FLASK_BREAK, TFSounds.BRITTLE_FLASK_CRACK, TFSounds.BROODLING_AMBIENT, TFSounds.BROODLING_DEATH, TFSounds.BROODLING_HURT, TFSounds.BROODLING_STEP, TFSounds.BUILDER_OFF, TFSounds.BUILDER_ON, TFSounds.BUILDER_REPLACE, TFSounds.BUILDER_CREATE, TFSounds.CARMINITE_GOLEM_ATTACK, TFSounds.CARMINITE_GOLEM_DEATH, TFSounds.CARMINITE_GOLEM_HURT, TFSounds.CARMINITE_GOLEM_STEP, TFSounds.CHARM_KEEP, TFSounds.CHARM_LIFE, TFSounds.CICADA, TFSounds.DEER_AMBIENT, TFSounds.DEER_DEATH, TFSounds.DEER_HURT, TFSounds.DWARF_AMBIENT, TFSounds.DWARF_DEATH, TFSounds.DWARF_HURT, TFSounds.DOOR_ACTIVATED, TFSounds.DOOR_REAPPEAR, TFSounds.DOOR_VANISH, TFSounds.FAN_WOOSH, TFSounds.FIRE_BEETLE_DEATH, TFSounds.FIRE_BEETLE_HURT, TFSounds.FIRE_BEETLE_SHOOT, TFSounds.FIRE_BEETLE_STEP, TFSounds.FLASK_FILL, TFSounds.GHASTGUARD_AMBIENT, TFSounds.GHASTGUARD_DEATH, TFSounds.GHASTGUARD_HURT, TFSounds.GHASTGUARD_SHOOT, TFSounds.GHASTGUARD_WARN, TFSounds.GHASTLING_AMBIENT, TFSounds.GHASTLING_DEATH, TFSounds.GHASTLING_HURT, TFSounds.GHASTLING_SHOOT, TFSounds.GHASTLING_WARN, TFSounds.GLASS_SWORD_BREAK, TFSounds.GOBLIN_KNIGHT_AMBIENT, TFSounds.GOBLIN_KNIGHT_DEATH, TFSounds.GOBLIN_KNIGHT_HURT, TFSounds.GOBLIN_KNIGHT_MUFFLED_AMBIENT, TFSounds.GOBLIN_KNIGHT_MUFFLED_DEATH, TFSounds.GOBLIN_KNIGHT_MUFFLED_HURT, TFSounds.HEDGE_SPIDER_AMBIENT, TFSounds.HEDGE_SPIDER_DEATH, TFSounds.HEDGE_SPIDER_HURT, TFSounds.HEDGE_SPIDER_STEP, TFSounds.HELMET_CRAB_DEATH, TFSounds.HELMET_CRAB_HURT, TFSounds.HELMET_CRAB_STEP, TFSounds.HOSTILE_WOLF_AMBIENT, TFSounds.HOSTILE_WOLF_DEATH, TFSounds.HOSTILE_WOLF_HURT, TFSounds.HOSTILE_WOLF_TARGET, TFSounds.HYDRA_DEATH, TFSounds.HYDRA_GROWL, TFSounds.HYDRA_HURT, TFSounds.HYDRA_ROAR, TFSounds.HYDRA_SHOOT, TFSounds.HYDRA_WARN, TFSounds.ICEBOMB_FIRED, TFSounds.ICE_CORE_AMBIENT, TFSounds.ICE_CORE_DEATH, TFSounds.ICE_CORE_HURT, TFSounds.ICE_CORE_SHOOT, TFSounds.ICE_GUARDIAN_AMBIENT, TFSounds.ICE_GUARDIAN_DEATH, TFSounds.ICE_GUARDIAN_HURT, TFSounds.JET_ACTIVE, TFSounds.JET_POP, TFSounds.JET_START, TFSounds.KING_SPIDER_AMBIENT, TFSounds.KING_SPIDER_DEATH, TFSounds.KING_SPIDER_HURT, TFSounds.KING_SPIDER_STEP, TFSounds.KNIGHTMETAL_EQUIP, TFSounds.KOBOLD_AMBIENT, TFSounds.KOBOLD_DEATH, TFSounds.KOBOLD_HURT, TFSounds.KOBOLD_MUNCH, TFSounds.LAMP_BURN, TFSounds.LICH_AMBIENT, TFSounds.LICH_CLONE_HURT, TFSounds.LICH_DEATH, TFSounds.LICH_HURT, TFSounds.LICH_SHOOT, TFSounds.LICH_TELEPORT, TFSounds.LOCKED_VANISHING_BLOCK, TFSounds.LOYAL_ZOMBIE_AMBIENT, TFSounds.LOYAL_ZOMBIE_DEATH, TFSounds.LOYAL_ZOMBIE_HURT, TFSounds.LOYAL_ZOMBIE_STEP, TFSounds.MAGNET_GRAB, TFSounds.MAZE_SLIME_DEATH, TFSounds.MAZE_SLIME_DEATH_SMALL, TFSounds.MAZE_SLIME_HURT, TFSounds.MAZE_SLIME_HURT_SMALL, TFSounds.MAZE_SLIME_SQUISH, TFSounds.MAZE_SLIME_SQUISH_SMALL, TFSounds.MINION_AMBIENT, TFSounds.MINION_DEATH, TFSounds.MINION_HURT, TFSounds.MINION_STEP, TFSounds.MINION_SUMMON, TFSounds.MINOSHROOM_AMBIENT, TFSounds.MINOSHROOM_ATTACK, TFSounds.MINOSHROOM_DEATH, TFSounds.MINOSHROOM_HURT, TFSounds.MINOSHROOM_SLAM, TFSounds.MINOSHROOM_STEP, TFSounds.MINOTAUR_AMBIENT, TFSounds.MINOTAUR_ATTACK, TFSounds.MINOTAUR_DEATH, TFSounds.MINOTAUR_HURT, TFSounds.MINOTAUR_STEP, TFSounds.MISTWOLF_AMBIENT, TFSounds.MISTWOLF_DEATH, TFSounds.MISTWOLF_HURT, TFSounds.MISTWOLF_TARGET, TFSounds.MOONWORM_SQUISH, TFSounds.MOSQUITO, TFSounds.NAGA_HISS, TFSounds.NAGA_HURT, TFSounds.NAGA_RATTLE, TFSounds.PEDESTAL_ACTIVATE, TFSounds.PHANTOM_AMBIENT, TFSounds.PHANTOM_DEATH, TFSounds.PHANTOM_HURT, TFSounds.PHANTOM_THROW_AXE, TFSounds.PHANTOM_THROW_PICK, TFSounds.PICKED_TORCHBERRIES, TFSounds.PINCH_BEETLE_DEATH, TFSounds.PINCH_BEETLE_HURT, TFSounds.PINCH_BEETLE_STEP, TFSounds.PORTAL_WOOSH, TFSounds.POWDER_USE, TFSounds.QUEST_RAM_AMBIENT, TFSounds.QUEST_RAM_DEATH, TFSounds.QUEST_RAM_HURT, TFSounds.QUEST_RAM_STEP, TFSounds.RAVEN_CAW, TFSounds.RAVEN_SQUAWK, TFSounds.REACTOR_AMBIENT, TFSounds.REAPPEAR_BLOCK, TFSounds.REAPPEAR_POOF, TFSounds.REDCAP_AMBIENT, TFSounds.REDCAP_DEATH, TFSounds.REDCAP_HURT, TFSounds.SCEPTER_DRAIN, TFSounds.SCEPTER_PEARL, TFSounds.SCEPTER_USE, TFSounds.SHIELD_ADD, TFSounds.SHIELD_BREAK, TFSounds.SKELETON_DRUID_AMBIENT, TFSounds.SKELETON_DRUID_DEATH, TFSounds.SKELETON_DRUID_HURT, TFSounds.SKELETON_DRUID_SHOOT, TFSounds.SKELETON_DRUID_STEP, TFSounds.SLIME_BEETLE_DEATH, TFSounds.SLIME_BEETLE_HURT, TFSounds.SLIME_BEETLE_SQUISH_SMALL, TFSounds.SLIME_BEETLE_STEP, TFSounds.SMOKER_START, TFSounds.SNOW_QUEEN_AMBIENT, TFSounds.SNOW_QUEEN_ATTACK, TFSounds.SNOW_QUEEN_BREAK, TFSounds.SNOW_QUEEN_DEATH, TFSounds.SNOW_QUEEN_HURT, TFSounds.SWARM_SPIDER_AMBIENT, TFSounds.SWARM_SPIDER_DEATH, TFSounds.SWARM_SPIDER_HURT, TFSounds.SWARM_SPIDER_STEP, TFSounds.TEAR_BREAK, TFSounds.TERMITE_AMBIENT, TFSounds.TERMITE_DEATH, TFSounds.TERMITE_HURT, TFSounds.TERMITE_STEP, TFSounds.TIME_CORE, TFSounds.TINYBIRD_CHIRP, TFSounds.TINYBIRD_HURT, TFSounds.TINYBIRD_SONG, TFSounds.TOME_AMBIENT, TFSounds.TOME_DEATH, TFSounds.TOME_HURT, TFSounds.TRANSFORMATION_CORE, TFSounds.UNCRAFTING_TABLE_ACTIVATE, TFSounds.UNLOCK_VANISHING_BLOCK, TFSounds.URGHAST_AMBIENT, TFSounds.URGHAST_DEATH, TFSounds.URGHAST_HURT, TFSounds.URGHAST_SHOOT, TFSounds.URGHAST_WARN, TFSounds.GHAST_TRAP_AMBIENT, TFSounds.GHAST_TRAP_ACTIVE, TFSounds.GHAST_TRAP_ON, TFSounds.GHAST_TRAP_SPINDOWN, TFSounds.GHAST_TRAP_WARMUP, TFSounds.VANISHING_BLOCK, TFSounds.WINTER_WOLF_AMBIENT, TFSounds.WINTER_WOLF_DEATH, TFSounds.WINTER_WOLF_HURT, TFSounds.WINTER_WOLF_SHOOT, TFSounds.WINTER_WOLF_TARGET, TFSounds.WRAITH_AMBIENT, TFSounds.WRAITH_DEATH, TFSounds.WRAITH_HURT, TFSounds.YETI_DEATH, TFSounds.YETI_GRAB, TFSounds.YETI_GROWL, TFSounds.YETI_HURT, TFSounds.YETI_THROW, TFSounds.ALPHAYETI_PARROT, TFSounds.CARMINITE_GOLEM_PARROT, TFSounds.HOSTILE_WOLF_PARROT, TFSounds.HYDRA_PARROT, TFSounds.ICE_CORE_PARROT, TFSounds.KOBOLD_PARROT, TFSounds.MOSQUITO_PARROT, TFSounds.NAGA_PARROT, TFSounds.REDCAP_PARROT, TFSounds.TOME_PARROT, TFSounds.WRAITH_PARROT, TFSounds.SLIDER, TFSounds.CASKET_CLOSE, TFSounds.CASKET_OPEN, TFSounds.CASKET_LOCKED, TFSounds.CASKET_REPAIR, TFSounds.MUSIC_DISC_RADIANCE, TFSounds.MUSIC_DISC_STEPS, TFSounds.MUSIC_DISC_SUPERSTITIOUS, TFSounds.MUSIC_DISC_HOME, TFSounds.MUSIC_DISC_WAYFARER, TFSounds.MUSIC_DISC_FINDINGS, TFSounds.MUSIC_DISC_MAKER, TFSounds.MUSIC_DISC_THREAD, TFSounds.MUSIC_DISC_MOTION, TFSounds.MUSIC });
    }
    
    public static void registerParrotSounds() {
        Parrot.f_29358_.put(TFEntities.ALPHA_YETI, TFSounds.ALPHAYETI_PARROT);
        Parrot.f_29358_.put(TFEntities.BLOCKCHAIN_GOBLIN, TFSounds.REDCAP_PARROT);
        Parrot.f_29358_.put(TFEntities.CARMINITE_BROODLING, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.CARMINITE_GOLEM, TFSounds.CARMINITE_GOLEM_PARROT);
        Parrot.f_29358_.put(TFEntities.FIRE_BEETLE, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.CARMINITE_GHASTLING, SoundEvents.f_12253_);
        Parrot.f_29358_.put(TFEntities.CARMINITE_GHASTGUARD, SoundEvents.f_12253_);
        Parrot.f_29358_.put(TFEntities.HEDGE_SPIDER, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.HELMET_CRAB, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.HOSTILE_WOLF, TFSounds.HOSTILE_WOLF_PARROT);
        Parrot.f_29358_.put(TFEntities.HYDRA, TFSounds.HYDRA_PARROT);
        Parrot.f_29358_.put(TFEntities.STABLE_ICE_CORE, TFSounds.ICE_CORE_PARROT);
        Parrot.f_29358_.put(TFEntities.KING_SPIDER, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.KOBOLD, TFSounds.KOBOLD_PARROT);
        Parrot.f_29358_.put(TFEntities.LICH, SoundEvents.f_12246_);
        Parrot.f_29358_.put(TFEntities.MAZE_SLIME, SoundEvents.f_12267_);
        Parrot.f_29358_.put(TFEntities.LICH_MINION, SoundEvents.f_12224_);
        Parrot.f_29358_.put(TFEntities.MINOSHROOM, TFSounds.MINOTAUR_PARROT);
        Parrot.f_29358_.put(TFEntities.MINOTAUR, TFSounds.MINOTAUR_PARROT);
        Parrot.f_29358_.put(TFEntities.MIST_WOLF, TFSounds.HOSTILE_WOLF_PARROT);
        Parrot.f_29358_.put(TFEntities.MOSQUITO_SWARM, TFSounds.MOSQUITO_PARROT);
        Parrot.f_29358_.put(TFEntities.NAGA, TFSounds.NAGA_PARROT);
        Parrot.f_29358_.put(TFEntities.KNIGHT_PHANTOM, TFSounds.WRAITH_PARROT);
        Parrot.f_29358_.put(TFEntities.PINCH_BEETLE, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.REDCAP, TFSounds.REDCAP_PARROT);
        Parrot.f_29358_.put(TFEntities.REDCAP_SAPPER, TFSounds.REDCAP_PARROT);
        Parrot.f_29358_.put(TFEntities.SKELETON_DRUID, SoundEvents.f_12266_);
        Parrot.f_29358_.put(TFEntities.SLIME_BEETLE, SoundEvents.f_12267_);
        Parrot.f_29358_.put(TFEntities.SNOW_GUARDIAN, TFSounds.ICE_CORE_PARROT);
        Parrot.f_29358_.put(TFEntities.SNOW_QUEEN, TFSounds.ICE_CORE_PARROT);
        Parrot.f_29358_.put(TFEntities.SWARM_SPIDER, SoundEvents.f_12268_);
        Parrot.f_29358_.put(TFEntities.TOWERWOOD_BORER, SoundEvents.f_12265_);
        Parrot.f_29358_.put(TFEntities.DEATH_TOME, TFSounds.TOME_PARROT);
        Parrot.f_29358_.put(TFEntities.UR_GHAST, SoundEvents.f_12253_);
        Parrot.f_29358_.put(TFEntities.WINTER_WOLF, TFSounds.HOSTILE_WOLF_PARROT);
        Parrot.f_29358_.put(TFEntities.WRAITH, TFSounds.WRAITH_PARROT);
        Parrot.f_29358_.put(TFEntities.YETI, TFSounds.ALPHAYETI_PARROT);
    }
    
    private TFSounds() {
    }
    
    static {
        ACID_RAIN_BURNS = createEvent("entity.twilightforest.acid_rain");
        ALPHAYETI_ALERT = createEvent("entity.twilightforest.alphayeti.alert");
        ALPHAYETI_DEATH = createEvent("entity.twilightforest.alphayeti.death");
        ALPHAYETI_GRAB = createEvent("entity.twilightforest.alphayeti.grab");
        ALPHAYETI_GROWL = createEvent("entity.twilightforest.alphayeti.growl");
        ALPHAYETI_HURT = createEvent("entity.twilightforest.alphayeti.hurt");
        ALPHAYETI_ICE = createEvent("entity.twilightforest.alphayeti.ice");
        ALPHAYETI_PANT = createEvent("entity.twilightforest.alphayeti.pant");
        ALPHAYETI_ROAR = createEvent("entity.twilightforest.alphayeti.roar");
        ALPHAYETI_THROW = createEvent("entity.twilightforest.alphayeti.throw");
        BIGHORN_AMBIENT = createEvent("entity.twilightforest.bighorn.ambient");
        BIGHORN_DEATH = createEvent("entity.twilightforest.bighorn.death");
        BIGHORN_HURT = createEvent("entity.twilightforest.bighorn.hurt");
        BIGHORN_STEP = createEvent("entity.twilightforest.bighorn.step");
        BLOCKCHAIN_AMBIENT = createEvent("entity.twilightforest.blockchain.ambient");
        BLOCKCHAIN_COLLIDE = createEvent("item.twilightforest.blockchain.collide");
        BLOCKCHAIN_DEATH = createEvent("entity.twilightforest.blockchain.death");
        BLOCKCHAIN_FIRED = createEvent("item.twilightforest.blockchain.fire");
        BLOCKCHAIN_HIT = createEvent("item.twilightforest.blockchain.hit");
        BLOCKCHAIN_HURT = createEvent("entity.twilightforest.blockchain.hurt");
        BLOCK_ANNIHILATED = createEvent("block.twilightforest.generic.annihilation");
        BOAR_AMBIENT = createEvent("entity.twilightforest.boar.ambient");
        BOAR_DEATH = createEvent("entity.twilightforest.boar.death");
        BOAR_HURT = createEvent("entity.twilightforest.boar.hurt");
        BOAR_STEP = createEvent("entity.twilightforest.boar.step");
        BRITTLE_FLASK_BREAK = createEvent("item.twilightforest.flask.break");
        BRITTLE_FLASK_CRACK = createEvent("item.twilightforest.flask.crack");
        BROODLING_AMBIENT = createEvent("entity.twilightforest.broodling.ambient");
        BROODLING_DEATH = createEvent("entity.twilightforest.broodling.death");
        BROODLING_HURT = createEvent("entity.twilightforest.broodling.hurt");
        BROODLING_STEP = createEvent("entity.twilightforest.broodling.step");
        BUILDER_OFF = createEvent("block.twilightforest.builder.off");
        BUILDER_ON = createEvent("block.twilightforest.builder.on");
        BUILDER_REPLACE = createEvent("block.twilightforest.builder.replace");
        BUILDER_CREATE = createEvent("block.twilightforest.builder.create");
        BUG_SQUISH = createEvent("block.twilightforest.bug.squish");
        CARMINITE_GOLEM_ATTACK = createEvent("entity.twilightforest.carminitegolem.attack");
        CARMINITE_GOLEM_DEATH = createEvent("entity.twilightforest.carminitegolem.death");
        CARMINITE_GOLEM_HURT = createEvent("entity.twilightforest.carminitegolem.hurt");
        CARMINITE_GOLEM_STEP = createEvent("entity.twilightforest.carminitegolem.step");
        CASKET_OPEN = createEvent("block.twilightforest.casket.open");
        CASKET_CLOSE = createEvent("block.twilightforest.casket.close");
        CASKET_LOCKED = createEvent("block.twilightforest.casket.locked");
        CASKET_REPAIR = createEvent("block.twilightforest.casket.repair");
        CHARM_KEEP = createEvent("item.twilightforest.charm.keep");
        CHARM_LIFE = createEvent("item.twilightforest.charm.life");
        CICADA = createEvent("entity.twilightforest.cicada");
        CICADA_FLYING = createEvent("entity.twilightforest.cicada_flying");
        DEER_DEATH = createEvent("entity.twilightforest.deer.death");
        DEER_HURT = createEvent("entity.twilightforest.deer.hurt");
        DEER_AMBIENT = createEvent("entity.twilightforest.deer.ambient");
        DWARF_DEATH = createEvent("entity.twilightforest.dwarf_rabbit.death");
        DWARF_HURT = createEvent("entity.twilightforest.dwarf_rabbit.hurt");
        DWARF_AMBIENT = createEvent("entity.twilightforest.dwarf_rabbit.ambient");
        DOOR_ACTIVATED = createEvent("block.twilightforest.door.activate");
        DOOR_REAPPEAR = createEvent("block.twilightforest.door.reappear");
        DOOR_VANISH = createEvent("block.twilightforest.door.vanish");
        FAN_WOOSH = createEvent("item.twilightforest.fan.woosh");
        FIRE_BEETLE_DEATH = createEvent("entity.twilightforest.firebeetle.death");
        FIRE_BEETLE_HURT = createEvent("entity.twilightforest.firebeetle.hurt");
        FIRE_BEETLE_SHOOT = createEvent("entity.twilightforest.firebeetle.shoot");
        FIRE_BEETLE_STEP = createEvent("entity.twilightforest.firebeetle.step");
        FLASK_FILL = createEvent("item.twilightforest.flask.fill");
        GHASTGUARD_AMBIENT = createEvent("entity.twilightforest.ghastguard.ambient");
        GHASTGUARD_DEATH = createEvent("entity.twilightforest.ghastguard.death");
        GHASTGUARD_HURT = createEvent("entity.twilightforest.ghastguard.hurt");
        GHASTGUARD_SHOOT = createEvent("entity.twilightforest.ghastguard.shoot");
        GHASTGUARD_WARN = createEvent("entity.twilightforest.ghastguard.warn");
        GHASTLING_AMBIENT = createEvent("entity.twilightforest.ghastling.ambient");
        GHASTLING_DEATH = createEvent("entity.twilightforest.ghastling.death");
        GHASTLING_HURT = createEvent("entity.twilightforest.ghastling.hurt");
        GHASTLING_SHOOT = createEvent("entity.twilightforest.ghastling.shoot");
        GHASTLING_WARN = createEvent("entity.twilightforest.ghastling.warn");
        GHAST_TRAP_ACTIVE = createEvent("block.twilightforest.ghast_trap.active");
        GHAST_TRAP_AMBIENT = createEvent("block.twilightforest.ghast_trap.ambient");
        GHAST_TRAP_ON = createEvent("block.twilightforest.ghast_trap.on");
        GHAST_TRAP_SPINDOWN = createEvent("block.twilightforest.ghast_trap.spindown");
        GHAST_TRAP_WARMUP = createEvent("block.twilightforest.ghast_trap.warmup");
        GLASS_SWORD_BREAK = createEvent("item.twilightforest.glasssword.break");
        GOBLIN_KNIGHT_AMBIENT = createEvent("entity.twilightforest.goblinKnight.ambient");
        GOBLIN_KNIGHT_DEATH = createEvent("entity.twilightforest.goblinKnight.death");
        GOBLIN_KNIGHT_HURT = createEvent("entity.twilightforest.goblinKnight.hurt");
        GOBLIN_KNIGHT_MUFFLED_AMBIENT = createEvent("entity.twilightforest.goblinknight.muffled.ambient");
        GOBLIN_KNIGHT_MUFFLED_DEATH = createEvent("entity.twilightforest.goblinknight.muffled.death");
        GOBLIN_KNIGHT_MUFFLED_HURT = createEvent("entity.twilightforest.goblinknight.muffled.hurt");
        HEDGE_SPIDER_AMBIENT = createEvent("entity.twilightforest.hedgespider.ambient");
        HEDGE_SPIDER_DEATH = createEvent("entity.twilightforest.hedgespider.death");
        HEDGE_SPIDER_HURT = createEvent("entity.twilightforest.hedgespider.hurt");
        HEDGE_SPIDER_STEP = createEvent("entity.twilightforest.hedgespider.step");
        HELMET_CRAB_DEATH = createEvent("entity.twilightforest.helmetcrab.death");
        HELMET_CRAB_HURT = createEvent("entity.twilightforest.helmetcrab.hurt");
        HELMET_CRAB_STEP = createEvent("entity.twilightforest.helmetcrab.step");
        HOSTILE_WOLF_DEATH = createEvent("entity.twilightforest.hostilewolf.death");
        HOSTILE_WOLF_HURT = createEvent("entity.twilightforest.hostilewolf.hurt");
        HOSTILE_WOLF_AMBIENT = createEvent("entity.twilightforest.hostilewolf.ambient");
        HOSTILE_WOLF_TARGET = createEvent("entity.twilightforest.hostilewolf.target");
        HYDRA_DEATH = createEvent("entity.twilightforest.hydra.death");
        HYDRA_GROWL = createEvent("entity.twilightforest.hydra.growl");
        HYDRA_HURT = createEvent("entity.twilightforest.hydra.hurt");
        HYDRA_ROAR = createEvent("entity.twilightforest.hydra.roar");
        HYDRA_SHOOT = createEvent("entity.twilightforest.hydra.shoot");
        HYDRA_WARN = createEvent("entity.twilightforest.hydra.warn");
        ICEBOMB_FIRED = createEvent("item.twilightforest.icebomb.fired");
        ICE_CORE_AMBIENT = createEvent("entity.twilightforest.ice.noise");
        ICE_CORE_DEATH = createEvent("entity.twilightforest.ice.death");
        ICE_CORE_HURT = createEvent("entity.twilightforest.ice.hurt");
        ICE_CORE_SHOOT = createEvent("entity.twilightforest.ice.shoot");
        ICE_GUARDIAN_AMBIENT = createEvent("entity.twilightforest.iceguardian.ambient");
        ICE_GUARDIAN_DEATH = createEvent("entity.twilightforest.iceguardian.death");
        ICE_GUARDIAN_HURT = createEvent("entity.twilightforest.iceguardian.hurt");
        JET_ACTIVE = createEvent("block.twilightforest.jet.active");
        JET_POP = createEvent("block.twilightforest.jet.pop");
        JET_START = createEvent("block.twilightforest.jet.start");
        KING_SPIDER_AMBIENT = createEvent("entity.twilightforest.kingspider.ambient");
        KING_SPIDER_DEATH = createEvent("entity.twilightforest.kingspider.death");
        KING_SPIDER_HURT = createEvent("entity.twilightforest.kingspider.hurt");
        KING_SPIDER_STEP = createEvent("entity.twilightforest.kingspider.step");
        KNIGHTMETAL_EQUIP = createEvent("item.twilightforest.armor.equip_knightmetal");
        KOBOLD_AMBIENT = createEvent("entity.twilightforest.kobold.ambient");
        KOBOLD_DEATH = createEvent("entity.twilightforest.kobold.death");
        KOBOLD_HURT = createEvent("entity.twilightforest.kobold.hurt");
        KOBOLD_MUNCH = createEvent("entity.twilightforest.kobold.munch");
        LAMP_BURN = createEvent("item.twilightforest.lamp.burn");
        LICH_AMBIENT = createEvent("entity.twilightforest.lich.ambient");
        LICH_CLONE_HURT = createEvent("entity.twilightforest.lichclone.hurt");
        LICH_DEATH = createEvent("entity.twilightforest.lich.death");
        LICH_HURT = createEvent("entity.twilightforest.lich.hurt");
        LICH_SHOOT = createEvent("entity.twilightforest.lich.shoot");
        LICH_TELEPORT = createEvent("entity.twilightforest.lich.teleport");
        LOCKED_VANISHING_BLOCK = createEvent("block.twilightforest.vanish.locked");
        LOYAL_ZOMBIE_AMBIENT = createEvent("entity.twilightforest.loyalzombie.ambient");
        LOYAL_ZOMBIE_DEATH = createEvent("entity.twilightforest.loyalzombie.death");
        LOYAL_ZOMBIE_HURT = createEvent("entity.twilightforest.loyalzombie.hurt");
        LOYAL_ZOMBIE_STEP = createEvent("entity.twilightforest.loyalzombie.step");
        MAGNET_GRAB = createEvent("item.twilightforest.magnet.grab");
        MAZE_SLIME_DEATH = createEvent("entity.twilightforest.mazeslime.death");
        MAZE_SLIME_DEATH_SMALL = createEvent("entity.twilightforest.mazeslimesmall.death");
        MAZE_SLIME_HURT = createEvent("entity.twilightforest.mazeslime.hurt");
        MAZE_SLIME_HURT_SMALL = createEvent("entity.twilightforest.mazeslimesmall.hurt");
        MAZE_SLIME_SQUISH = createEvent("entity.twilightforest.mazeslime.squish");
        MAZE_SLIME_SQUISH_SMALL = createEvent("entity.twilightforest.mazeslimesmall.squish");
        MINION_AMBIENT = createEvent("entity.twilightforest.minion.ambient");
        MINION_DEATH = createEvent("entity.twilightforest.minion.death");
        MINION_HURT = createEvent("entity.twilightforest.minion.hurt");
        MINION_STEP = createEvent("entity.twilightforest.minion.step");
        MINION_SUMMON = createEvent("entity.twilightforest.minion.summon");
        MINOSHROOM_AMBIENT = createEvent("entity.twilightforest.minoshroom.ambient");
        MINOSHROOM_ATTACK = createEvent("entity.twilightforest.minoshroom.attack");
        MINOSHROOM_DEATH = createEvent("entity.twilightforest.minoshroom.death");
        MINOSHROOM_HURT = createEvent("entity.twilightforest.minoshroom.hurt");
        MINOSHROOM_SLAM = createEvent("entity.twilightforest.minoshroom.slam");
        MINOSHROOM_STEP = createEvent("entity.twilightforest.minoshroom.step");
        MINOTAUR_AMBIENT = createEvent("entity.twilightforest.minotaur.ambient");
        MINOTAUR_ATTACK = createEvent("entity.twilightforest.minotaur.attack");
        MINOTAUR_DEATH = createEvent("entity.twilightforest.minotaur.death");
        MINOTAUR_HURT = createEvent("entity.twilightforest.minotaur.hurt");
        MINOTAUR_STEP = createEvent("entity.twilightforest.minotaur.step");
        MISTWOLF_DEATH = createEvent("entity.twilightforest.mistwolf.death");
        MISTWOLF_HURT = createEvent("entity.twilightforest.mistwolf.hurt");
        MISTWOLF_AMBIENT = createEvent("entity.twilightforest.mistwolf.ambient");
        MISTWOLF_TARGET = createEvent("entity.twilightforest.mistwolf.target");
        MOONWORM_SQUISH = createEvent("item.twilightforest.moonworm.squish");
        MOSQUITO = createEvent("entity.twilightforest.mosquito.ambient");
        NAGA_HISS = createEvent("entity.twilightforest.naga.hiss");
        NAGA_HURT = createEvent("entity.twilightforest.naga.hurt");
        NAGA_RATTLE = createEvent("entity.twilightforest.naga.rattle");
        PEDESTAL_ACTIVATE = createEvent("block.twilightforest.pedestal.activate");
        PHANTOM_AMBIENT = createEvent("entity.twilightforest.phantom.ambient");
        PHANTOM_DEATH = createEvent("entity.twilightforest.phantom.death");
        PHANTOM_HURT = createEvent("entity.twilightforest.phantom.hurt");
        PHANTOM_THROW_AXE = createEvent("entity.twilightforest.phantom.axe");
        PHANTOM_THROW_PICK = createEvent("entity.twilightforest.phantom.pick");
        PICKED_TORCHBERRIES = createEvent("block.twilightforest.torchberry.harvest");
        PINCH_BEETLE_DEATH = createEvent("entity.twilightforest.pinchbeetle.death");
        PINCH_BEETLE_HURT = createEvent("entity.twilightforest.pinchbeetle.hurt");
        PINCH_BEETLE_STEP = createEvent("entity.twilightforest.pinchbeetle.step");
        PORTAL_WOOSH = createEvent("block.twilightforest.portal.woosh");
        POWDER_USE = createEvent("item.twilightforest.powder.use");
        QUEST_RAM_AMBIENT = createEvent("entity.twilightforest.quest.ambient");
        QUEST_RAM_DEATH = createEvent("entity.twilightforest.quest.death");
        QUEST_RAM_HURT = createEvent("entity.twilightforest.quest.hurt");
        QUEST_RAM_STEP = createEvent("entity.twilightforest.quest.step");
        RAVEN_CAW = createEvent("entity.twilightforest.raven.caw");
        RAVEN_SQUAWK = createEvent("entity.twilightforest.raven.squawk");
        REACTOR_AMBIENT = createEvent("block.twilightforest.reactor.ambient");
        REAPPEAR_BLOCK = createEvent("block.twilightforest.reappear.reappear");
        REAPPEAR_POOF = createEvent("block.twilightforest.reappear.vanish");
        REDCAP_AMBIENT = createEvent("entity.twilightforest.redcap.ambient");
        REDCAP_DEATH = createEvent("entity.twilightforest.redcap.death");
        REDCAP_HURT = createEvent("entity.twilightforest.redcap.hurt");
        SCEPTER_DRAIN = createEvent("item.twilightforest.scepter.drain");
        SCEPTER_PEARL = createEvent("item.twilightforest.scepter.pearl");
        SCEPTER_USE = createEvent("item.twilightforest.scepter.use");
        SHIELD_ADD = createEvent("entity.twilightforest.shield.add");
        SHIELD_BREAK = createEvent("entity.twilightforest.shield.break");
        SKELETON_DRUID_AMBIENT = createEvent("entity.twilightforest.druid.ambient");
        SKELETON_DRUID_DEATH = createEvent("entity.twilightforest.druid.death");
        SKELETON_DRUID_HURT = createEvent("entity.twilightforest.druid.hurt");
        SKELETON_DRUID_SHOOT = createEvent("entity.twilightforest.druid.shoot");
        SKELETON_DRUID_STEP = createEvent("entity.twilightforest.druid.step");
        SLIDER = createEvent("block.twilightforest.slider");
        SLIME_BEETLE_DEATH = createEvent("entity.twilightforest.slimebeetle.death");
        SLIME_BEETLE_HURT = createEvent("entity.twilightforest.slimebeetle.hurt");
        SLIME_BEETLE_SQUISH_SMALL = createEvent("entity.twilightforest.slimebeetle.squish");
        SLIME_BEETLE_STEP = createEvent("entity.twilightforest.slimebeetle.step");
        SMOKER_START = createEvent("block.twilightforest.smoker.start");
        SNOW_QUEEN_AMBIENT = createEvent("entity.twilightforest.snowqueen.ambient");
        SNOW_QUEEN_ATTACK = createEvent("entity.twilightforest.snowqueen.attack");
        SNOW_QUEEN_BREAK = createEvent("entity.twilightforest.snowqueen.break");
        SNOW_QUEEN_DEATH = createEvent("entity.twilightforest.snowqueen.death");
        SNOW_QUEEN_HURT = createEvent("entity.twilightforest.snowqueen.hurt");
        SWARM_SPIDER_AMBIENT = createEvent("entity.twilightforest.swarmspider.ambient");
        SWARM_SPIDER_DEATH = createEvent("entity.twilightforest.swarmspider.death");
        SWARM_SPIDER_HURT = createEvent("entity.twilightforest.swarmspider.hurt");
        SWARM_SPIDER_STEP = createEvent("entity.twilightforest.swarmspider.step");
        TEAR_BREAK = createEvent("entity.twilightforest.tear.break");
        TERMITE_AMBIENT = createEvent("entity.twilightforest.termite.ambient");
        TERMITE_DEATH = createEvent("entity.twilightforest.termite.death");
        TERMITE_HURT = createEvent("entity.twilightforest.termite.hurt");
        TERMITE_STEP = createEvent("entity.twilightforest.termite.step");
        TIME_CORE = createEvent("block.twilightforest.core.time");
        TINYBIRD_CHIRP = createEvent("entity.twilightforest.tinybird.chirp");
        TINYBIRD_HURT = createEvent("entity.twilightforest.tinybird.hurt");
        TINYBIRD_SONG = createEvent("entity.twilightforest.tinybird.song");
        TOME_DEATH = createEvent("entity.twilightforest.tome.death");
        TOME_HURT = createEvent("entity.twilightforest.tome.hurt");
        TOME_AMBIENT = createEvent("entity.twilightforest.tome.ambient");
        TRANSFORMATION_CORE = createEvent("block.twilightforest.core.transformation");
        UNCRAFTING_TABLE_ACTIVATE = createEvent("block.twilightforest.uncrafting_table.activate");
        UNLOCK_VANISHING_BLOCK = createEvent("block.twilightforest.vanish.unlock");
        URGHAST_AMBIENT = createEvent("entity.twilightforest.urghast.ambient");
        URGHAST_DEATH = createEvent("entity.twilightforest.urghast.death");
        URGHAST_HURT = createEvent("entity.twilightforest.urghast.hurt");
        URGHAST_SHOOT = createEvent("entity.twilightforest.urghast.shoot");
        URGHAST_WARN = createEvent("entity.twilightforest.urghast.warn");
        VANISHING_BLOCK = createEvent("block.twilightforest.vanish.vanish");
        WINTER_WOLF_DEATH = createEvent("entity.twilightforest.winterwolf.death");
        WINTER_WOLF_HURT = createEvent("entity.twilightforest.winterwolf.hurt");
        WINTER_WOLF_AMBIENT = createEvent("entity.twilightforest.winterwolf.ambient");
        WINTER_WOLF_SHOOT = createEvent("entity.twilightforest.winterwolf.shoot");
        WINTER_WOLF_TARGET = createEvent("entity.twilightforest.winterwolf.target");
        WRAITH_AMBIENT = createEvent("entity.twilightforest.wraith.ambient");
        WRAITH_DEATH = createEvent("entity.twilightforest.wraith.death");
        WRAITH_HURT = createEvent("entity.twilightforest.wraith.hurt");
        YETI_DEATH = createEvent("entity.twilightforest.yeti.death");
        YETI_GRAB = createEvent("entity.twilightforest.yeti.grab");
        YETI_GROWL = createEvent("entity.twilightforest.yeti.growl");
        YETI_HURT = createEvent("entity.twilightforest.yeti.hurt");
        YETI_THROW = createEvent("entity.twilightforest.yeti.throw");
        ALPHAYETI_PARROT = createEvent("entity.twilightforest.alphayeti.parrot");
        CARMINITE_GOLEM_PARROT = createEvent("entity.twilightforest.carminitegolem.parrot");
        HOSTILE_WOLF_PARROT = createEvent("entity.twilightforest.hostilewolf.parrot");
        HYDRA_PARROT = createEvent("entity.twilightforest.hydra.parrot");
        ICE_CORE_PARROT = createEvent("entity.twilightforest.icecore.parrot");
        KOBOLD_PARROT = createEvent("entity.twilightforest.kobold.parrot");
        MINOTAUR_PARROT = createEvent("entity.twilightforest.minotaur.parrot");
        MOSQUITO_PARROT = createEvent("entity.twilightforest.mosquito.parrot");
        NAGA_PARROT = createEvent("entity.twilightforest.naga.parrot");
        REDCAP_PARROT = createEvent("entity.twilightforest.redcap.parrot");
        TOME_PARROT = createEvent("entity.twilightforest.tome.parrot");
        WRAITH_PARROT = createEvent("entity.twilightforest.wraith.parrot");
        MUSIC = createEvent("music.bg");
        MUSIC_DISC_RADIANCE = createEvent("music_disc.twilightforest.radiance");
        MUSIC_DISC_STEPS = createEvent("music_disc.twilightforest.steps");
        MUSIC_DISC_SUPERSTITIOUS = createEvent("music_disc.twilightforest.superstitious");
        MUSIC_DISC_HOME = createEvent("music_disc.twilightforest.home");
        MUSIC_DISC_WAYFARER = createEvent("music_disc.twilightforest.wayfarer");
        MUSIC_DISC_FINDINGS = createEvent("music_disc.twilightforest.findings");
        MUSIC_DISC_MAKER = createEvent("music_disc.twilightforest.maker");
        MUSIC_DISC_THREAD = createEvent("music_disc.twilightforest.thread");
        MUSIC_DISC_MOTION = createEvent("music_disc.twilightforest.motion");
    }
}
