// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest;

import twilightforest.tileentity.TileEntityTFMoonworm;
import twilightforest.tileentity.TileEntityTFFlameJet;
import twilightforest.tileentity.TileEntityTFPoppingJet;
import twilightforest.tileentity.TileEntityTFSmoker;
import twilightforest.tileentity.TileEntityTFHydraSpawner;
import twilightforest.tileentity.TileEntityTFLichSpawner;
import twilightforest.tileentity.TileEntityTFNagaSpawner;
import twilightforest.tileentity.TileEntityTFCicada;
import twilightforest.tileentity.TileEntityTFFirefly;
import cpw.mods.fml.common.registry.LanguageRegistry;
import twilightforest.entity.EntityTFCharmEffect;
import twilightforest.entity.EntityTFSlimeProjectile;
import twilightforest.entity.EntityTFMoonwormShot;
import twilightforest.entity.EntityTFLichBomb;
import twilightforest.entity.EntityTFHydraMortar;
import twilightforest.entity.EntityTFTomeBolt;
import twilightforest.entity.EntityTFTwilightWandBolt;
import twilightforest.entity.EntityTFLichBolt;
import twilightforest.entity.EntityTFNatureBolt;
import cpw.mods.fml.common.registry.EntityRegistry;
import twilightforest.entity.EntityTFHydraHead;
import twilightforest.entity.EntityTFMobileFirefly;
import twilightforest.entity.EntityTFKingSpider;
import twilightforest.entity.EntityTFMistWolf;
import twilightforest.entity.EntityTFRedcapSapper;
import twilightforest.entity.EntityTFMazeSlime;
import twilightforest.entity.EntityTFPinchBeetle;
import twilightforest.entity.EntityTFSlimeBeetle;
import twilightforest.entity.EntityTFFireBeetle;
import twilightforest.entity.EntityTFMinoshroom;
import twilightforest.entity.EntityTFMinotaur;
import twilightforest.entity.EntityTFDeathTome;
import twilightforest.entity.EntityTFMosquitoSwarm;
import twilightforest.entity.EntityTFBoggard;
import twilightforest.entity.EntityTFKobold;
import twilightforest.entity.EntityTFQuestRam;
import twilightforest.entity.EntityTFRaven;
import twilightforest.entity.EntityTFBunny;
import twilightforest.entity.EntityTFSquirrel;
import twilightforest.entity.EntityTFTinyBird;
import twilightforest.entity.EntityTFLoyalZombie;
import twilightforest.entity.EntityTFLichMinion;
import twilightforest.entity.EntityTFPenguin;
import twilightforest.entity.EntityTFLich;
import twilightforest.entity.EntityTFHydra;
import twilightforest.entity.EntityTFHedgeSpider;
import twilightforest.entity.EntityTFWraith;
import twilightforest.entity.EntityTFHostileWolf;
import twilightforest.entity.EntityTFSkeletonDruid;
import twilightforest.entity.EntityTFNagaSegment;
import twilightforest.entity.EntityTFNaga;
import twilightforest.entity.EntityTFSwarmSpider;
import twilightforest.entity.EntityTFRedcap;
import twilightforest.entity.EntityTFDeer;
import twilightforest.entity.EntityTFBighorn;
import twilightforest.entity.EntityTFBoar;
import cpw.mods.fml.common.IScheduledTickHandler;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.common.network.IGuiHandler;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraftforge.common.DimensionManager;
import twilightforest.world.WorldProviderTwilightForest;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.IPlayerTracker;
import cpw.mods.fml.common.ICraftingHandler;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.AchievementPage;
import twilightforest.entity.TFCreatures;
import twilightforest.item.TFItems;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import twilightforest.block.TFBlocks;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.Mod;

@Mod(modid = "TwilightForest", name = "The Twilight Forest", version = "1.14.0")
@NetworkMod(channels = { "TwilightForest", "tfmagicmap", "tfmazemap" }, clientSideRequired = true, serverSideRequired = false, packetHandler = TFPacketHandler.class)
public class TwilightForestMod
{
    public static final String ID = "TwilightForest";
    public static final String VERSION = "1.14.0";
    public static int dimensionID;
    public static int idBlockFirefly;
    public static int idBlockPortal;
    public static int idBlockLog;
    public static int idBlockLeaves;
    public static int idBlockMazestone;
    public static int idBlockHedge;
    public static int idBlockBossSpawner;
    public static int idBlockFireflyJar;
    public static int idBlockPlant;
    public static int idBlockRoots;
    public static int idBlockCicada;
    public static int idBlockUncraftingTable;
    public static int idBlockFireJet;
    public static int idBlockNagastone;
    public static int idBlockSapling;
    public static int idBlockMagicLog;
    public static int idBlockMagicLeaves;
    public static int idBlockMoonworm;
    public static int idBlockMagicLogSpecial;
    public static int idBlockTowerWood;
    public static int idBlockTowerDevice;
    public static int idBlockTowerAntenna;
    public static int idItemNagaScale;
    public static int idItemPlateNaga;
    public static int idItemLegsNaga;
    public static int idItemScepterTwilight;
    public static int idItemScepterLifeDrain;
    public static int idItemScepterZombie;
    public static int idItemWandPacification;
    public static int idItemOreMeter;
    public static int idItemMagicMap;
    public static int idItemMazeMap;
    public static int idItemOreMap;
    public static int idItemFeather;
    public static int idItemMagicMapFocus;
    public static int idItemMazeMapFocus;
    public static int idItemLiveRoot;
    public static int idItemIronwoodRaw;
    public static int idItemIronwoodIngot;
    public static int idItemIronwoodHelm;
    public static int idItemIronwoodPlate;
    public static int idItemIronwoodLegs;
    public static int idItemIronwoodBoots;
    public static int idItemIronwoodSword;
    public static int idItemIronwoodShovel;
    public static int idItemIronwoodPick;
    public static int idItemIronwoodAxe;
    public static int idItemIronwoodHoe;
    public static int idItemTorchberries;
    public static int idItemSpawnEgg;
    public static int idItemVenisonRaw;
    public static int idItemVenisonCooked;
    public static int idItemHydraChops;
    public static int idItemFieryBlood;
    public static int idItemHydraTrophy;
    public static int idItemFieryIngot;
    public static int idItemFieryHelm;
    public static int idItemFieryPlate;
    public static int idItemFieryLegs;
    public static int idItemFieryBoots;
    public static int idItemFierySword;
    public static int idItemFieryPick;
    public static int idItemSteeleafIngot;
    public static int idItemSteeleafHelm;
    public static int idItemSteeleafPlate;
    public static int idItemSteeleafLegs;
    public static int idItemSteeleafBoots;
    public static int idItemSteeleafSword;
    public static int idItemSteeleafShovel;
    public static int idItemSteeleafPick;
    public static int idItemSteeleafAxe;
    public static int idItemSteeleafHoe;
    public static int idItemMinotaurAxe;
    public static int idItemMazebreakerPick;
    public static int idItemTransformPowder;
    public static int idItemMeefRaw;
    public static int idItemMeefSteak;
    public static int idItemMeefStroganoff;
    public static int idItemMazeWafer;
    public static int idItemEmptyMagicMap;
    public static int idItemEmptyMazeMap;
    public static int idItemEmptyOreMap;
    public static int idItemOreMagnet;
    public static int idItemCrumbleHorn;
    public static int idItemPeacockFan;
    public static int idItemMoonwormQueen;
    public static int idItemCharmOfLife1;
    public static int idItemCharmOfLife2;
    public static int idItemCharmOfKeeping1;
    public static int idItemCharmOfKeeping2;
    public static int idItemCharmOfKeeping3;
    public static boolean creatureCompatibility;
    public static boolean silentCicadas;
    public static boolean allowPortalsInOtherDimensions;
    public static int idMobWildBoar;
    public static int idMobBighornSheep;
    public static int idMobWildDeer;
    public static int idMobRedcap;
    public static int idMobSwarmSpider;
    public static int idMobNaga;
    public static int idMobNagaSegment;
    public static int idMobSkeletonDruid;
    public static int idMobHostileWolf;
    public static int idMobTwilightWraith;
    public static int idMobHedgeSpider;
    public static int idMobHydra;
    public static int idMobLich;
    public static int idMobPenguin;
    public static int idMobLichMinion;
    public static int idMobLoyalZombie;
    public static int idMobTinyBird;
    public static int idMobSquirrel;
    public static int idMobBunny;
    public static int idMobRaven;
    public static int idMobQuestRam;
    public static int idMobKobold;
    public static int idMobBoggard;
    public static int idMobMosquitoSwarm;
    public static int idMobDeathTome;
    public static int idMobMinotaur;
    public static int idMobMinoshroom;
    public static int idMobFireBeetle;
    public static int idMobSlimeBeetle;
    public static int idMobPinchBeetle;
    public static int idMobMazeSlime;
    public static int idMobRedcapSapper;
    public static int idMobMistWolf;
    public static int idMobKingSpider;
    public static int idMobFirefly;
    public static int idVehicleSpawnNatureBolt;
    public static int idVehicleSpawnLichBolt;
    public static int idVehicleSpawnTwilightWandBolt;
    public static int idVehicleSpawnTomeBolt;
    public static int idVehicleSpawnHydraMortar;
    public static int idVehicleSpawnLichBomb;
    public static int idVehicleSpawnMoonwormShot;
    public static int idVehicleSpawnSlimeBlob;
    public static int idVehicleSpawnCharmEffect;
    public static int idBiomeLake;
    public static int idBiomeTwilightForest;
    public static int idBiomeTwilightForestVariant;
    public static int idBiomeHighlands;
    public static int idBiomeMushrooms;
    public static int idBiomeSwamp;
    public static int idBiomeStream;
    public static int idBiomeSnowfield;
    public static int idBiomeGlacier;
    public static int idBiomeClearing;
    public static int idBiomeClearingBorder;
    public static int idBiomeLakeBorder;
    public static int idBiomeDeepMushrooms;
    public static int idBiomeMajorFeature;
    public static int idBiomeMinorFeature;
    public static int idBiomeDarkForest;
    public static int idBiomeEnchantedForest;
    public static int idBiomeFireSwamp;
    @Mod.Instance("TwilightForest")
    public static TwilightForestMod instance;
    @SidedProxy(clientSide = "twilightforest.client.TFClientProxy", serverSide = "twilightforest.TFCommonProxy")
    public static TFCommonProxy proxy;
    public static final TFEventListener eventListener;
    TFBlocks blocks;
    TFTickHandler tickHandler;
    
    public TwilightForestMod() {
        TwilightForestMod.instance = this;
    }
    
    @Mod.PreInit
    public void preInit(final FMLPreInitializationEvent event) {
        this.loadConfiguration(new Configuration(event.getSuggestedConfigurationFile()));
        new TFBlocks();
        new TFItems();
        new TFCreatures();
        this.registerCreatures();
        AchievementPage.registerAchievementPage((AchievementPage)new TFAchievementPage());
        try {
            Class.forName("net.minecraftforge.event.entity.EntityJoinWorldEvent", false, this.getClass().getClassLoader());
            MinecraftForge.EVENT_BUS.register((Object)TwilightForestMod.eventListener);
        }
        catch (ClassNotFoundException e) {
            System.err.println("Running an old version of forge.  Cannot initialize Twilight Forest event listener.  May be problematic.");
        }
        GameRegistry.registerCraftingHandler((ICraftingHandler)TwilightForestMod.eventListener);
        GameRegistry.registerPlayerTracker((IPlayerTracker)TwilightForestMod.eventListener);
        TwilightForestMod.proxy.doPreLoadRegistration();
    }
    
    @Mod.Init
    public void load(final FMLInitializationEvent evt) {
        DimensionManager.registerProviderType(TwilightForestMod.dimensionID, (Class)WorldProviderTwilightForest.class, false);
        DimensionManager.registerDimension(TwilightForestMod.dimensionID, TwilightForestMod.dimensionID);
        new TFRecipes();
        this.registerTileEntities();
        TwilightForestMod.proxy.doOnLoadRegistration();
        NetworkRegistry.instance().registerGuiHandler((Object)TwilightForestMod.instance, (IGuiHandler)TwilightForestMod.proxy);
        TickRegistry.registerScheduledTickHandler((IScheduledTickHandler)(this.tickHandler = new TFTickHandler()), Side.SERVER);
    }
    
    private void registerCreatures() {
        TFCreatures.registerTFCreature(EntityTFBoar.class, "Wild Boar", TwilightForestMod.idMobWildBoar, 8611131, 16773066);
        TFCreatures.registerTFCreature(EntityTFBighorn.class, "Bighorn Sheep", TwilightForestMod.idMobBighornSheep, 14405295, 14141297);
        TFCreatures.registerTFCreature(EntityTFDeer.class, "Wild Deer", TwilightForestMod.idMobWildDeer, 8080686, 4924445);
        TFCreatures.registerTFCreature(EntityTFRedcap.class, "Redcap", TwilightForestMod.idMobRedcap, 3881580, 11214356);
        TFCreatures.registerTFCreature(EntityTFSwarmSpider.class, "Swarm Spider", TwilightForestMod.idMobSwarmSpider, 3277358, 1516830);
        TFCreatures.registerTFCreature(EntityTFNaga.class, "Naga", TwilightForestMod.idMobNaga, 10801942, 1783819);
        TFCreatures.registerTFCreature(EntityTFNagaSegment.class, "Naga Segment", TwilightForestMod.idMobNagaSegment);
        TFCreatures.registerTFCreature(EntityTFSkeletonDruid.class, "Skeleton Druid", TwilightForestMod.idMobSkeletonDruid, 10724259, 2767639);
        TFCreatures.registerTFCreature(EntityTFHostileWolf.class, "Hostile Wolf", TwilightForestMod.idMobHostileWolf, 14144467, 11214356);
        TFCreatures.registerTFCreature(EntityTFWraith.class, "Twilight Wraith", TwilightForestMod.idMobTwilightWraith, 5263440, 8618883);
        TFCreatures.registerTFCreature(EntityTFHedgeSpider.class, "Hedge Spider", TwilightForestMod.idMobHedgeSpider, 2318099, 5645907);
        TFCreatures.registerTFCreature(EntityTFHydra.class, "Hydra", TwilightForestMod.idMobHydra, 1321280, 2719851);
        TFCreatures.registerTFCreature(EntityTFLich.class, "Twilight Lich", TwilightForestMod.idMobLich, 11314313, 3540082);
        TFCreatures.registerTFCreature(EntityTFPenguin.class, "Penguin", TwilightForestMod.idMobPenguin, 1185051, 16379346);
        TFCreatures.registerTFCreature(EntityTFLichMinion.class, "Lich Minion", TwilightForestMod.idMobLichMinion);
        TFCreatures.registerTFCreature(EntityTFLoyalZombie.class, "Loyal Zombie", TwilightForestMod.idMobLoyalZombie);
        TFCreatures.registerTFCreature(EntityTFTinyBird.class, "Tiny Bird", TwilightForestMod.idMobTinyBird, 3386077, 1149166);
        TFCreatures.registerTFCreature(EntityTFSquirrel.class, "Forest Squirrel", TwilightForestMod.idMobSquirrel, 9457426, 15658734);
        TFCreatures.registerTFCreature(EntityTFBunny.class, "Forest Bunny", TwilightForestMod.idMobBunny, 16711406, 13413017);
        TFCreatures.registerTFCreature(EntityTFRaven.class, "Forest Raven", TwilightForestMod.idMobRaven, 17, 2236979);
        TFCreatures.registerTFCreature(EntityTFQuestRam.class, "Questing Ram", TwilightForestMod.idMobQuestRam);
        TFCreatures.registerTFCreature(EntityTFKobold.class, "Twilight Kobold", TwilightForestMod.idMobKobold, 3612822, 9002267);
        TFCreatures.registerTFCreature(EntityTFBoggard.class, "Boggard", TwilightForestMod.idMobBoggard);
        TFCreatures.registerTFCreature(EntityTFMosquitoSwarm.class, "Mosquito Swarm", TwilightForestMod.idMobMosquitoSwarm, 526596, 2961185);
        TFCreatures.registerTFCreature(EntityTFDeathTome.class, "Death Tome", TwilightForestMod.idMobDeathTome, 7818786, 14405054);
        TFCreatures.registerTFCreature(EntityTFMinotaur.class, "Minotaur", TwilightForestMod.idMobMinotaur, 4141092, 11173222);
        TFCreatures.registerTFCreature(EntityTFMinoshroom.class, "Minoshroom", TwilightForestMod.idMobMinoshroom, 11014162, 11173222);
        TFCreatures.registerTFCreature(EntityTFFireBeetle.class, "Fire Beetle", TwilightForestMod.idMobFireBeetle, 1903360, 13332261);
        TFCreatures.registerTFCreature(EntityTFSlimeBeetle.class, "Slime Beetle", TwilightForestMod.idMobSlimeBeetle, 792070, 6334284);
        TFCreatures.registerTFCreature(EntityTFPinchBeetle.class, "Pinch Beetle", TwilightForestMod.idMobPinchBeetle, 12358439, 2364937);
        TFCreatures.registerTFCreature(EntityTFMazeSlime.class, "Maze Slime", TwilightForestMod.idMobMazeSlime, 10724259, 2767639);
        TFCreatures.registerTFCreature(EntityTFRedcapSapper.class, "Redcap Sapper", TwilightForestMod.idMobRedcapSapper, 5725473, 11214356);
        TFCreatures.registerTFCreature(EntityTFMistWolf.class, "Mist Wolf", TwilightForestMod.idMobMistWolf, 3806225, 14862474);
        TFCreatures.registerTFCreature(EntityTFKingSpider.class, "King Spider", TwilightForestMod.idMobKingSpider, 2318099, 5645907);
        TFCreatures.registerTFCreature(EntityTFMobileFirefly.class, "Firefly", TwilightForestMod.idMobFirefly, 10801942, 1783819);
        EntityRegistry.registerModEntity((Class)EntityTFHydraHead.class, "HydraHead", 11, (Object)this, 150, 3, false);
        EntityRegistry.registerModEntity((Class)EntityTFNatureBolt.class, "tfnaturebolt", TwilightForestMod.idVehicleSpawnNatureBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFLichBolt.class, "tflichbolt", TwilightForestMod.idVehicleSpawnLichBolt, (Object)this, 150, 2, true);
        EntityRegistry.registerModEntity((Class)EntityTFTwilightWandBolt.class, "tftwilightwandbolt", TwilightForestMod.idVehicleSpawnTwilightWandBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFTomeBolt.class, "tftomebolt", TwilightForestMod.idVehicleSpawnTomeBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFHydraMortar.class, "tfhydramortar", TwilightForestMod.idVehicleSpawnHydraMortar, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFLichBomb.class, "tflichbomb", TwilightForestMod.idVehicleSpawnLichBomb, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFMoonwormShot.class, "tfmoonwormshot", TwilightForestMod.idVehicleSpawnMoonwormShot, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFSlimeProjectile.class, "tfslimeblob", TwilightForestMod.idVehicleSpawnSlimeBlob, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFCharmEffect.class, "tfcharmeffect", TwilightForestMod.idVehicleSpawnCharmEffect, (Object)this, 80, 3, true);
        this.addEntityName("Wild Boar", "Wild Boar");
        this.addEntityName("Bighorn Sheep", "Bighorn Sheep");
        this.addEntityName("Wild Deer", "Wild Deer");
        this.addEntityName("Redcap", "Redcap");
        this.addEntityName("Swarm Spider", "Swarm Spider");
        this.addEntityName("Naga", "Naga");
        this.addEntityName("Naga Segment", "Naga Segment");
        this.addEntityName("Skeleton Druid", "Skeleton Druid");
        this.addEntityName("Hostile Wolf", "Hostile Wolf");
        this.addEntityName("Twilight Wraith", "Twilight Wraith");
        this.addEntityName("Hedge Spider", "Hedge Spider");
        this.addEntityName("Hydra", "Hydra");
        this.addEntityName("HydraHead", "Hydra Head");
        this.addEntityName("Twilight Lich", "Twilight Lich");
        this.addEntityName("Penguin", "Penguin");
        this.addEntityName("Tiny Bird", "Tiny Bird");
        this.addEntityName("Forest Squirrel", "Forest Squirrel");
        this.addEntityName("Forest Bunny", "Forest Bunny");
        this.addEntityName("Forest Raven", "Forest Raven");
        this.addEntityName("Questing Ram", "Questing Ram");
        this.addEntityName("Twilight Kobold", "Kobold");
        this.addEntityName("Boggard", "Boggard [NYI]");
        this.addEntityName("Lich Minion", "Lich Minion");
        this.addEntityName("Loyal Zombie", "Loyal Zombie");
        this.addEntityName("Naga2", "Naga 2");
        this.addEntityName("Mosquito Swarm", "Mosquito Swarm");
        this.addEntityName("Death Tome", "Death Tome");
        this.addEntityName("Minotaur", "Minotaur");
        this.addEntityName("Minoshroom", "Minoshroom");
        this.addEntityName("Fire Beetle", "Fire Beetle");
        this.addEntityName("Slime Beetle", "Slime Beetle");
        this.addEntityName("Pinch Beetle", "Pinch Beetle");
        this.addEntityName("Maze Slime", "Maze Slime");
        this.addEntityName("Redcap Sapper", "Redcap Sapper");
        this.addEntityName("Mist Wolf", "Wolf of the Mists [WIP]");
        this.addEntityName("King Spider", "King Spider [WIP]");
        this.addEntityName("Firefly", "Firefly");
    }
    
    public void addEntityName(final String gameName, final String displayName) {
        LanguageRegistry.instance().addStringLocalization("entity." + gameName + ".name", "en_US", displayName);
        LanguageRegistry.instance().addStringLocalization("entity.TwilightForest." + gameName + ".name", "en_US", displayName);
    }
    
    private void registerTileEntities() {
        GameRegistry.registerTileEntity((Class)TileEntityTFFirefly.class, "Firefly");
        GameRegistry.registerTileEntity((Class)TileEntityTFCicada.class, "Cicada");
        GameRegistry.registerTileEntity((Class)TileEntityTFNagaSpawner.class, "Naga Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFLichSpawner.class, "Lich Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFHydraSpawner.class, "Hydra Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFSmoker.class, "Swamp Smoker");
        GameRegistry.registerTileEntity((Class)TileEntityTFPoppingJet.class, "Popping Flame Jet");
        GameRegistry.registerTileEntity((Class)TileEntityTFFlameJet.class, "Lit Flame Jet");
        GameRegistry.registerTileEntity((Class)TileEntityTFMoonworm.class, "Moonworm");
    }
    
    private void loadConfiguration(final Configuration configFile) {
        configFile.load();
        TwilightForestMod.dimensionID = Integer.parseInt(configFile.get("dimension", "dimensionID", 7).value);
        configFile.get("dimension", "dimensionID", 7).comment = "What ID number to assign to the Twilight Forest dimension.  Change if you are having conflicts with another mod.";
        TwilightForestMod.silentCicadas = Boolean.parseBoolean(configFile.get("general", "SilentCicadas", false).value);
        configFile.get("general", "SilentCicadas", false).comment = "Make cicadas silent  for those having sound library problems, or otherwise finding them annoying";
        TwilightForestMod.allowPortalsInOtherDimensions = Boolean.parseBoolean(configFile.get("general", "AllowPortalsInOtherDimensions", false).value);
        configFile.get("general", "AllowPortalsInOtherDimensions", false).comment = "Allow portals to the Twilight Forest to be made outside of dimension 0.  May be considered an exploit.";
        TwilightForestMod.idBlockFirefly = Integer.parseInt(configFile.getBlock("Critter", 2160).value);
        TwilightForestMod.idBlockPortal = Integer.parseInt(configFile.getBlock("Portal", 2162).value);
        TwilightForestMod.idBlockLog = Integer.parseInt(configFile.getBlock("Log", 2163).value);
        TwilightForestMod.idBlockLeaves = Integer.parseInt(configFile.getBlock("Leaves", 2164).value);
        TwilightForestMod.idBlockMazestone = Integer.parseInt(configFile.getBlock("Mazestone", 2165).value);
        TwilightForestMod.idBlockHedge = Integer.parseInt(configFile.getBlock("Hedge", 2166).value);
        TwilightForestMod.idBlockBossSpawner = Integer.parseInt(configFile.getBlock("BossSpawner", 2167).value);
        TwilightForestMod.idBlockFireflyJar = Integer.parseInt(configFile.getBlock("FireflyJar", 2168).value);
        TwilightForestMod.idBlockPlant = Integer.parseInt(configFile.getBlock("Plant", 2169).value);
        TwilightForestMod.idBlockRoots = Integer.parseInt(configFile.getBlock("Roots", 2170).value);
        TwilightForestMod.idBlockCicada = Integer.parseInt(configFile.getBlock("Cicada", 2171).value);
        TwilightForestMod.idBlockUncraftingTable = Integer.parseInt(configFile.getBlock("UncraftingTable", 2172).value);
        TwilightForestMod.idBlockFireJet = Integer.parseInt(configFile.getBlock("FireJet", 2173).value);
        TwilightForestMod.idBlockNagastone = Integer.parseInt(configFile.getBlock("Nagastone", 2174).value);
        TwilightForestMod.idBlockSapling = Integer.parseInt(configFile.getBlock("Sapling", 2175).value);
        TwilightForestMod.idBlockMagicLog = Integer.parseInt(configFile.getBlock("MagicLog", 2176).value);
        TwilightForestMod.idBlockMagicLeaves = Integer.parseInt(configFile.getBlock("MagicLeaves", 2177).value);
        TwilightForestMod.idBlockMoonworm = Integer.parseInt(configFile.getBlock("Moonworm", 2178).value);
        TwilightForestMod.idBlockMagicLogSpecial = Integer.parseInt(configFile.getBlock("MagicLogSpecial", 2179).value);
        TwilightForestMod.idBlockTowerWood = Integer.parseInt(configFile.getBlock("TowerWood", 2180).value);
        TwilightForestMod.idBlockTowerDevice = Integer.parseInt(configFile.getBlock("TowerDevice", 2181).value);
        TwilightForestMod.idBlockTowerAntenna = Integer.parseInt(configFile.getBlock("TowerAntenna", 2182).value);
        TwilightForestMod.idItemNagaScale = Integer.parseInt(configFile.getItem("NagaScale", 27701).value);
        TwilightForestMod.idItemPlateNaga = Integer.parseInt(configFile.getItem("PlateNaga", 27702).value);
        TwilightForestMod.idItemLegsNaga = Integer.parseInt(configFile.getItem("LegsNaga", 27703).value);
        TwilightForestMod.idItemScepterTwilight = Integer.parseInt(configFile.getItem("ScepterTwilight", 27704).value);
        TwilightForestMod.idItemScepterLifeDrain = Integer.parseInt(configFile.getItem("ScepterLifeDrain", 27705).value);
        TwilightForestMod.idItemScepterZombie = Integer.parseInt(configFile.getItem("ScepterZombie", 27706).value);
        TwilightForestMod.idItemWandPacification = Integer.parseInt(configFile.getItem("WandPacification", 27707).value);
        TwilightForestMod.idItemOreMeter = Integer.parseInt(configFile.getItem("OreMeter", 27708).value);
        TwilightForestMod.idItemMagicMap = Integer.parseInt(configFile.getItem("MagicMap", 27709).value);
        TwilightForestMod.idItemMazeMap = Integer.parseInt(configFile.getItem("MazeMap", 27710).value);
        TwilightForestMod.idItemOreMap = Integer.parseInt(configFile.getItem("OreMap", 27711).value);
        TwilightForestMod.idItemFeather = Integer.parseInt(configFile.getItem("Feather", 27712).value);
        TwilightForestMod.idItemMagicMapFocus = Integer.parseInt(configFile.getItem("MagicMapFocus", 27713).value);
        TwilightForestMod.idItemMazeMapFocus = Integer.parseInt(configFile.getItem("MazeMapFocus", 27714).value);
        TwilightForestMod.idItemLiveRoot = Integer.parseInt(configFile.getItem("LiveRoot", 27716).value);
        TwilightForestMod.idItemIronwoodRaw = Integer.parseInt(configFile.getItem("IronwoodRaw", 27717).value);
        TwilightForestMod.idItemIronwoodIngot = Integer.parseInt(configFile.getItem("IronwoodIngot", 27718).value);
        TwilightForestMod.idItemIronwoodHelm = Integer.parseInt(configFile.getItem("IronwoodHelm", 27719).value);
        TwilightForestMod.idItemIronwoodPlate = Integer.parseInt(configFile.getItem("IronwoodPlate", 27720).value);
        TwilightForestMod.idItemIronwoodLegs = Integer.parseInt(configFile.getItem("IronwoodLegs", 27721).value);
        TwilightForestMod.idItemIronwoodBoots = Integer.parseInt(configFile.getItem("IronwoodBoots", 27722).value);
        TwilightForestMod.idItemIronwoodSword = Integer.parseInt(configFile.getItem("IronwoodSword", 27723).value);
        TwilightForestMod.idItemIronwoodShovel = Integer.parseInt(configFile.getItem("IronwoodShovel", 27724).value);
        TwilightForestMod.idItemIronwoodPick = Integer.parseInt(configFile.getItem("IronwoodPick", 27725).value);
        TwilightForestMod.idItemIronwoodAxe = Integer.parseInt(configFile.getItem("IronwoodAxe", 27726).value);
        TwilightForestMod.idItemIronwoodHoe = Integer.parseInt(configFile.getItem("IronwoodHoe", 27727).value);
        TwilightForestMod.idItemTorchberries = Integer.parseInt(configFile.getItem("Torchberries", 27728).value);
        TwilightForestMod.idItemSpawnEgg = Integer.parseInt(configFile.getItem("SpawnEgg", 27729).value);
        TwilightForestMod.idItemVenisonRaw = Integer.parseInt(configFile.getItem("VenisonRaw", 27730).value);
        TwilightForestMod.idItemVenisonCooked = Integer.parseInt(configFile.getItem("VenisonCooked", 27731).value);
        TwilightForestMod.idItemHydraChops = Integer.parseInt(configFile.getItem("HydraChops", 27732).value);
        TwilightForestMod.idItemFieryBlood = Integer.parseInt(configFile.getItem("FieryBlood", 27733).value);
        TwilightForestMod.idItemHydraTrophy = Integer.parseInt(configFile.getItem("HydraTrophy", 27734).value);
        TwilightForestMod.idItemFieryIngot = Integer.parseInt(configFile.getItem("FieryIngot", 27735).value);
        TwilightForestMod.idItemFieryHelm = Integer.parseInt(configFile.getItem("FieryHelm", 27736).value);
        TwilightForestMod.idItemFieryPlate = Integer.parseInt(configFile.getItem("FieryPlate", 27737).value);
        TwilightForestMod.idItemFieryLegs = Integer.parseInt(configFile.getItem("FieryLegs", 27738).value);
        TwilightForestMod.idItemFieryBoots = Integer.parseInt(configFile.getItem("FieryBoots", 27739).value);
        TwilightForestMod.idItemFierySword = Integer.parseInt(configFile.getItem("FierySword", 27740).value);
        TwilightForestMod.idItemFieryPick = Integer.parseInt(configFile.getItem("FieryPick", 27741).value);
        TwilightForestMod.idItemSteeleafIngot = Integer.parseInt(configFile.getItem("SteeleafIngot", 27742).value);
        TwilightForestMod.idItemSteeleafHelm = Integer.parseInt(configFile.getItem("SteeleafHelm", 27743).value);
        TwilightForestMod.idItemSteeleafPlate = Integer.parseInt(configFile.getItem("SteeleafPlate", 27744).value);
        TwilightForestMod.idItemSteeleafLegs = Integer.parseInt(configFile.getItem("SteeleafLegs", 27745).value);
        TwilightForestMod.idItemSteeleafBoots = Integer.parseInt(configFile.getItem("SteeleafBoots", 27746).value);
        TwilightForestMod.idItemSteeleafSword = Integer.parseInt(configFile.getItem("SteeleafSword", 27747).value);
        TwilightForestMod.idItemSteeleafShovel = Integer.parseInt(configFile.getItem("SteeleafShovel", 27748).value);
        TwilightForestMod.idItemSteeleafPick = Integer.parseInt(configFile.getItem("SteeleafPick", 27749).value);
        TwilightForestMod.idItemSteeleafAxe = Integer.parseInt(configFile.getItem("SteeleafAxe", 27750).value);
        TwilightForestMod.idItemSteeleafHoe = Integer.parseInt(configFile.getItem("SteeleafHoe", 27751).value);
        TwilightForestMod.idItemMinotaurAxe = Integer.parseInt(configFile.getItem("MinotaurAxe", 27752).value);
        TwilightForestMod.idItemMazebreakerPick = Integer.parseInt(configFile.getItem("MazebreakerPick", 27753).value);
        TwilightForestMod.idItemTransformPowder = Integer.parseInt(configFile.getItem("TransformPowder", 27754).value);
        TwilightForestMod.idItemMeefRaw = Integer.parseInt(configFile.getItem("MeefRaw", 27755).value);
        TwilightForestMod.idItemMeefSteak = Integer.parseInt(configFile.getItem("MeefSteak", 27756).value);
        TwilightForestMod.idItemMeefStroganoff = Integer.parseInt(configFile.getItem("MeefStroganoff", 27757).value);
        TwilightForestMod.idItemMazeWafer = Integer.parseInt(configFile.getItem("MazeWafer", 27758).value);
        TwilightForestMod.idItemEmptyMagicMap = Integer.parseInt(configFile.getItem("EmptyMagicMap", 27759).value);
        TwilightForestMod.idItemEmptyMazeMap = Integer.parseInt(configFile.getItem("EmptyMazeMap", 27760).value);
        TwilightForestMod.idItemEmptyOreMap = Integer.parseInt(configFile.getItem("EmptyOreMap", 27761).value);
        TwilightForestMod.idItemOreMagnet = Integer.parseInt(configFile.getItem("OreMagnet", 27762).value);
        TwilightForestMod.idItemCrumbleHorn = Integer.parseInt(configFile.getItem("CrumbleHorn", 27763).value);
        TwilightForestMod.idItemPeacockFan = Integer.parseInt(configFile.getItem("PeacockFan", 27764).value);
        TwilightForestMod.idItemMoonwormQueen = Integer.parseInt(configFile.getItem("MoonwormQueen", 27765).value);
        TwilightForestMod.idItemCharmOfLife1 = Integer.parseInt(configFile.getItem("CharmOfLife1", 27766).value);
        TwilightForestMod.idItemCharmOfLife2 = Integer.parseInt(configFile.getItem("CharmOfLife2", 27767).value);
        TwilightForestMod.idItemCharmOfKeeping2 = Integer.parseInt(configFile.getItem("CharmOfKeeping2", 27768).value);
        TwilightForestMod.idItemCharmOfKeeping3 = Integer.parseInt(configFile.getItem("CharmOfKeeping3", 27769).value);
        TwilightForestMod.idItemCharmOfKeeping1 = Integer.parseInt(configFile.getItem("CharmOfKeeping1", 27770).value);
        TwilightForestMod.creatureCompatibility = Boolean.parseBoolean(configFile.get("general", "CreatureCompatibility", false).value);
        configFile.get("general", "CreatureCompatibility", false).comment = "Allows creature and spawner compatibility with very old maps.  It is not recommended to change this.";
        if (TwilightForestMod.creatureCompatibility) {
            TwilightForestMod.idMobWildBoar = Integer.parseInt(configFile.get("creature", "entity.id.WildBoar", 177).value);
            TwilightForestMod.idMobBighornSheep = Integer.parseInt(configFile.get("creature", "entity.id.BighornSheep", 178).value);
            TwilightForestMod.idMobWildDeer = Integer.parseInt(configFile.get("creature", "entity.id.WildDeer", 179).value);
            TwilightForestMod.idMobRedcap = Integer.parseInt(configFile.get("creature", "entity.id.Redcap", 180).value);
            TwilightForestMod.idMobSwarmSpider = Integer.parseInt(configFile.get("creature", "entity.id.SwarmSpider", 181).value);
            TwilightForestMod.idMobNaga = Integer.parseInt(configFile.get("creature", "entity.id.Naga", 182).value);
            TwilightForestMod.idMobNagaSegment = Integer.parseInt(configFile.get("creature", "entity.id.NagaSegment", 183).value);
            TwilightForestMod.idMobSkeletonDruid = Integer.parseInt(configFile.get("creature", "entity.id.SkeletonDruid", 184).value);
            TwilightForestMod.idMobHostileWolf = Integer.parseInt(configFile.get("creature", "entity.id.HostileWolf", 185).value);
            TwilightForestMod.idMobTwilightWraith = Integer.parseInt(configFile.get("creature", "entity.id.TwilightWraith", 186).value);
            TwilightForestMod.idMobHedgeSpider = Integer.parseInt(configFile.get("creature", "entity.id.HedgeSpider", 187).value);
            TwilightForestMod.idMobHydra = Integer.parseInt(configFile.get("creature", "entity.id.Hydra", 189).value);
            TwilightForestMod.idMobLich = Integer.parseInt(configFile.get("creature", "entity.id.Lich", 190).value);
            TwilightForestMod.idMobPenguin = Integer.parseInt(configFile.get("creature", "entity.id.Penguin", 191).value);
            TwilightForestMod.idMobLichMinion = Integer.parseInt(configFile.get("creature", "entity.id.LichMinion", 192).value);
            TwilightForestMod.idMobLoyalZombie = Integer.parseInt(configFile.get("creature", "entity.id.LoyalZombie", 193).value);
            TwilightForestMod.idMobTinyBird = Integer.parseInt(configFile.get("creature", "entity.id.TinyBird", 194).value);
            TwilightForestMod.idMobSquirrel = Integer.parseInt(configFile.get("creature", "entity.id.Squirrel", 195).value);
            TwilightForestMod.idMobBunny = Integer.parseInt(configFile.get("creature", "entity.id.Bunny", 196).value);
            TwilightForestMod.idMobRaven = Integer.parseInt(configFile.get("creature", "entity.id.Raven", 197).value);
            TwilightForestMod.idMobQuestRam = Integer.parseInt(configFile.get("creature", "entity.id.QuestRam", 198).value);
            TwilightForestMod.idMobKobold = Integer.parseInt(configFile.get("creature", "entity.id.Kobold", 199).value);
            TwilightForestMod.idMobBoggard = Integer.parseInt(configFile.get("creature", "entity.id.Boggard", 201).value);
            TwilightForestMod.idMobMosquitoSwarm = Integer.parseInt(configFile.get("creature", "entity.id.MosquitoSwarm", 202).value);
            TwilightForestMod.idMobDeathTome = Integer.parseInt(configFile.get("creature", "entity.id.DeathTome", 203).value);
            TwilightForestMod.idMobMinotaur = Integer.parseInt(configFile.get("creature", "entity.id.Minotaur", 204).value);
            TwilightForestMod.idMobMinoshroom = Integer.parseInt(configFile.get("creature", "entity.id.Minoshroom", 205).value);
            TwilightForestMod.idMobFireBeetle = Integer.parseInt(configFile.get("creature", "entity.id.FireBeetle", 206).value);
            TwilightForestMod.idMobSlimeBeetle = Integer.parseInt(configFile.get("creature", "entity.id.SlimeBeetle", 207).value);
            TwilightForestMod.idMobPinchBeetle = Integer.parseInt(configFile.get("creature", "entity.id.PinchBeetle", 208).value);
            TwilightForestMod.idMobMazeSlime = Integer.parseInt(configFile.get("creature", "entity.id.MazeSlime", 209).value);
            TwilightForestMod.idMobRedcapSapper = Integer.parseInt(configFile.get("creature", "entity.id.RedcapSapper", 210).value);
            TwilightForestMod.idMobMistWolf = Integer.parseInt(configFile.get("creature", "entity.id.MistWolf", 211).value);
            TwilightForestMod.idMobKingSpider = Integer.parseInt(configFile.get("creature", "entity.id.KingSpider", 212).value);
        }
        else {
            TwilightForestMod.idMobWildBoar = 177;
            TwilightForestMod.idMobBighornSheep = 178;
            TwilightForestMod.idMobWildDeer = 179;
            TwilightForestMod.idMobRedcap = 180;
            TwilightForestMod.idMobSwarmSpider = 181;
            TwilightForestMod.idMobNaga = 182;
            TwilightForestMod.idMobNagaSegment = 183;
            TwilightForestMod.idMobSkeletonDruid = 184;
            TwilightForestMod.idMobHostileWolf = 185;
            TwilightForestMod.idMobTwilightWraith = 186;
            TwilightForestMod.idMobHedgeSpider = 187;
            TwilightForestMod.idMobHydra = 189;
            TwilightForestMod.idMobLich = 190;
            TwilightForestMod.idMobPenguin = 191;
            TwilightForestMod.idMobLichMinion = 192;
            TwilightForestMod.idMobLoyalZombie = 193;
            TwilightForestMod.idMobTinyBird = 194;
            TwilightForestMod.idMobSquirrel = 195;
            TwilightForestMod.idMobBunny = 196;
            TwilightForestMod.idMobRaven = 197;
            TwilightForestMod.idMobQuestRam = 198;
            TwilightForestMod.idMobKobold = 199;
            TwilightForestMod.idMobBoggard = 201;
            TwilightForestMod.idMobMosquitoSwarm = 202;
            TwilightForestMod.idMobDeathTome = 203;
            TwilightForestMod.idMobMinotaur = 204;
            TwilightForestMod.idMobMinoshroom = 205;
            TwilightForestMod.idMobFireBeetle = 206;
            TwilightForestMod.idMobSlimeBeetle = 207;
            TwilightForestMod.idMobPinchBeetle = 208;
            TwilightForestMod.idMobMazeSlime = 209;
            TwilightForestMod.idMobRedcapSapper = 210;
            TwilightForestMod.idMobMistWolf = 211;
            TwilightForestMod.idMobKingSpider = 212;
        }
        TwilightForestMod.idBiomeLake = Integer.parseInt(configFile.get("biome", "biome.id.Lake", 70).value);
        TwilightForestMod.idBiomeTwilightForest = Integer.parseInt(configFile.get("biome", "biome.id.TwilightForest", 71).value);
        TwilightForestMod.idBiomeTwilightForestVariant = Integer.parseInt(configFile.get("biome", "biome.id.TwilightForestVariant", 72).value);
        TwilightForestMod.idBiomeHighlands = Integer.parseInt(configFile.get("biome", "biome.id.Highlands", 73).value);
        TwilightForestMod.idBiomeMushrooms = Integer.parseInt(configFile.get("biome", "biome.id.Mushrooms", 74).value);
        TwilightForestMod.idBiomeSwamp = Integer.parseInt(configFile.get("biome", "biome.id.Swamp", 75).value);
        TwilightForestMod.idBiomeStream = Integer.parseInt(configFile.get("biome", "biome.id.Stream", 76).value);
        TwilightForestMod.idBiomeSnowfield = Integer.parseInt(configFile.get("biome", "biome.id.Snowfield", 77).value);
        TwilightForestMod.idBiomeGlacier = Integer.parseInt(configFile.get("biome", "biome.id.Glacier", 78).value);
        TwilightForestMod.idBiomeClearing = Integer.parseInt(configFile.get("biome", "biome.id.Clearing", 79).value);
        TwilightForestMod.idBiomeClearingBorder = Integer.parseInt(configFile.get("biome", "biome.id.ClearingBorder", 80).value);
        TwilightForestMod.idBiomeLakeBorder = Integer.parseInt(configFile.get("biome", "biome.id.LakeBorder", 81).value);
        TwilightForestMod.idBiomeDeepMushrooms = Integer.parseInt(configFile.get("biome", "biome.id.DeepMushrooms", 82).value);
        TwilightForestMod.idBiomeMajorFeature = Integer.parseInt(configFile.get("biome", "biome.id.MajorFeature", 83).value);
        TwilightForestMod.idBiomeMinorFeature = Integer.parseInt(configFile.get("biome", "biome.id.MinorFeature", 84).value);
        TwilightForestMod.idBiomeDarkForest = Integer.parseInt(configFile.get("biome", "biome.id.DarkForest", 85).value);
        TwilightForestMod.idBiomeEnchantedForest = Integer.parseInt(configFile.get("biome", "biome.id.EnchantedForest", 86).value);
        TwilightForestMod.idBiomeFireSwamp = Integer.parseInt(configFile.get("biome", "biome.id.FireSwamp", 87).value);
        configFile.save();
    }
    
    static {
        TwilightForestMod.idVehicleSpawnNatureBolt = 1;
        TwilightForestMod.idVehicleSpawnLichBolt = 2;
        TwilightForestMod.idVehicleSpawnTwilightWandBolt = 3;
        TwilightForestMod.idVehicleSpawnTomeBolt = 4;
        TwilightForestMod.idVehicleSpawnHydraMortar = 5;
        TwilightForestMod.idVehicleSpawnLichBomb = 6;
        TwilightForestMod.idVehicleSpawnMoonwormShot = 7;
        TwilightForestMod.idVehicleSpawnSlimeBlob = 8;
        TwilightForestMod.idVehicleSpawnCharmEffect = 9;
        eventListener = new TFEventListener();
    }
}
