// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest;

import twilightforest.item.BehaviorTFMobEggDispense;
import net.minecraft.block.BlockDispenser;
import net.minecraft.server.MinecraftServer;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import twilightforest.tileentity.TileEntityTFKnightPhantomsSpawner;
import twilightforest.tileentity.TileEntityTFCReactorActive;
import twilightforest.tileentity.TileEntityTFGhastTrapActive;
import twilightforest.tileentity.TileEntityTFGhastTrapInactive;
import twilightforest.tileentity.TileEntityTFTowerBossSpawner;
import twilightforest.tileentity.TileEntityTFTrophy;
import twilightforest.tileentity.TileEntityTFReverter;
import twilightforest.tileentity.TileEntityTFTowerBuilder;
import twilightforest.tileentity.TileEntityTFMoonworm;
import twilightforest.tileentity.TileEntityTFFlameJet;
import twilightforest.tileentity.TileEntityTFPoppingJet;
import twilightforest.tileentity.TileEntityTFSmoker;
import twilightforest.tileentity.TileEntityTFHydraSpawner;
import twilightforest.tileentity.TileEntityTFLichSpawner;
import twilightforest.tileentity.TileEntityTFNagaSpawner;
import twilightforest.tileentity.TileEntityTFCicada;
import twilightforest.tileentity.TileEntityTFFirefly;
import twilightforest.entity.EntityTFThrownPick;
import twilightforest.entity.EntityTFThrownAxe;
import twilightforest.entity.EntityTFCharmEffect;
import twilightforest.entity.EntityTFSlimeProjectile;
import twilightforest.entity.EntityTFMoonwormShot;
import twilightforest.entity.EntityTFLichBomb;
import twilightforest.entity.EntityTFHydraMortar;
import twilightforest.entity.EntityTFTomeBolt;
import twilightforest.entity.EntityTFTwilightWandBolt;
import twilightforest.entity.EntityTFLichBolt;
import twilightforest.entity.EntityTFNatureBolt;
import cpw.mods.fml.common.registry.EntityRegistry;
import twilightforest.entity.EntityTFHydraHead;
import twilightforest.entity.EntityTFKnightPhantom;
import twilightforest.entity.EntityTFHelmetCrab;
import twilightforest.entity.EntityTFGoblinKnightLower;
import twilightforest.entity.EntityTFGoblinKnightUpper;
import twilightforest.entity.EntityTFBlockGoblin;
import twilightforest.entity.EntityTFUrGhast;
import twilightforest.entity.EntityTFTowerBroodling;
import twilightforest.entity.EntityTFTowerTermite;
import twilightforest.entity.EntityTFTowerGolem;
import twilightforest.entity.EntityTFTowerGhast;
import twilightforest.entity.EntityTFMiniGhast;
import twilightforest.entity.passive.EntityTFMobileFirefly;
import twilightforest.entity.EntityTFKingSpider;
import twilightforest.entity.EntityTFMistWolf;
import twilightforest.entity.EntityTFRedcapSapper;
import twilightforest.entity.EntityTFMazeSlime;
import twilightforest.entity.EntityTFPinchBeetle;
import twilightforest.entity.EntityTFSlimeBeetle;
import twilightforest.entity.EntityTFFireBeetle;
import twilightforest.entity.EntityTFMinoshroom;
import twilightforest.entity.EntityTFMinotaur;
import twilightforest.entity.EntityTFDeathTome;
import twilightforest.entity.EntityTFMosquitoSwarm;
import twilightforest.entity.EntityTFBoggard;
import twilightforest.entity.EntityTFKobold;
import twilightforest.entity.passive.EntityTFQuestRam;
import twilightforest.entity.passive.EntityTFRaven;
import twilightforest.entity.passive.EntityTFBunny;
import twilightforest.entity.passive.EntityTFSquirrel;
import twilightforest.entity.passive.EntityTFTinyBird;
import twilightforest.entity.EntityTFLoyalZombie;
import twilightforest.entity.EntityTFLichMinion;
import twilightforest.entity.passive.EntityTFPenguin;
import twilightforest.entity.EntityTFLich;
import twilightforest.entity.EntityTFHydra;
import twilightforest.entity.EntityTFHedgeSpider;
import twilightforest.entity.EntityTFWraith;
import twilightforest.entity.EntityTFHostileWolf;
import twilightforest.entity.EntityTFSkeletonDruid;
import twilightforest.entity.EntityTFNaga;
import twilightforest.entity.EntityTFSwarmSpider;
import twilightforest.entity.EntityTFRedcap;
import twilightforest.entity.passive.EntityTFDeer;
import twilightforest.entity.passive.EntityTFBighorn;
import net.minecraft.entity.Entity;
import twilightforest.entity.passive.EntityTFBoar;
import net.minecraft.command.ICommand;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import twilightforest.biomes.TFBiomeBase;
import net.minecraftforge.common.DimensionManager;
import twilightforest.world.WorldProviderTwilightForest;
import cpw.mods.fml.common.IPlayerTracker;
import cpw.mods.fml.common.ICraftingHandler;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.IScheduledTickHandler;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.common.network.IGuiHandler;
import cpw.mods.fml.common.network.NetworkRegistry;
import twilightforest.item.TFRecipes;
import twilightforest.entity.TFCreatures;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import twilightforest.structures.StructureTFMajorFeatureStart;
import net.minecraftforge.common.AchievementPage;
import twilightforest.item.TFItems;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import twilightforest.block.TFBlocks;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.Mod;

@Mod(modid = "TwilightForest", name = "The Twilight Forest", version = "1.20.5")
@NetworkMod(channels = { "TwilightForest", "tfmagicmap", "tfmazemap" }, clientSideRequired = true, serverSideRequired = false, packetHandler = TFPacketHandler.class, connectionHandler = TFPacketHandler.class)
public class TwilightForestMod
{
    public static final String ID = "TwilightForest";
    public static final String VERSION = "1.20.5";
    public static final String MODEL_DIR = "twilightforest:textures/model/";
    public static final String GUI_DIR = "twilightforest:textures/gui/";
    public static final String ARMOR_DIR = "twilightforest:textures/armor/";
    public static int dimensionID;
    public static int backupdimensionID;
    public static int dimensionProviderID;
    public static int achievementBaseID;
    public static boolean creatureCompatibility;
    public static boolean silentCicadas;
    public static boolean allowPortalsInOtherDimensions;
    public static boolean adminOnlyPortals;
    public static String twilightForestSeed;
    public static boolean disablePortalCreation;
    public static boolean disableUncrafting;
    public static boolean enforcedProgression;
    public static boolean mapGenChanges;
    public static float canopyCoverage;
    public static int twilightOakChance;
    public static int idBlockFirefly;
    public static int idBlockPortal;
    public static int idBlockLog;
    public static int idBlockLeaves;
    public static int idBlockMazestone;
    public static int idBlockHedge;
    public static int idBlockBossSpawner;
    public static int idBlockFireflyJar;
    public static int idBlockPlant;
    public static int idBlockRoots;
    public static int idBlockCicada;
    public static int idBlockUncraftingTable;
    public static int idBlockFireJet;
    public static int idBlockNagastone;
    public static int idBlockSapling;
    public static int idBlockMagicLog;
    public static int idBlockMagicLeaves;
    public static int idBlockMoonworm;
    public static int idBlockMagicLogSpecial;
    public static int idBlockTowerWood;
    public static int idBlockTowerDevice;
    public static int idBlockTowerTranslucent;
    public static int idBlockTrophy;
    public static int idBlockShield;
    public static int idBlockTrophyPedestal;
    public static int idBlockAuroraBrick;
    public static int idBlockUnderBrick;
    public static int idItemNagaScale;
    public static int idItemPlateNaga;
    public static int idItemLegsNaga;
    public static int idItemScepterTwilight;
    public static int idItemScepterLifeDrain;
    public static int idItemScepterZombie;
    public static int idItemWandPacification;
    public static int idItemOreMeter;
    public static int idItemMagicMap;
    public static int idItemMazeMap;
    public static int idItemOreMap;
    public static int idItemFeather;
    public static int idItemMagicMapFocus;
    public static int idItemMazeMapFocus;
    public static int idItemLiveRoot;
    public static int idItemIronwoodRaw;
    public static int idItemIronwoodIngot;
    public static int idItemIronwoodHelm;
    public static int idItemIronwoodPlate;
    public static int idItemIronwoodLegs;
    public static int idItemIronwoodBoots;
    public static int idItemIronwoodSword;
    public static int idItemIronwoodShovel;
    public static int idItemIronwoodPick;
    public static int idItemIronwoodAxe;
    public static int idItemIronwoodHoe;
    public static int idItemTorchberries;
    public static int idItemSpawnEgg;
    public static int idItemVenisonRaw;
    public static int idItemVenisonCooked;
    public static int idItemHydraChops;
    public static int idItemFieryBlood;
    public static int idItemTrophy;
    public static int idItemFieryIngot;
    public static int idItemFieryHelm;
    public static int idItemFieryPlate;
    public static int idItemFieryLegs;
    public static int idItemFieryBoots;
    public static int idItemFierySword;
    public static int idItemFieryPick;
    public static int idItemSteeleafIngot;
    public static int idItemSteeleafHelm;
    public static int idItemSteeleafPlate;
    public static int idItemSteeleafLegs;
    public static int idItemSteeleafBoots;
    public static int idItemSteeleafSword;
    public static int idItemSteeleafShovel;
    public static int idItemSteeleafPick;
    public static int idItemSteeleafAxe;
    public static int idItemSteeleafHoe;
    public static int idItemMinotaurAxe;
    public static int idItemMazebreakerPick;
    public static int idItemTransformPowder;
    public static int idItemMeefRaw;
    public static int idItemMeefSteak;
    public static int idItemMeefStroganoff;
    public static int idItemMazeWafer;
    public static int idItemEmptyMagicMap;
    public static int idItemEmptyMazeMap;
    public static int idItemEmptyOreMap;
    public static int idItemOreMagnet;
    public static int idItemCrumbleHorn;
    public static int idItemPeacockFan;
    public static int idItemMoonwormQueen;
    public static int idItemCharmOfLife1;
    public static int idItemCharmOfLife2;
    public static int idItemCharmOfKeeping1;
    public static int idItemCharmOfKeeping2;
    public static int idItemCharmOfKeeping3;
    public static int idItemTowerKey;
    public static int idItemBorerEssence;
    public static int idItemCarminite;
    public static int idItemExperiment115;
    public static int idItemArmorShards;
    public static int idItemKnightMetal;
    public static int idItemShardCluster;
    public static int idItemKnightlyHelm;
    public static int idItemKnightlyPlate;
    public static int idItemKnightlyLegs;
    public static int idItemKnightlyBoots;
    public static int idItemKnightlySword;
    public static int idItemKnightlyPick;
    public static int idItemKnightlyAxe;
    public static int idItemPhantomHelm;
    public static int idItemPhantomPlate;
    public static int idMobWildBoar;
    public static int idMobBighornSheep;
    public static int idMobWildDeer;
    public static int idMobRedcap;
    public static int idMobSwarmSpider;
    public static int idMobNaga;
    public static int idMobNagaSegment;
    public static int idMobSkeletonDruid;
    public static int idMobHostileWolf;
    public static int idMobTwilightWraith;
    public static int idMobHedgeSpider;
    public static int idMobHydra;
    public static int idMobLich;
    public static int idMobPenguin;
    public static int idMobLichMinion;
    public static int idMobLoyalZombie;
    public static int idMobTinyBird;
    public static int idMobSquirrel;
    public static int idMobBunny;
    public static int idMobRaven;
    public static int idMobQuestRam;
    public static int idMobKobold;
    public static int idMobBoggard;
    public static int idMobMosquitoSwarm;
    public static int idMobDeathTome;
    public static int idMobMinotaur;
    public static int idMobMinoshroom;
    public static int idMobFireBeetle;
    public static int idMobSlimeBeetle;
    public static int idMobPinchBeetle;
    public static int idMobMazeSlime;
    public static int idMobRedcapSapper;
    public static int idMobMistWolf;
    public static int idMobKingSpider;
    public static int idMobFirefly;
    public static int idMobMiniGhast;
    public static int idMobTowerGhast;
    public static int idMobTowerGolem;
    public static int idMobTowerTermite;
    public static int idMobTowerBroodling;
    public static int idMobTowerBoss;
    public static int idMobBlockGoblin;
    public static int idMobGoblinKnightUpper;
    public static int idMobGoblinKnightLower;
    public static int idMobHelmetCrab;
    public static int idMobKnightPhantom;
    public static int idVehicleSpawnNatureBolt;
    public static int idVehicleSpawnLichBolt;
    public static int idVehicleSpawnTwilightWandBolt;
    public static int idVehicleSpawnTomeBolt;
    public static int idVehicleSpawnHydraMortar;
    public static int idVehicleSpawnLichBomb;
    public static int idVehicleSpawnMoonwormShot;
    public static int idVehicleSpawnSlimeBlob;
    public static int idVehicleSpawnCharmEffect;
    public static int idVehicleSpawnThrownAxe;
    public static int idVehicleSpawnThrownPick;
    public static int idBiomeLake;
    public static int idBiomeTwilightForest;
    public static int idBiomeTwilightForestVariant;
    public static int idBiomeHighlands;
    public static int idBiomeMushrooms;
    public static int idBiomeSwamp;
    public static int idBiomeStream;
    public static int idBiomeSnowfield;
    public static int idBiomeGlacier;
    public static int idBiomeClearing;
    public static int idBiomeClearingBorder;
    public static int idBiomeLightedForest;
    public static int idBiomeDeepMushrooms;
    public static int idBiomeMajorFeature;
    public static int idBiomeMinorFeature;
    public static int idBiomeDarkForest;
    public static int idBiomeEnchantedForest;
    public static int idBiomeFireSwamp;
    public static int idEnchantmentFieryAura;
    public static boolean biomeIDConflicts;
    @Mod.Instance("TwilightForest")
    public static TwilightForestMod instance;
    @SidedProxy(clientSide = "twilightforest.client.TFClientProxy", serverSide = "twilightforest.TFCommonProxy")
    public static TFCommonProxy proxy;
    public static final TFEventListener eventListener;
    TFBlocks blocks;
    TFTickHandler tickHandler;
    
    public TwilightForestMod() {
        TwilightForestMod.instance = this;
    }
    
    @Mod.EventHandler
    public void preInit(final FMLPreInitializationEvent event) {
        this.loadConfiguration(new Configuration(event.getSuggestedConfigurationFile()));
        TwilightForestMod.proxy.doPreLoadRegistration();
        new TFBlocks();
        new TFItems();
        AchievementPage.registerAchievementPage((AchievementPage)new TFAchievementPage());
        new StructureTFMajorFeatureStart();
    }
    
    @Mod.EventHandler
    public void load(final FMLInitializationEvent evt) {
        new TFCreatures();
        this.registerCreatures();
        new TFRecipes();
        this.registerTileEntities();
        TwilightForestMod.proxy.doOnLoadRegistration();
        NetworkRegistry.instance().registerGuiHandler((Object)TwilightForestMod.instance, (IGuiHandler)TwilightForestMod.proxy);
        TickRegistry.registerScheduledTickHandler((IScheduledTickHandler)(this.tickHandler = new TFTickHandler()), Side.SERVER);
        MinecraftForge.EVENT_BUS.register((Object)TwilightForestMod.eventListener);
        GameRegistry.registerCraftingHandler((ICraftingHandler)TwilightForestMod.eventListener);
        GameRegistry.registerPlayerTracker((IPlayerTracker)TwilightForestMod.eventListener);
        DimensionManager.registerProviderType(TwilightForestMod.dimensionProviderID, (Class)WorldProviderTwilightForest.class, false);
        TFLocalization.loadLocalizations();
        TFBiomeBase.registerWithBiomeDictionary();
    }
    
    @Mod.EventHandler
    public void postInit(final FMLPostInitializationEvent evt) {
        if (this.isDimensionUnregistered(TwilightForestMod.dimensionID)) {
            DimensionManager.registerDimension(TwilightForestMod.dimensionID, TwilightForestMod.dimensionProviderID);
        }
        else {
            FMLLog.warning("[TwilightForest] Twilight Forest detected that the configured dimension id '%d' is being used.  Using backup ID.  It is recommended that you configure this mod to use a unique dimension ID.", new Object[] { TwilightForestMod.dimensionID });
            DimensionManager.registerDimension(TwilightForestMod.backupdimensionID, TwilightForestMod.dimensionProviderID);
            TwilightForestMod.dimensionID = TwilightForestMod.backupdimensionID;
        }
        if (Loader.isModLoaded("Thaumcraft")) {
            this.registerThaumcraftIntegration();
        }
        else {
            FMLLog.info("[TwilightForest] Did not find Thaumcraft, did not load ThaumcraftApi integration.", new Object[0]);
        }
        TwilightForestMod.biomeIDConflicts = TFBiomeBase.checkForBiomeConflicts();
    }
    
    @Mod.EventHandler
    public void startServer(final FMLServerStartingEvent event) {
        event.registerServerCommand((ICommand)new CommandTFLocate());
        this.registerDispenseBehaviors(event.getServer());
    }
    
    private void registerCreatures() {
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFBoar.class, "Wild Boar", TwilightForestMod.idMobWildBoar, 8611131, 16773066);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFBighorn.class, "Bighorn Sheep", TwilightForestMod.idMobBighornSheep, 14405295, 14141297);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFDeer.class, "Wild Deer", TwilightForestMod.idMobWildDeer, 8080686, 4924445);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFRedcap.class, "Redcap", TwilightForestMod.idMobRedcap, 3881580, 11214356);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFSwarmSpider.class, "Swarm Spider", TwilightForestMod.idMobSwarmSpider, 3277358, 1516830);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFNaga.class, "Naga", TwilightForestMod.idMobNaga, 10801942, 1783819);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFSkeletonDruid.class, "Skeleton Druid", TwilightForestMod.idMobSkeletonDruid, 10724259, 2767639);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFHostileWolf.class, "Hostile Wolf", TwilightForestMod.idMobHostileWolf, 14144467, 11214356);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFWraith.class, "Twilight Wraith", TwilightForestMod.idMobTwilightWraith, 5263440, 8618883);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFHedgeSpider.class, "Hedge Spider", TwilightForestMod.idMobHedgeSpider, 2318099, 5645907);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFHydra.class, "Hydra", TwilightForestMod.idMobHydra, 1321280, 2719851);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFLich.class, "Twilight Lich", TwilightForestMod.idMobLich, 11314313, 3540082);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFPenguin.class, "Penguin", TwilightForestMod.idMobPenguin, 1185051, 16379346);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFLichMinion.class, "Lich Minion", TwilightForestMod.idMobLichMinion);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFLoyalZombie.class, "Loyal Zombie", TwilightForestMod.idMobLoyalZombie);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFTinyBird.class, "Tiny Bird", TwilightForestMod.idMobTinyBird, 3386077, 1149166);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFSquirrel.class, "Forest Squirrel", TwilightForestMod.idMobSquirrel, 9457426, 15658734);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFBunny.class, "Forest Bunny", TwilightForestMod.idMobBunny, 16711406, 13413017);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFRaven.class, "Forest Raven", TwilightForestMod.idMobRaven, 17, 2236979);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFQuestRam.class, "Questing Ram", TwilightForestMod.idMobQuestRam);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFKobold.class, "Twilight Kobold", TwilightForestMod.idMobKobold, 3612822, 9002267);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFBoggard.class, "Boggard", TwilightForestMod.idMobBoggard);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMosquitoSwarm.class, "Mosquito Swarm", TwilightForestMod.idMobMosquitoSwarm, 526596, 2961185);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFDeathTome.class, "Death Tome", TwilightForestMod.idMobDeathTome, 7818786, 14405054);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMinotaur.class, "Minotaur", TwilightForestMod.idMobMinotaur, 4141092, 11173222);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMinoshroom.class, "Minoshroom", TwilightForestMod.idMobMinoshroom, 11014162, 11173222);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFFireBeetle.class, "Fire Beetle", TwilightForestMod.idMobFireBeetle, 1903360, 13332261);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFSlimeBeetle.class, "Slime Beetle", TwilightForestMod.idMobSlimeBeetle, 792070, 6334284);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFPinchBeetle.class, "Pinch Beetle", TwilightForestMod.idMobPinchBeetle, 12358439, 2364937);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMazeSlime.class, "Maze Slime", TwilightForestMod.idMobMazeSlime, 10724259, 2767639);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFRedcapSapper.class, "Redcap Sapper", TwilightForestMod.idMobRedcapSapper, 5725473, 11214356);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMistWolf.class, "Mist Wolf", TwilightForestMod.idMobMistWolf, 3806225, 14862474);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFKingSpider.class, "King Spider", TwilightForestMod.idMobKingSpider, 2890254, 16760855);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMobileFirefly.class, "Firefly", TwilightForestMod.idMobFirefly, 10801942, 12250626);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFMiniGhast.class, "Mini Ghast", TwilightForestMod.idMobMiniGhast, 12369084, 10961731);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFTowerGhast.class, "Tower Ghast", TwilightForestMod.idMobTowerGhast, 12369084, 12023928);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFTowerGolem.class, "Tower Golem", TwilightForestMod.idMobTowerGolem, 7028000, 14867930);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFTowerTermite.class, "Tower Termite", TwilightForestMod.idMobTowerTermite, 6105889, 11313210);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFTowerBroodling.class, "Redscale Broodling", TwilightForestMod.idMobTowerBroodling, 3423252, 12250626);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFUrGhast.class, "Tower Boss", TwilightForestMod.idMobTowerBoss, 12369084, 12023928);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFBlockGoblin.class, "Block&Chain Goblin", TwilightForestMod.idMobBlockGoblin, 13887420, 2047999);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFGoblinKnightUpper.class, "Upper Goblin Knight", TwilightForestMod.idMobGoblinKnightUpper);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFGoblinKnightLower.class, "Lower Goblin Knight", TwilightForestMod.idMobGoblinKnightLower, 5660757, 13887420);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFHelmetCrab.class, "Helmet Crab", TwilightForestMod.idMobHelmetCrab, 16486475, 13887420);
        TFCreatures.registerTFCreature((Class<? extends Entity>)EntityTFKnightPhantom.class, "Knight Phantom", TwilightForestMod.idMobKnightPhantom, 10905403, 13887420);
        EntityRegistry.registerModEntity((Class)EntityTFHydraHead.class, "HydraHead", 11, (Object)this, 150, 3, false);
        EntityRegistry.registerModEntity((Class)EntityTFNatureBolt.class, "tfnaturebolt", TwilightForestMod.idVehicleSpawnNatureBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFLichBolt.class, "tflichbolt", TwilightForestMod.idVehicleSpawnLichBolt, (Object)this, 150, 2, true);
        EntityRegistry.registerModEntity((Class)EntityTFTwilightWandBolt.class, "tftwilightwandbolt", TwilightForestMod.idVehicleSpawnTwilightWandBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFTomeBolt.class, "tftomebolt", TwilightForestMod.idVehicleSpawnTomeBolt, (Object)this, 150, 5, true);
        EntityRegistry.registerModEntity((Class)EntityTFHydraMortar.class, "tfhydramortar", TwilightForestMod.idVehicleSpawnHydraMortar, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFLichBomb.class, "tflichbomb", TwilightForestMod.idVehicleSpawnLichBomb, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFMoonwormShot.class, "tfmoonwormshot", TwilightForestMod.idVehicleSpawnMoonwormShot, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFSlimeProjectile.class, "tfslimeblob", TwilightForestMod.idVehicleSpawnSlimeBlob, (Object)this, 150, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFCharmEffect.class, "tfcharmeffect", TwilightForestMod.idVehicleSpawnCharmEffect, (Object)this, 80, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFThrownAxe.class, "tfthrownaxe", TwilightForestMod.idVehicleSpawnThrownAxe, (Object)this, 80, 3, true);
        EntityRegistry.registerModEntity((Class)EntityTFThrownPick.class, "tfthrownpick", TwilightForestMod.idVehicleSpawnThrownPick, (Object)this, 80, 3, true);
    }
    
    private void registerTileEntities() {
        GameRegistry.registerTileEntity((Class)TileEntityTFFirefly.class, "Firefly");
        GameRegistry.registerTileEntity((Class)TileEntityTFCicada.class, "Cicada");
        GameRegistry.registerTileEntity((Class)TileEntityTFNagaSpawner.class, "Naga Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFLichSpawner.class, "Lich Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFHydraSpawner.class, "Hydra Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFSmoker.class, "Swamp Smoker");
        GameRegistry.registerTileEntity((Class)TileEntityTFPoppingJet.class, "Popping Flame Jet");
        GameRegistry.registerTileEntity((Class)TileEntityTFFlameJet.class, "Lit Flame Jet");
        GameRegistry.registerTileEntity((Class)TileEntityTFMoonworm.class, "Moonworm");
        GameRegistry.registerTileEntity((Class)TileEntityTFTowerBuilder.class, "Tower Builder");
        GameRegistry.registerTileEntity((Class)TileEntityTFReverter.class, "Tower Reverter");
        GameRegistry.registerTileEntity((Class)TileEntityTFTrophy.class, "TF Trophy");
        GameRegistry.registerTileEntity((Class)TileEntityTFTowerBossSpawner.class, "Tower Boss Spawner");
        GameRegistry.registerTileEntity((Class)TileEntityTFGhastTrapInactive.class, "Inactive Ghast Trap");
        GameRegistry.registerTileEntity((Class)TileEntityTFGhastTrapActive.class, "Active Ghast Trap");
        GameRegistry.registerTileEntity((Class)TileEntityTFCReactorActive.class, "Active Carminite Reactor");
        GameRegistry.registerTileEntity((Class)TileEntityTFKnightPhantomsSpawner.class, "Knight Phantom Spawner");
    }
    
    private boolean isDimensionUnregistered(final int dimID) {
        try {
            DimensionManager.getProviderType(dimID);
            return false;
        }
        catch (IllegalArgumentException ex) {
            return true;
        }
    }
    
    private void registerThaumcraftIntegration() {
        try {
            ThaumcraftApi.registerObjectTag(TFItems.nagaScale.field_77779_bT, -1, new AspectList().add(Aspect.MOTION, 2).add(Aspect.ARMOR, 3));
            ThaumcraftApi.registerComplexObjectTag(TFItems.scepterTwilight.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 8).add(Aspect.ELDRITCH, 8).add(Aspect.WEAPON, 8));
            ThaumcraftApi.registerComplexObjectTag(TFItems.scepterLifeDrain.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 8).add(Aspect.LIFE, 8).add(Aspect.HUNGER, 8));
            ThaumcraftApi.registerComplexObjectTag(TFItems.scepterZombie.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 8).add(Aspect.UNDEAD, 8).add(Aspect.ENTROPY, 8));
            ThaumcraftApi.registerObjectTag(TFItems.magicMapFocus.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 4).add(Aspect.SENSES, 8));
            ThaumcraftApi.registerObjectTag(TFItems.mazeMapFocus.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 4).add(Aspect.SENSES, 8).add(Aspect.ORDER, 4));
            ThaumcraftApi.registerObjectTag(TFItems.feather.field_77779_bT, -1, new AspectList().add(Aspect.FLIGHT, 2).add(Aspect.AIR, 1).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag(TFItems.liveRoot.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 1).add(Aspect.TREE, 2).add(Aspect.LIFE, 2));
            ThaumcraftApi.registerObjectTag(TFItems.ironwoodIngot.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 2).add(Aspect.TREE, 1).add(Aspect.METAL, 4).add(Aspect.CRAFT, 2));
            ThaumcraftApi.registerObjectTag(TFItems.torchberries.field_77779_bT, -1, new AspectList().add(Aspect.PLANT, 2).add(Aspect.LIGHT, 2));
            ThaumcraftApi.registerObjectTag(TFItems.fieryBlood.field_77779_bT, -1, new AspectList().add(Aspect.FIRE, 8).add(Aspect.LIFE, 8).add(Aspect.MAGIC, 4));
            ThaumcraftApi.registerObjectTag(TFItems.trophy.field_77779_bT, -1, new AspectList().add(Aspect.LIFE, 6).add(Aspect.BEAST, 6).add(Aspect.SOUL, 6));
            ThaumcraftApi.registerObjectTag(TFItems.steeleafIngot.field_77779_bT, -1, new AspectList().add(Aspect.PLANT, 4).add(Aspect.METAL, 2));
            ThaumcraftApi.registerComplexObjectTag(TFItems.minotaurAxe.field_77779_bT, -1, new AspectList().add(Aspect.TOOL, 2).add(Aspect.WEAPON, 4).add(Aspect.CRYSTAL, 6).add(Aspect.GREED, 8));
            ThaumcraftApi.registerComplexObjectTag(TFItems.mazebreakerPick.field_77779_bT, -1, new AspectList().add(Aspect.CRYSTAL, 6).add(Aspect.TOOL, 8).add(Aspect.MINE, 8));
            ThaumcraftApi.registerObjectTag(TFItems.oreMagnet.field_77779_bT, -1, new AspectList().add(Aspect.GREED, 10).add(Aspect.TOOL, 6).add(Aspect.METAL, 8).add(Aspect.MOTION, 6));
            ThaumcraftApi.registerObjectTag(TFItems.crumbleHorn.field_77779_bT, -1, new AspectList().add(Aspect.ENTROPY, 12).add(Aspect.BEAST, 2));
            ThaumcraftApi.registerObjectTag(TFItems.peacockFan.field_77779_bT, -1, new AspectList().add(Aspect.AIR, 8).add(Aspect.MOTION, 6).add(Aspect.FLIGHT, 10));
            ThaumcraftApi.registerObjectTag(TFItems.moonwormQueen.field_77779_bT, -1, new AspectList().add(Aspect.LIGHT, 12).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag(TFItems.charmOfLife1.field_77779_bT, -1, new AspectList().add(Aspect.LIFE, 2).add(Aspect.HEAL, 2).add(Aspect.GREED, 4));
            ThaumcraftApi.registerObjectTag(TFItems.charmOfKeeping1.field_77779_bT, -1, new AspectList().add(Aspect.DEATH, 1).add(Aspect.TRAVEL, 2).add(Aspect.GREED, 4));
            ThaumcraftApi.registerObjectTag(TFItems.towerKey.field_77779_bT, -1, new AspectList().add(Aspect.MECHANISM, 4).add(Aspect.MAGIC, 4));
            ThaumcraftApi.registerObjectTag(TFItems.transformPowder.field_77779_bT, -1, new AspectList().add(Aspect.MAGIC, 8).add(Aspect.EXCHANGE, 4));
            ThaumcraftApi.registerObjectTag(TFItems.borerEssence.field_77779_bT, -1, new AspectList().add(Aspect.BEAST, 2).add(Aspect.TREE, 2).add(Aspect.SOUL, 4).add(Aspect.MAGIC, 2));
            ThaumcraftApi.registerObjectTag(TFItems.armorShard.field_77779_bT, -1, new AspectList().add(Aspect.METAL, 1));
            ThaumcraftApi.registerObjectTag(TFItems.knightMetal.field_77779_bT, -1, new AspectList().add(Aspect.METAL, 8).add(Aspect.CRAFT, 1));
            ThaumcraftApi.registerObjectTag(TFItems.phantomHelm.field_77779_bT, -1, new AspectList().add(Aspect.METAL, 6).add(Aspect.ARMOR, 6).add(Aspect.UNDEAD, 6));
            ThaumcraftApi.registerObjectTag(TFItems.phantomPlate.field_77779_bT, -1, new AspectList().add(Aspect.METAL, 8).add(Aspect.ARMOR, 8).add(Aspect.UNDEAD, 8));
            ThaumcraftApi.registerObjectTag(TFItems.venisonRaw.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 2).add(Aspect.FLESH, 4).add(Aspect.BEAST, 2));
            ThaumcraftApi.registerObjectTag(TFItems.venisonCooked.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 4).add(Aspect.FLESH, 4).add(Aspect.CRAFT, 1));
            ThaumcraftApi.registerObjectTag(TFItems.hydraChop.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 6).add(Aspect.FLESH, 6).add(Aspect.LIFE, 4));
            ThaumcraftApi.registerObjectTag(TFItems.meefRaw.field_77779_bT, -1, new AspectList().add(Aspect.BEAST, 2).add(Aspect.FLESH, 4).add(Aspect.LIFE, 2));
            ThaumcraftApi.registerObjectTag(TFItems.meefSteak.field_77779_bT, -1, new AspectList().add(Aspect.FIRE, 1).add(Aspect.BEAST, 1).add(Aspect.FLESH, 4).add(Aspect.LIFE, 2));
            ThaumcraftApi.registerObjectTag(TFItems.meefStroganoff.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 4).add(Aspect.BEAST, 2).add(Aspect.FLESH, 4));
            ThaumcraftApi.registerObjectTag(TFItems.mazeWafer.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 2));
            ThaumcraftApi.registerObjectTag(TFItems.experiment115.field_77779_bT, -1, new AspectList().add(Aspect.HUNGER, 3).add(Aspect.MECHANISM, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.firefly.field_71990_ca, -1, new AspectList().add(Aspect.FLIGHT, 1).add(Aspect.LIGHT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.leaves.field_71990_ca, -1, new AspectList().add(Aspect.PLANT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.mazestone.field_71990_ca, -1, new AspectList().add(Aspect.STONE, 2).add(Aspect.TRAP, 1).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.hedge.field_71990_ca, 0, new AspectList().add(Aspect.PLANT, 1).add(Aspect.WEAPON, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.hedge.field_71990_ca, 1, new AspectList().add(Aspect.PLANT, 3).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.root.field_71990_ca, -1, new AspectList().add(Aspect.TREE, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.cicada.field_71990_ca, -1, new AspectList().add(Aspect.SENSES, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.uncraftingTable.field_71990_ca, -1, new AspectList().add(Aspect.TREE, 4).add(Aspect.ENTROPY, 8).add(Aspect.EXCHANGE, 12).add(Aspect.CRAFT, 16));
            ThaumcraftApi.registerObjectTag(TFBlocks.fireJet.field_71990_ca, -1, new AspectList().add(Aspect.FIRE, 4).add(Aspect.AIR, 2).add(Aspect.MOTION, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.nagastone.field_71990_ca, -1, new AspectList().add(Aspect.STONE, 2).add(Aspect.MOTION, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.magicLeaves.field_71990_ca, -1, new AspectList().add(Aspect.PLANT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.towerWood.field_71990_ca, -1, new AspectList().add(Aspect.TREE, 2).add(Aspect.MECHANISM, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.towerDevice.field_71990_ca, -1, new AspectList().add(Aspect.TREE, 4).add(Aspect.MECHANISM, 4).add(Aspect.MAGIC, 4));
            ThaumcraftApi.registerObjectTag(TFBlocks.towerTranslucent.field_71990_ca, -1, new AspectList().add(Aspect.TREE, 4).add(Aspect.MECHANISM, 4).add(Aspect.MAGIC, 4).add(Aspect.VOID, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.trophy.field_71990_ca, -1, new AspectList().add(Aspect.LIFE, 6).add(Aspect.BEAST, 6).add(Aspect.SOUL, 6));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 3, new AspectList().add(Aspect.PLANT, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 4, new AspectList().add(Aspect.PLANT, 1).add(Aspect.SEED, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 5, new AspectList().add(Aspect.PLANT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 8, new AspectList().add(Aspect.PLANT, 2).add(Aspect.MAGIC, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 9, new AspectList().add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1).add(Aspect.LIGHT, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 10, new AspectList().add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 11, new AspectList().add(Aspect.PLANT, 2).add(Aspect.DARKNESS, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 13, new AspectList().add(Aspect.PLANT, 2).add(Aspect.LIGHT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.plant.field_71990_ca, 14, new AspectList().add(Aspect.PLANT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.sapling.field_71990_ca, -1, new AspectList().add(Aspect.PLANT, 4).add(Aspect.TREE, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.moonworm.field_71990_ca, -1, new AspectList().add(Aspect.DARKNESS, 2).add(Aspect.LIGHT, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.shield.field_71990_ca, -1, new AspectList().add(Aspect.TRAP, 1).add(Aspect.MAGIC, 1).add(Aspect.ARMOR, 1));
            ThaumcraftApi.registerObjectTag(TFBlocks.trophyPedestal.field_71990_ca, -1, new AspectList().add(Aspect.GREED, 6).add(Aspect.BEAST, 5));
            ThaumcraftApi.registerObjectTag(TFBlocks.auroraBrick.field_71990_ca, -1, new AspectList().add(Aspect.ICE, 2).add(Aspect.CRYSTAL, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.underBrick.field_71990_ca, -1, new AspectList().add(Aspect.DARKNESS, 2).add(Aspect.STONE, 2));
            ThaumcraftApi.registerObjectTag(TFBlocks.portal.field_71990_ca, -1, new AspectList().add(Aspect.MAGIC, 1).add(Aspect.MOTION, 2));
            FMLLog.info("[TwilightForest] Loaded ThaumcraftApi integration.", new Object[0]);
        }
        catch (Exception e) {
            FMLLog.warning("[TwilightForest] Had an %s error while trying to register with ThaumcraftApi.", new Object[] { e.getLocalizedMessage() });
        }
    }
    
    private void registerDispenseBehaviors(final MinecraftServer minecraftServer) {
        BlockDispenser.field_82527_a.func_82595_a((Object)TFItems.spawnEgg, (Object)new BehaviorTFMobEggDispense(minecraftServer));
    }
    
    private void loadConfiguration(final Configuration configFile) {
        configFile.load();
        TwilightForestMod.dimensionID = configFile.get("dimension", "dimensionID", 7).getInt();
        configFile.get("dimension", "dimensionID", 7).comment = "What ID number to assign to the Twilight Forest dimension.  Change if you are having conflicts with another mod.";
        TwilightForestMod.silentCicadas = configFile.get("general", "SilentCicadas", false).getBoolean(false);
        configFile.get("general", "SilentCicadas", false).comment = "Make cicadas silent  for those having sound library problems, or otherwise finding them annoying";
        TwilightForestMod.allowPortalsInOtherDimensions = configFile.get("general", "AllowPortalsInOtherDimensions", false).getBoolean(false);
        configFile.get("general", "AllowPortalsInOtherDimensions", false).comment = "Allow portals to the Twilight Forest to be made outside of dimension 0.  May be considered an exploit.";
        TwilightForestMod.adminOnlyPortals = configFile.get("general", "AdminOnlyPortals", false).getBoolean(false);
        configFile.get("general", "AdminOnlyPortals", false).comment = "Allow portals only for admins (ops).  This severly reduces the range in which the mod usually scans for valid portal conditions, and it scans near ops only.";
        TwilightForestMod.twilightForestSeed = configFile.get("general", "TwilightForestSeed", "").getString();
        configFile.get("general", "TwilightForestSeed", "").comment = "If set, this will override the normal world seed when generating parts of the Twilight Forest Dimension.";
        TwilightForestMod.disablePortalCreation = configFile.get("general", "DisablePortalCreation", false).getBoolean(false);
        configFile.get("general", "DisablePortalCreation", false).comment = "Disable Twilight Forest portal creation entirely.  Provided for server operators looking to restrict action to the dimension.";
        TwilightForestMod.disableUncrafting = configFile.get("general", "DisableUncrafting", false).getBoolean(false);
        configFile.get("general", "DisableUncrafting", false).comment = "Disable the uncrafting function of the uncrafting table.  Provided as an option when interaction with other mods produces exploitable recipes.";
        TwilightForestMod.enforcedProgression = configFile.get("general", "EnforcedProgression", false).getBoolean(false);
        configFile.get("general", "EnforcedProgression", false).comment = "Enforced progression through Twilight Forest dungeons/areas.  [NYI]";
        TwilightForestMod.mapGenChanges = configFile.get("general", "MapGenChanges", false).getBoolean(false);
        configFile.get("general", "MapGenChanges", false).comment = "World generation changes, intended for release with the version of the mod that works with Minecraft 1.7.";
        TwilightForestMod.achievementBaseID = configFile.get("general", "AchievementBaseID", 7000).getInt(7000);
        configFile.get("general", "AchievementBaseID", 7000).comment = "Base ID for achievements.  Changing this may break compatibility with existing saves.";
        TwilightForestMod.canopyCoverage = (float)configFile.get("Performance", "CanopyCoverage", 1.7).getDouble(1.7);
        configFile.get("performance", "CanopyCoverage", 1.7).comment = "Amount of canopy coverage, from 0.0 on up.  Lower numbers improve chunk generation speed at the cost of a thinner forest.";
        TwilightForestMod.twilightOakChance = configFile.get("Performance", "TwilightOakChance", 48).getInt(48);
        configFile.get("Performance", "TwilightOakChance", 48).comment = "Chance that a chunk in the Twilight Forest will contain a twilight oak tree.  Higher numbers reduce the number of trees, increasing performance.";
        TwilightForestMod.idBlockFirefly = configFile.getBlock("Critter", 2160).getInt();
        TwilightForestMod.idBlockPortal = configFile.getBlock("Portal", 2162).getInt();
        TwilightForestMod.idBlockLog = configFile.getBlock("Log", 2163).getInt();
        TwilightForestMod.idBlockLeaves = configFile.getBlock("Leaves", 2164).getInt();
        TwilightForestMod.idBlockMazestone = configFile.getBlock("Mazestone", 2165).getInt();
        TwilightForestMod.idBlockHedge = configFile.getBlock("Hedge", 2166).getInt();
        TwilightForestMod.idBlockBossSpawner = configFile.getBlock("BossSpawner", 2167).getInt();
        TwilightForestMod.idBlockFireflyJar = configFile.getBlock("FireflyJar", 2168).getInt();
        TwilightForestMod.idBlockPlant = configFile.getBlock("Plant", 2169).getInt();
        TwilightForestMod.idBlockRoots = configFile.getBlock("Roots", 2170).getInt();
        TwilightForestMod.idBlockCicada = configFile.getBlock("Cicada", 2171).getInt();
        TwilightForestMod.idBlockUncraftingTable = configFile.getBlock("UncraftingTable", 2172).getInt();
        TwilightForestMod.idBlockFireJet = configFile.getBlock("FireJet", 2173).getInt();
        TwilightForestMod.idBlockNagastone = configFile.getBlock("Nagastone", 2174).getInt();
        TwilightForestMod.idBlockSapling = configFile.getBlock("Sapling", 2175).getInt();
        TwilightForestMod.idBlockMagicLog = configFile.getBlock("MagicLog", 2176).getInt();
        TwilightForestMod.idBlockMagicLeaves = configFile.getBlock("MagicLeaves", 2177).getInt();
        TwilightForestMod.idBlockMoonworm = configFile.getBlock("Moonworm", 2178).getInt();
        TwilightForestMod.idBlockMagicLogSpecial = configFile.getBlock("MagicLogSpecial", 2179).getInt();
        TwilightForestMod.idBlockTowerWood = configFile.getBlock("TowerWood", 2180).getInt();
        TwilightForestMod.idBlockTowerDevice = configFile.getBlock("TowerDevice", 2181).getInt();
        TwilightForestMod.idBlockShield = configFile.getBlock("Shield", 2182).getInt();
        TwilightForestMod.idBlockTowerTranslucent = configFile.getBlock("TowerTranslucent", 2183).getInt();
        TwilightForestMod.idBlockTrophy = configFile.getBlock("Trophy", 2184).getInt();
        TwilightForestMod.idBlockTrophyPedestal = configFile.getBlock("TrophyPedestal", 2185).getInt();
        TwilightForestMod.idBlockAuroraBrick = configFile.getBlock("AuroraBrick", 2186).getInt();
        TwilightForestMod.idBlockUnderBrick = configFile.getBlock("UnderBrick", 2187).getInt();
        TwilightForestMod.idItemNagaScale = configFile.getItem("NagaScale", 27701).getInt();
        TwilightForestMod.idItemPlateNaga = configFile.getItem("PlateNaga", 27702).getInt();
        TwilightForestMod.idItemLegsNaga = configFile.getItem("LegsNaga", 27703).getInt();
        TwilightForestMod.idItemScepterTwilight = configFile.getItem("ScepterTwilight", 27704).getInt();
        TwilightForestMod.idItemScepterLifeDrain = configFile.getItem("ScepterLifeDrain", 27705).getInt();
        TwilightForestMod.idItemScepterZombie = configFile.getItem("ScepterZombie", 27706).getInt();
        TwilightForestMod.idItemWandPacification = configFile.getItem("WandPacification", 27707).getInt();
        TwilightForestMod.idItemOreMeter = configFile.getItem("OreMeter", 27708).getInt();
        TwilightForestMod.idItemMagicMap = configFile.getItem("MagicMap", 27709).getInt();
        TwilightForestMod.idItemMazeMap = configFile.getItem("MazeMap", 27710).getInt();
        TwilightForestMod.idItemOreMap = configFile.getItem("OreMap", 27711).getInt();
        TwilightForestMod.idItemFeather = configFile.getItem("Feather", 27712).getInt();
        TwilightForestMod.idItemMagicMapFocus = configFile.getItem("MagicMapFocus", 27713).getInt();
        TwilightForestMod.idItemMazeMapFocus = configFile.getItem("MazeMapFocus", 27714).getInt();
        TwilightForestMod.idItemLiveRoot = configFile.getItem("LiveRoot", 27716).getInt();
        TwilightForestMod.idItemIronwoodRaw = configFile.getItem("IronwoodRaw", 27717).getInt();
        TwilightForestMod.idItemIronwoodIngot = configFile.getItem("IronwoodIngot", 27718).getInt();
        TwilightForestMod.idItemIronwoodHelm = configFile.getItem("IronwoodHelm", 27719).getInt();
        TwilightForestMod.idItemIronwoodPlate = configFile.getItem("IronwoodPlate", 27720).getInt();
        TwilightForestMod.idItemIronwoodLegs = configFile.getItem("IronwoodLegs", 27721).getInt();
        TwilightForestMod.idItemIronwoodBoots = configFile.getItem("IronwoodBoots", 27722).getInt();
        TwilightForestMod.idItemIronwoodSword = configFile.getItem("IronwoodSword", 27723).getInt();
        TwilightForestMod.idItemIronwoodShovel = configFile.getItem("IronwoodShovel", 27724).getInt();
        TwilightForestMod.idItemIronwoodPick = configFile.getItem("IronwoodPick", 27725).getInt();
        TwilightForestMod.idItemIronwoodAxe = configFile.getItem("IronwoodAxe", 27726).getInt();
        TwilightForestMod.idItemIronwoodHoe = configFile.getItem("IronwoodHoe", 27727).getInt();
        TwilightForestMod.idItemTorchberries = configFile.getItem("Torchberries", 27728).getInt();
        TwilightForestMod.idItemSpawnEgg = configFile.getItem("SpawnEgg", 27729).getInt();
        TwilightForestMod.idItemVenisonRaw = configFile.getItem("VenisonRaw", 27730).getInt();
        TwilightForestMod.idItemVenisonCooked = configFile.getItem("VenisonCooked", 27731).getInt();
        TwilightForestMod.idItemHydraChops = configFile.getItem("HydraChops", 27732).getInt();
        TwilightForestMod.idItemFieryBlood = configFile.getItem("FieryBlood", 27733).getInt();
        TwilightForestMod.idItemTrophy = configFile.getItem("HydraTrophy", 27734).getInt();
        TwilightForestMod.idItemFieryIngot = configFile.getItem("FieryIngot", 27735).getInt();
        TwilightForestMod.idItemFieryHelm = configFile.getItem("FieryHelm", 27736).getInt();
        TwilightForestMod.idItemFieryPlate = configFile.getItem("FieryPlate", 27737).getInt();
        TwilightForestMod.idItemFieryLegs = configFile.getItem("FieryLegs", 27738).getInt();
        TwilightForestMod.idItemFieryBoots = configFile.getItem("FieryBoots", 27739).getInt();
        TwilightForestMod.idItemFierySword = configFile.getItem("FierySword", 27740).getInt();
        TwilightForestMod.idItemFieryPick = configFile.getItem("FieryPick", 27741).getInt();
        TwilightForestMod.idItemSteeleafIngot = configFile.getItem("SteeleafIngot", 27742).getInt();
        TwilightForestMod.idItemSteeleafHelm = configFile.getItem("SteeleafHelm", 27743).getInt();
        TwilightForestMod.idItemSteeleafPlate = configFile.getItem("SteeleafPlate", 27744).getInt();
        TwilightForestMod.idItemSteeleafLegs = configFile.getItem("SteeleafLegs", 27745).getInt();
        TwilightForestMod.idItemSteeleafBoots = configFile.getItem("SteeleafBoots", 27746).getInt();
        TwilightForestMod.idItemSteeleafSword = configFile.getItem("SteeleafSword", 27747).getInt();
        TwilightForestMod.idItemSteeleafShovel = configFile.getItem("SteeleafShovel", 27748).getInt();
        TwilightForestMod.idItemSteeleafPick = configFile.getItem("SteeleafPick", 27749).getInt();
        TwilightForestMod.idItemSteeleafAxe = configFile.getItem("SteeleafAxe", 27750).getInt();
        TwilightForestMod.idItemSteeleafHoe = configFile.getItem("SteeleafHoe", 27751).getInt();
        TwilightForestMod.idItemMinotaurAxe = configFile.getItem("MinotaurAxe", 27752).getInt();
        TwilightForestMod.idItemMazebreakerPick = configFile.getItem("MazebreakerPick", 27753).getInt();
        TwilightForestMod.idItemTransformPowder = configFile.getItem("TransformPowder", 27754).getInt();
        TwilightForestMod.idItemMeefRaw = configFile.getItem("MeefRaw", 27755).getInt();
        TwilightForestMod.idItemMeefSteak = configFile.getItem("MeefSteak", 27756).getInt();
        TwilightForestMod.idItemMeefStroganoff = configFile.getItem("MeefStroganoff", 27757).getInt();
        TwilightForestMod.idItemMazeWafer = configFile.getItem("MazeWafer", 27758).getInt();
        TwilightForestMod.idItemEmptyMagicMap = configFile.getItem("EmptyMagicMap", 27759).getInt();
        TwilightForestMod.idItemEmptyMazeMap = configFile.getItem("EmptyMazeMap", 27760).getInt();
        TwilightForestMod.idItemEmptyOreMap = configFile.getItem("EmptyOreMap", 27761).getInt();
        TwilightForestMod.idItemOreMagnet = configFile.getItem("OreMagnet", 27762).getInt();
        TwilightForestMod.idItemCrumbleHorn = configFile.getItem("CrumbleHorn", 27763).getInt();
        TwilightForestMod.idItemPeacockFan = configFile.getItem("PeacockFan", 27764).getInt();
        TwilightForestMod.idItemMoonwormQueen = configFile.getItem("MoonwormQueen", 27765).getInt();
        TwilightForestMod.idItemCharmOfLife1 = configFile.getItem("CharmOfLife1", 27766).getInt();
        TwilightForestMod.idItemCharmOfLife2 = configFile.getItem("CharmOfLife2", 27767).getInt();
        TwilightForestMod.idItemCharmOfKeeping2 = configFile.getItem("CharmOfKeeping2", 27768).getInt();
        TwilightForestMod.idItemCharmOfKeeping3 = configFile.getItem("CharmOfKeeping3", 27769).getInt();
        TwilightForestMod.idItemCharmOfKeeping1 = configFile.getItem("CharmOfKeeping1", 27770).getInt();
        TwilightForestMod.idItemTowerKey = configFile.getItem("TowerKey", 27771).getInt();
        TwilightForestMod.idItemBorerEssence = configFile.getItem("BorerEssence", 27772).getInt();
        TwilightForestMod.idItemCarminite = configFile.getItem("Carminite", 27773).getInt();
        TwilightForestMod.idItemExperiment115 = configFile.getItem("Experiment115", 27774).getInt();
        TwilightForestMod.idItemArmorShards = configFile.getItem("ArmorShards", 27775).getInt();
        TwilightForestMod.idItemKnightMetal = configFile.getItem("KnightMetal", 27776).getInt();
        TwilightForestMod.idItemShardCluster = configFile.getItem("ShardCluster", 27777).getInt();
        TwilightForestMod.idItemKnightlyHelm = configFile.getItem("KnightlyHelm", 27778).getInt();
        TwilightForestMod.idItemKnightlyPlate = configFile.getItem("KnightlyPlate", 27779).getInt();
        TwilightForestMod.idItemKnightlyLegs = configFile.getItem("KnightlyLegs", 27780).getInt();
        TwilightForestMod.idItemKnightlyBoots = configFile.getItem("KnightlyBoots", 27781).getInt();
        TwilightForestMod.idItemKnightlySword = configFile.getItem("KnightlySword", 27782).getInt();
        TwilightForestMod.idItemKnightlyPick = configFile.getItem("KnightlyPick", 27783).getInt();
        TwilightForestMod.idItemKnightlyAxe = configFile.getItem("KnightlyAxe", 27784).getInt();
        TwilightForestMod.idItemPhantomHelm = configFile.getItem("PhantomHelm", 27785).getInt();
        TwilightForestMod.idItemPhantomPlate = configFile.getItem("PhantomPlate", 27786).getInt();
        TwilightForestMod.idMobWildBoar = 177;
        TwilightForestMod.idMobBighornSheep = 178;
        TwilightForestMod.idMobWildDeer = 179;
        TwilightForestMod.idMobRedcap = 180;
        TwilightForestMod.idMobSwarmSpider = 181;
        TwilightForestMod.idMobNaga = 182;
        TwilightForestMod.idMobNagaSegment = 183;
        TwilightForestMod.idMobSkeletonDruid = 184;
        TwilightForestMod.idMobHostileWolf = 185;
        TwilightForestMod.idMobTwilightWraith = 186;
        TwilightForestMod.idMobHedgeSpider = 187;
        TwilightForestMod.idMobHydra = 189;
        TwilightForestMod.idMobLich = 190;
        TwilightForestMod.idMobPenguin = 191;
        TwilightForestMod.idMobLichMinion = 192;
        TwilightForestMod.idMobLoyalZombie = 193;
        TwilightForestMod.idMobTinyBird = 194;
        TwilightForestMod.idMobSquirrel = 195;
        TwilightForestMod.idMobBunny = 196;
        TwilightForestMod.idMobRaven = 197;
        TwilightForestMod.idMobQuestRam = 198;
        TwilightForestMod.idMobKobold = 199;
        TwilightForestMod.idMobBoggard = 201;
        TwilightForestMod.idMobMosquitoSwarm = 202;
        TwilightForestMod.idMobDeathTome = 203;
        TwilightForestMod.idMobMinotaur = 204;
        TwilightForestMod.idMobMinoshroom = 205;
        TwilightForestMod.idMobFireBeetle = 206;
        TwilightForestMod.idMobSlimeBeetle = 207;
        TwilightForestMod.idMobPinchBeetle = 208;
        TwilightForestMod.idMobMazeSlime = 209;
        TwilightForestMod.idMobRedcapSapper = 210;
        TwilightForestMod.idMobMistWolf = 211;
        TwilightForestMod.idMobKingSpider = 212;
        TwilightForestMod.idMobFirefly = 213;
        TwilightForestMod.idMobMiniGhast = 214;
        TwilightForestMod.idMobTowerGhast = 215;
        TwilightForestMod.idMobTowerGolem = 216;
        TwilightForestMod.idMobTowerTermite = 218;
        TwilightForestMod.idMobTowerBroodling = 219;
        TwilightForestMod.idMobTowerBoss = 217;
        TwilightForestMod.idMobBlockGoblin = 220;
        TwilightForestMod.idMobGoblinKnightUpper = 221;
        TwilightForestMod.idMobGoblinKnightLower = 222;
        TwilightForestMod.idMobHelmetCrab = 223;
        TwilightForestMod.idMobKnightPhantom = 224;
        TwilightForestMod.idBiomeLake = configFile.get("biome", "biome.id.Lake", 70).getInt();
        TwilightForestMod.idBiomeTwilightForest = configFile.get("biome", "biome.id.TwilightForest", 71).getInt();
        TwilightForestMod.idBiomeTwilightForestVariant = configFile.get("biome", "biome.id.TwilightForestVariant", 72).getInt();
        TwilightForestMod.idBiomeHighlands = configFile.get("biome", "biome.id.Highlands", 73).getInt();
        TwilightForestMod.idBiomeMushrooms = configFile.get("biome", "biome.id.Mushrooms", 74).getInt();
        TwilightForestMod.idBiomeSwamp = configFile.get("biome", "biome.id.Swamp", 75).getInt();
        TwilightForestMod.idBiomeStream = configFile.get("biome", "biome.id.Stream", 76).getInt();
        TwilightForestMod.idBiomeSnowfield = configFile.get("biome", "biome.id.Snowfield", 77).getInt();
        TwilightForestMod.idBiomeGlacier = configFile.get("biome", "biome.id.Glacier", 78).getInt();
        TwilightForestMod.idBiomeClearing = configFile.get("biome", "biome.id.Clearing", 79).getInt();
        TwilightForestMod.idBiomeClearingBorder = configFile.get("biome", "biome.id.ClearingBorder", 80).getInt();
        TwilightForestMod.idBiomeLightedForest = configFile.get("biome", "biome.id.LakeBorder", 81).getInt();
        TwilightForestMod.idBiomeDeepMushrooms = configFile.get("biome", "biome.id.DeepMushrooms", 82).getInt();
        TwilightForestMod.idBiomeMajorFeature = configFile.get("biome", "biome.id.MajorFeature", 83).getInt();
        TwilightForestMod.idBiomeMinorFeature = configFile.get("biome", "biome.id.MinorFeature", 84).getInt();
        TwilightForestMod.idBiomeDarkForest = configFile.get("biome", "biome.id.DarkForest", 85).getInt();
        TwilightForestMod.idBiomeEnchantedForest = configFile.get("biome", "biome.id.EnchantedForest", 86).getInt();
        TwilightForestMod.idBiomeFireSwamp = configFile.get("biome", "biome.id.FireSwamp", 87).getInt();
        TwilightForestMod.idEnchantmentFieryAura = configFile.get("enchantment", "enchantment.id.fieryaura", 136).getInt();
        configFile.save();
    }
    
    public static void setDimensionID(final int dim) {
        if (TwilightForestMod.dimensionID != dim) {
            FMLLog.info("[TwilightForest] Server has a different dimension ID (%d) for the Twilight Forest.  Changing this on the client.  This change will not be saved.", new Object[] { dim });
            DimensionManager.unregisterDimension(TwilightForestMod.dimensionID);
            DimensionManager.registerDimension(TwilightForestMod.dimensionID = dim, TwilightForestMod.dimensionProviderID);
        }
    }
    
    static {
        TwilightForestMod.backupdimensionID = -777;
        TwilightForestMod.dimensionProviderID = -777;
        TwilightForestMod.achievementBaseID = 7000;
        TwilightForestMod.idVehicleSpawnNatureBolt = 1;
        TwilightForestMod.idVehicleSpawnLichBolt = 2;
        TwilightForestMod.idVehicleSpawnTwilightWandBolt = 3;
        TwilightForestMod.idVehicleSpawnTomeBolt = 4;
        TwilightForestMod.idVehicleSpawnHydraMortar = 5;
        TwilightForestMod.idVehicleSpawnLichBomb = 6;
        TwilightForestMod.idVehicleSpawnMoonwormShot = 7;
        TwilightForestMod.idVehicleSpawnSlimeBlob = 8;
        TwilightForestMod.idVehicleSpawnCharmEffect = 9;
        TwilightForestMod.idVehicleSpawnThrownAxe = 10;
        TwilightForestMod.idVehicleSpawnThrownPick = 13;
        eventListener = new TFEventListener();
    }
}
