// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.item;

import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.registry.GameRegistry;
import twilightforest.TwilightForestMod;

public class TFItems
{
    public static wi ARMOR_NAGA;
    public static wi ARMOR_IRONWOOD;
    public static wi ARMOR_FIERY;
    public static wi ARMOR_STEELEAF;
    public static wi ARMOR_KNIGHTLY;
    public static yc TOOL_IRONWOOD;
    public static yc TOOL_FIERY;
    public static yc TOOL_STEELEAF;
    public static yc TOOL_KNIGHTLY;
    public static yb nagaScale;
    public static yb plateNaga;
    public static yb legsNaga;
    public static yb scepterTwilight;
    public static yb scepterLifeDrain;
    public static yb scepterZombie;
    public static yb wandPacification;
    public static yb oreMeter;
    public static yb magicMap;
    public static yb mazeMap;
    public static yb oreMap;
    public static yb feather;
    public static yb magicMapFocus;
    public static yb mazeMapFocus;
    public static yb liveRoot;
    public static yb ironwoodRaw;
    public static yb ironwoodIngot;
    public static yb ironwoodHelm;
    public static yb ironwoodPlate;
    public static yb ironwoodLegs;
    public static yb ironwoodBoots;
    public static yb ironwoodSword;
    public static yb ironwoodShovel;
    public static yb ironwoodPick;
    public static yb ironwoodAxe;
    public static yb ironwoodHoe;
    public static yb torchberries;
    public static yb spawnEgg;
    public static yb venisonRaw;
    public static yb venisonCooked;
    public static yb hydraChop;
    public static yb fieryBlood;
    public static yb trophy;
    public static yb fieryIngot;
    public static yb fieryHelm;
    public static yb fieryPlate;
    public static yb fieryLegs;
    public static yb fieryBoots;
    public static yb fierySword;
    public static yb fieryPick;
    public static yb steeleafIngot;
    public static yb steeleafHelm;
    public static yb steeleafPlate;
    public static yb steeleafLegs;
    public static yb steeleafBoots;
    public static yb steeleafSword;
    public static yb steeleafShovel;
    public static yb steeleafPick;
    public static yb steeleafAxe;
    public static yb steeleafHoe;
    public static yb minotaurAxe;
    public static yb mazebreakerPick;
    public static yb transformPowder;
    public static yb meefRaw;
    public static yb meefSteak;
    public static yb meefStroganoff;
    public static yb mazeWafer;
    public static yb emptyMagicMap;
    public static yb emptyMazeMap;
    public static yb emptyOreMap;
    public static yb oreMagnet;
    public static yb crumbleHorn;
    public static yb peacockFan;
    public static yb moonwormQueen;
    public static yb charmOfLife1;
    public static yb charmOfLife2;
    public static yb charmOfKeeping1;
    public static yb charmOfKeeping2;
    public static yb charmOfKeeping3;
    public static yb towerKey;
    public static yb borerEssence;
    public static yb carminite;
    public static yb experiment115;
    public static yb armorShard;
    public static yb knightMetal;
    public static yb shardCluster;
    public static yb knightlyHelm;
    public static yb knightlyPlate;
    public static yb knightlyLegs;
    public static yb knightlyBoots;
    public static yb knightlySword;
    public static yb knightlyPick;
    public static yb knightlyAxe;
    public static CreativeTabTwilightForest creativeTab;
    
    public TFItems() {
        final int nagaScaleRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/nagascale_");
        final int ironwoodRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/ironwood_");
        final int fieryRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/fiery_");
        final int steeleafRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/steeleaf_");
        final int knightlyRenderID = TwilightForestMod.proxy.registerArmorRenderID("twilightforest/knightly_");
        TFItems.nagaScale = new ItemTF(TwilightForestMod.idItemNagaScale).b("nagaScale");
        TFItems.plateNaga = new ItemTFNagaArmor(TwilightForestMod.idItemPlateNaga, TFItems.ARMOR_NAGA, nagaScaleRenderID, 1).b("plateNaga").d(1);
        TFItems.legsNaga = new ItemTFNagaArmor(TwilightForestMod.idItemLegsNaga, TFItems.ARMOR_NAGA, nagaScaleRenderID, 2).b("legsNaga").d(1);
        TFItems.scepterTwilight = new ItemTFTwilightWand(TwilightForestMod.idItemScepterTwilight).b("scepterTwilight").d(1).q();
        TFItems.scepterLifeDrain = new ItemTFLifeDrainWand(TwilightForestMod.idItemScepterLifeDrain).b("scepterLifeDrain").d(1).q();
        TFItems.scepterZombie = new ItemTFZombieWand(TwilightForestMod.idItemScepterZombie).b("scepterZombie").d(1).q();
        TFItems.oreMeter = new ItemTFOreMeter(TwilightForestMod.idItemOreMeter).b("oreMeter").d(1);
        TFItems.magicMap = new ItemTFMagicMap(TwilightForestMod.idItemMagicMap).b("magicMap").d(1);
        TFItems.mazeMap = new ItemTFMazeMap(TwilightForestMod.idItemMazeMap, false).b("mazeMap").d(1);
        TFItems.oreMap = new ItemTFMazeMap(TwilightForestMod.idItemOreMap, true).b("oreMap").d(1);
        TFItems.feather = new ItemTF(TwilightForestMod.idItemFeather).b("tfFeather");
        TFItems.magicMapFocus = new ItemTF(TwilightForestMod.idItemMagicMapFocus).b("magicMapFocus");
        TFItems.mazeMapFocus = new ItemTF(TwilightForestMod.idItemMazeMapFocus).b("mazeMapFocus");
        TFItems.liveRoot = new ItemTF(TwilightForestMod.idItemLiveRoot).b("liveRoot");
        TFItems.ironwoodRaw = new ItemTF(TwilightForestMod.idItemIronwoodRaw).b("ironwoodRaw");
        TFItems.ironwoodIngot = new ItemTF(TwilightForestMod.idItemIronwoodIngot).b("ironwoodIngot");
        TFItems.ironwoodHelm = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodHelm, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 0).b("ironwoodHelm").d(1);
        TFItems.ironwoodPlate = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodPlate, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 1).b("ironwoodPlate").d(1);
        TFItems.ironwoodLegs = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodLegs, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 2).b("ironwoodLegs").d(1);
        TFItems.ironwoodBoots = new ItemTFIronwoodArmor(TwilightForestMod.idItemIronwoodBoots, TFItems.ARMOR_IRONWOOD, ironwoodRenderID, 3).b("ironwoodBoots").d(1);
        TFItems.ironwoodSword = new ItemTFIronwoodSword(TwilightForestMod.idItemIronwoodSword, TFItems.TOOL_IRONWOOD).b("ironwoodSword").d(1);
        TFItems.ironwoodShovel = new ItemTFIronwoodShovel(TwilightForestMod.idItemIronwoodShovel, TFItems.TOOL_IRONWOOD).b("ironwoodShovel").d(1);
        TFItems.ironwoodPick = new ItemTFIronwoodPick(TwilightForestMod.idItemIronwoodPick, TFItems.TOOL_IRONWOOD).b("ironwoodPick").d(1);
        TFItems.ironwoodAxe = new ItemTFIronwoodAxe(TwilightForestMod.idItemIronwoodAxe, TFItems.TOOL_IRONWOOD).b("ironwoodAxe").d(1);
        TFItems.ironwoodHoe = new ItemTFIronwoodHoe(TwilightForestMod.idItemIronwoodHoe, TFItems.TOOL_IRONWOOD).b("ironwoodHoe").d(1);
        TFItems.torchberries = new ItemTF(TwilightForestMod.idItemTorchberries).b("torchberries");
        TFItems.spawnEgg = new ItemTFSpawnEgg(TwilightForestMod.idItemSpawnEgg).b("tfspawnegg");
        TFItems.venisonRaw = new ItemTFFood(TwilightForestMod.idItemVenisonRaw, 3, 0.3f, true).setLooksLike(yb.bk).b("venisonRaw");
        TFItems.venisonCooked = new ItemTFFood(TwilightForestMod.idItemVenisonCooked, 8, 0.8f, true).setLooksLike(yb.bl).b("venisonCooked");
        TFItems.hydraChop = new ItemTFFood(TwilightForestMod.idItemHydraChops, 18, 2.0f, true).setLooksLike(yb.at).a(nh.l.H, 5, 0, 1.0f).b("hydraChop");
        TFItems.fieryBlood = new ItemTF(TwilightForestMod.idItemFieryBlood).makeRare().b("fieryBlood");
        TFItems.trophy = new ItemTFTrophy(TwilightForestMod.idItemTrophy).b("trophy");
        TFItems.fieryIngot = new ItemTF(TwilightForestMod.idItemFieryIngot).makeRare().b("fieryIngot");
        TFItems.fieryHelm = new ItemTFFieryArmor(TwilightForestMod.idItemFieryHelm, TFItems.ARMOR_FIERY, fieryRenderID, 0).b("fieryHelm").d(1);
        TFItems.fieryPlate = new ItemTFFieryArmor(TwilightForestMod.idItemFieryPlate, TFItems.ARMOR_FIERY, fieryRenderID, 1).b("fieryPlate").d(1);
        TFItems.fieryLegs = new ItemTFFieryArmor(TwilightForestMod.idItemFieryLegs, TFItems.ARMOR_FIERY, fieryRenderID, 2).b("fieryLegs").d(1);
        TFItems.fieryBoots = new ItemTFFieryArmor(TwilightForestMod.idItemFieryBoots, TFItems.ARMOR_FIERY, fieryRenderID, 3).b("fieryBoots").d(1);
        TFItems.fierySword = new ItemTFFierySword(TwilightForestMod.idItemFierySword, TFItems.TOOL_FIERY).b("fierySword").d(1);
        TFItems.fieryPick = new ItemTFFieryPick(TwilightForestMod.idItemFieryPick, TFItems.TOOL_FIERY).b("fieryPick").d(1);
        TFItems.steeleafIngot = new ItemTF(TwilightForestMod.idItemSteeleafIngot).b("steeleafIngot");
        TFItems.steeleafHelm = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafHelm, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 0).b("steeleafHelm").d(1);
        TFItems.steeleafPlate = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafPlate, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 1).b("steeleafPlate").d(1);
        TFItems.steeleafLegs = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafLegs, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 2).b("steeleafLegs").d(1);
        TFItems.steeleafBoots = new ItemTFSteeleafArmor(TwilightForestMod.idItemSteeleafBoots, TFItems.ARMOR_IRONWOOD, steeleafRenderID, 3).b("steeleafBoots").d(1);
        TFItems.steeleafSword = new ItemTFSteeleafSword(TwilightForestMod.idItemSteeleafSword, TFItems.TOOL_STEELEAF).b("steeleafSword").d(1);
        TFItems.steeleafShovel = new ItemTFSteeleafShovel(TwilightForestMod.idItemSteeleafShovel, TFItems.TOOL_STEELEAF).b("steeleafShovel").d(1);
        TFItems.steeleafPick = new ItemTFSteeleafPick(TwilightForestMod.idItemSteeleafPick, TFItems.TOOL_STEELEAF).b("steeleafPick").d(1);
        TFItems.steeleafAxe = new ItemTFSteeleafAxe(TwilightForestMod.idItemSteeleafAxe, TFItems.TOOL_STEELEAF).b("steeleafAxe").d(1);
        TFItems.steeleafHoe = new ItemTFSteeleafHoe(TwilightForestMod.idItemSteeleafHoe, TFItems.TOOL_STEELEAF).b("steeleafHoe").d(1);
        TFItems.minotaurAxe = new ItemTFMinotaurAxe(TwilightForestMod.idItemMinotaurAxe, yc.d).b("minotaurAxe").d(1);
        TFItems.mazebreakerPick = new ItemTFMazebreakerPick(TwilightForestMod.idItemMazebreakerPick, yc.d).b("mazebreakerPick").d(1);
        TFItems.transformPowder = new ItemTFTransformPowder(TwilightForestMod.idItemTransformPowder).makeRare().b("transformPowder");
        TFItems.meefRaw = new ItemTFFood(TwilightForestMod.idItemMeefRaw, 2, 0.3f, true).setLooksLike(yb.bk).b("meefRaw");
        TFItems.meefSteak = new ItemTFFood(TwilightForestMod.idItemMeefSteak, 6, 0.6f, true).setLooksLike(yb.bl).b("meefSteak");
        TFItems.meefStroganoff = new ItemTFFood(TwilightForestMod.idItemMeefStroganoff, 8).setLooksLike(yb.H).b("meefStroganoff");
        TFItems.mazeWafer = new ItemTFFood(TwilightForestMod.idItemMazeWafer, 4, 0.6f, false).b("mazeWafer");
        TFItems.emptyMagicMap = new ItemTFEmptyMagicMap(TwilightForestMod.idItemEmptyMagicMap).b("emptyMagicMap");
        TFItems.emptyMazeMap = new ItemTFEmptyMazeMap(TwilightForestMod.idItemEmptyMazeMap, false).b("emptyMazeMap");
        TFItems.emptyOreMap = new ItemTFEmptyMazeMap(TwilightForestMod.idItemEmptyOreMap, true).b("emptyOreMap");
        TFItems.oreMagnet = new ItemTFOreMagnet(TwilightForestMod.idItemOreMagnet).b("oreMagnet");
        TFItems.crumbleHorn = new ItemTFCrumbleHorn(TwilightForestMod.idItemCrumbleHorn).b("crumbleHorn");
        TFItems.peacockFan = new ItemTFPeacockFan(TwilightForestMod.idItemPeacockFan).b("peacockFan");
        TFItems.moonwormQueen = new ItemTFMoonwormQueen(TwilightForestMod.idItemMoonwormQueen).b("moonwormQueen");
        TFItems.charmOfLife1 = new ItemTFCharm(TwilightForestMod.idItemCharmOfLife1).b("charmOfLife1");
        TFItems.charmOfLife2 = new ItemTFCharm(TwilightForestMod.idItemCharmOfLife2).b("charmOfLife2");
        TFItems.charmOfKeeping1 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping1).b("charmOfKeeping1");
        TFItems.charmOfKeeping2 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping2).b("charmOfKeeping2");
        TFItems.charmOfKeeping3 = new ItemTFCharm(TwilightForestMod.idItemCharmOfKeeping3).b("charmOfKeeping3");
        TFItems.towerKey = new ItemTFTowerKey(TwilightForestMod.idItemTowerKey).b("towerKey");
        TFItems.borerEssence = new ItemTF(TwilightForestMod.idItemBorerEssence).b("borerEssence");
        TFItems.carminite = new ItemTF(TwilightForestMod.idItemCarminite).makeRare().b("carminite");
        TFItems.experiment115 = new ItemTFFood(TwilightForestMod.idItemExperiment115, 4, 0.3f, false).b("experiment115");
        TFItems.armorShard = new ItemTF(TwilightForestMod.idItemArmorShards).b("armorShards");
        TFItems.knightMetal = new ItemTF(TwilightForestMod.idItemKnightMetal).b("knightMetal");
        TFItems.shardCluster = new ItemTF(TwilightForestMod.idItemShardCluster).b("shardCluster");
        TFItems.knightlyHelm = new ItemTFKnightlyArmor(TwilightForestMod.idItemKnightlyHelm, TFItems.ARMOR_KNIGHTLY, knightlyRenderID, 0).b("knightlyHelm").d(1);
        TFItems.knightlyPlate = new ItemTFKnightlyArmor(TwilightForestMod.idItemKnightlyPlate, TFItems.ARMOR_KNIGHTLY, knightlyRenderID, 1).b("knightlyPlate").d(1);
        TFItems.knightlyLegs = new ItemTFKnightlyArmor(TwilightForestMod.idItemKnightlyLegs, TFItems.ARMOR_KNIGHTLY, knightlyRenderID, 2).b("knightlyLegs").d(1);
        TFItems.knightlyBoots = new ItemTFKnightlyArmor(TwilightForestMod.idItemKnightlyBoots, TFItems.ARMOR_KNIGHTLY, knightlyRenderID, 3).b("knightlyBoots").d(1);
        TFItems.knightlySword = new ItemTFKnightlySword(TwilightForestMod.idItemKnightlySword, TFItems.TOOL_KNIGHTLY).b("knightlySword").d(1);
        TFItems.knightlyPick = new ItemTFKnightlyPick(TwilightForestMod.idItemKnightlyPick, TFItems.TOOL_KNIGHTLY).b("knightlyPick").d(1);
        TFItems.knightlyAxe = new ItemTFKnightlyAxe(TwilightForestMod.idItemKnightlyAxe, TFItems.TOOL_KNIGHTLY).b("knightlyAxe").d(1);
        this.registerTFItem(TFItems.nagaScale, "Naga Scale");
        this.registerTFItem(TFItems.plateNaga, "Naga Scale Tunic");
        this.registerTFItem(TFItems.legsNaga, "Naga Scale Leggings");
        this.registerTFItem(TFItems.scepterTwilight, "Scepter of Twilight");
        this.registerTFItem(TFItems.scepterLifeDrain, "Scepter of Life Draining");
        this.registerTFItem(TFItems.scepterZombie, "Zombie Scepter");
        this.registerTFItem(TFItems.oreMeter, "Ore Meter [WIP]");
        this.registerTFItem(TFItems.magicMap, "Magic Map");
        this.registerTFItem(TFItems.mazeMap, "Maze Map");
        this.registerTFItem(TFItems.oreMap, "Maze/Ore Map");
        this.registerTFItem(TFItems.feather, "Raven's Feather");
        this.registerTFItem(TFItems.magicMapFocus, "Magic Map Focus");
        this.registerTFItem(TFItems.mazeMapFocus, "Maze Map Focus");
        this.registerTFItem(TFItems.liveRoot, "Liveroot");
        this.registerTFItem(TFItems.ironwoodRaw, "Raw Ironwood Materials");
        this.registerTFItem(TFItems.ironwoodIngot, "Ironwood Ingot");
        this.registerTFItem(TFItems.ironwoodHelm, "Ironwood Helm");
        this.registerTFItem(TFItems.ironwoodPlate, "Ironwood Plate");
        this.registerTFItem(TFItems.ironwoodLegs, "Ironwood Legs");
        this.registerTFItem(TFItems.ironwoodBoots, "Ironwood Boots");
        this.registerTFItem(TFItems.ironwoodSword, "Ironwood Sword");
        this.registerTFItem(TFItems.ironwoodShovel, "Ironwood Shovel");
        this.registerTFItem(TFItems.ironwoodPick, "Ironwood Pick");
        this.registerTFItem(TFItems.ironwoodAxe, "Ironwood Axe");
        this.registerTFItem(TFItems.ironwoodHoe, "Ironwood Hoe");
        this.registerTFItem(TFItems.torchberries, "Torchberries");
        this.registerTFItem(TFItems.venisonRaw, "Raw Venison");
        this.registerTFItem(TFItems.venisonCooked, "Venison Steak");
        this.registerTFItem(TFItems.hydraChop, "Hydra Chop");
        this.registerTFItem(TFItems.fieryBlood, "Fiery Blood");
        this.registerTFItem(TFItems.trophy, "Hydra Trophy");
        this.registerTFItem(TFItems.fieryIngot, "Fiery Ingot");
        this.registerTFItem(TFItems.fieryHelm, "Fiery Helm");
        this.registerTFItem(TFItems.fieryPlate, "Fiery Plate");
        this.registerTFItem(TFItems.fieryLegs, "Fiery Legs");
        this.registerTFItem(TFItems.fieryBoots, "Fiery Boots");
        this.registerTFItem(TFItems.fierySword, "Fiery Sword");
        this.registerTFItem(TFItems.fieryPick, "Fiery Pick");
        this.registerTFItem(TFItems.steeleafIngot, "Steeleaf");
        this.registerTFItem(TFItems.steeleafHelm, "Steeleaf Helm");
        this.registerTFItem(TFItems.steeleafPlate, "Steeleaf Plate");
        this.registerTFItem(TFItems.steeleafLegs, "Steeleaf Legs");
        this.registerTFItem(TFItems.steeleafBoots, "Steeleaf Boots");
        this.registerTFItem(TFItems.steeleafSword, "Steeleaf Sword");
        this.registerTFItem(TFItems.steeleafShovel, "Steeleaf Shovel");
        this.registerTFItem(TFItems.steeleafPick, "Steeleaf Pick");
        this.registerTFItem(TFItems.steeleafAxe, "Steeleaf Axe");
        this.registerTFItem(TFItems.steeleafHoe, "Steeleaf Hoe");
        this.registerTFItem(TFItems.minotaurAxe, "Minotaur Axe");
        this.registerTFItem(TFItems.mazebreakerPick, "Mazebreaker");
        this.registerTFItem(TFItems.transformPowder, "Transformation Powder");
        this.registerTFItem(TFItems.meefRaw, "Raw Meef");
        this.registerTFItem(TFItems.meefSteak, "Meef Steak");
        this.registerTFItem(TFItems.meefStroganoff, "Meef Stroganoff");
        this.registerTFItem(TFItems.mazeWafer, "Maze Wafer");
        this.registerTFItem(TFItems.emptyMagicMap, "Blank Magic Map");
        this.registerTFItem(TFItems.emptyMazeMap, "Blank Maze Map");
        this.registerTFItem(TFItems.emptyOreMap, "Blank Maze/Ore Map");
        this.registerTFItem(TFItems.oreMagnet, "Ore Magnet");
        this.registerTFItem(TFItems.crumbleHorn, "Crumble Horn");
        this.registerTFItem(TFItems.peacockFan, "Peacock Feather Fan");
        this.registerTFItem(TFItems.moonwormQueen, "Moonworm Queen");
        this.registerTFItem(TFItems.charmOfLife1, "Charm of Life I");
        this.registerTFItem(TFItems.charmOfLife2, "Charm of Life II");
        this.registerTFItem(TFItems.charmOfKeeping1, "Charm of Keeping I");
        this.registerTFItem(TFItems.charmOfKeeping2, "Charm of Keeping II");
        this.registerTFItem(TFItems.charmOfKeeping3, "Charm of Keeping III");
        this.registerTFItem(TFItems.towerKey, "Tower Key");
        this.registerTFItem(TFItems.borerEssence, "Borer Essence");
        this.registerTFItem(TFItems.carminite, "Carminite");
        this.registerTFItem(TFItems.experiment115, "Experiment 115");
        this.registerTFItem(TFItems.armorShard, "Armor Shards");
        this.registerTFItem(TFItems.knightMetal, "Knightmetal Ingot");
        this.registerTFItem(TFItems.shardCluster, "Shard Cluster");
        this.registerTFItem(TFItems.knightlyHelm, "Knightly Helm");
        this.registerTFItem(TFItems.knightlyPlate, "Knightly Plate");
        this.registerTFItem(TFItems.knightlyLegs, "Knightly Legs");
        this.registerTFItem(TFItems.knightlyBoots, "Knightly Boots");
        this.registerTFItem(TFItems.knightlySword, "Knightly Sword");
        this.registerTFItem(TFItems.knightlyPick, "Knightly Pick");
        this.registerTFItem(TFItems.knightlyAxe, "Knightly Axe");
        this.registerTFItem(TFItems.spawnEgg, "Spawn");
    }
    
    private void registerTFItem(final yb item, final String englishName) {
        GameRegistry.registerItem(item, item.a(), "TwilightForest");
    }
    
    static {
        TFItems.ARMOR_NAGA = EnumHelper.addArmorMaterial("NAGA_SCALE", 21, new int[] { 2, 7, 6, 3 }, 15);
        TFItems.ARMOR_IRONWOOD = EnumHelper.addArmorMaterial("IRONWOOD", 20, new int[] { 2, 7, 5, 2 }, 15);
        TFItems.ARMOR_FIERY = EnumHelper.addArmorMaterial("FIERY", 25, new int[] { 4, 9, 7, 4 }, 10);
        TFItems.ARMOR_STEELEAF = EnumHelper.addArmorMaterial("STEELEAF", 10, new int[] { 3, 8, 6, 3 }, 9);
        TFItems.ARMOR_KNIGHTLY = EnumHelper.addArmorMaterial("KNIGHTMETAL", 20, new int[] { 3, 8, 6, 3 }, 8);
        TFItems.TOOL_IRONWOOD = EnumHelper.addToolMaterial("IRONWOOD", 2, 512, 6.5f, 2.0f, 25);
        TFItems.TOOL_FIERY = EnumHelper.addToolMaterial("FIERY", 4, 1024, 9.0f, 4.0f, 10);
        TFItems.TOOL_STEELEAF = EnumHelper.addToolMaterial("STEELEAF", 3, 131, 8.0f, 3.0f, 9);
        TFItems.TOOL_KNIGHTLY = EnumHelper.addToolMaterial("KNIGHTMETAL", 3, 512, 8.0f, 3.0f, 8);
        TFItems.creativeTab = new CreativeTabTwilightForest("twilightForest");
    }
}
