// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.util;

import net.minecraft.util.ResourceLocation;

public class TFEntityNames
{
    public static final ResourceLocation WILD_BOAR;
    public static final ResourceLocation BIGHORN_SHEEP;
    public static final ResourceLocation DEER;
    public static final ResourceLocation PENGUIN;
    public static final ResourceLocation TINY_BIRD;
    public static final ResourceLocation SQUIRREL;
    public static final ResourceLocation BUNNY;
    public static final ResourceLocation RAVEN;
    public static final ResourceLocation FIREFLY;
    public static final ResourceLocation QUEST_RAM;
    public static final ResourceLocation SKELETON_DRUID;
    public static final ResourceLocation WRAITH;
    public static final ResourceLocation KOBOLD;
    public static final ResourceLocation HOSTILE_WOLF;
    public static final ResourceLocation REDCAP;
    public static final ResourceLocation REDCAP_SAPPER;
    public static final ResourceLocation SWARM_SPIDER;
    public static final ResourceLocation HEDGE_SPIDER;
    public static final ResourceLocation FIRE_BEETLE;
    public static final ResourceLocation SLIME_BEETLE;
    public static final ResourceLocation PINCH_BEETLE;
    public static final ResourceLocation BOGGARD;
    public static final ResourceLocation RISING_ZOMBIE;
    public static final ResourceLocation NAGA;
    public static final ResourceLocation LICH;
    public static final ResourceLocation LICH_MINION;
    public static final ResourceLocation LOYAL_ZOMBIE;
    public static final ResourceLocation DEATH_TOME;
    public static final ResourceLocation MOSQUITO_SWARM;
    public static final ResourceLocation HYDRA;
    public static final ResourceLocation MINOTAUR;
    public static final ResourceLocation MINOSHROOM;
    public static final ResourceLocation MAZE_SLIME;
    public static final ResourceLocation MIST_WOLF;
    public static final ResourceLocation KING_SPIDER;
    public static final ResourceLocation MINI_GHAST;
    public static final ResourceLocation TOWER_GHAST;
    public static final ResourceLocation TOWER_GOLEM;
    public static final ResourceLocation TOWER_TERMITE;
    public static final ResourceLocation TOWER_BROODLING;
    public static final ResourceLocation UR_GHAST;
    public static final ResourceLocation BLOCKCHAIN_GOBLIN;
    public static final ResourceLocation GOBLIN_KNIGHT_UPPER;
    public static final ResourceLocation GOBLIN_KNIGHT_LOWER;
    public static final ResourceLocation HELMET_CRAB;
    public static final ResourceLocation KNIGHT_PHANTOM;
    public static final ResourceLocation YETI;
    public static final ResourceLocation YETI_ALPHA;
    public static final ResourceLocation WINTER_WOLF;
    public static final ResourceLocation SNOW_GUARDIAN;
    public static final ResourceLocation STABLE_ICE_CORE;
    public static final ResourceLocation UNSTABLE_ICE_CORE;
    public static final ResourceLocation SNOW_QUEEN;
    public static final ResourceLocation ICE_CRYSTAL;
    public static final ResourceLocation TROLL;
    public static final ResourceLocation GIANT_MINER;
    public static final ResourceLocation ARMORED_GIANT;
    public static final ResourceLocation HARBINGER_CUBE;
    public static final ResourceLocation ADHERENT;
    public static final ResourceLocation ROVING_CUBE;
    public static final ResourceLocation SLIDER;
    public static final ResourceLocation CASTLE_GUARDIAN;
    public static final ResourceLocation HYDRA_HEAD;
    public static final ResourceLocation CHARM_EFFECT;
    public static final ResourceLocation FALLING_ICE;
    public static final ResourceLocation CHAIN_BLOCK;
    public static final ResourceLocation CUBE_OF_ANNIHILATION;
    public static final ResourceLocation NATURE_BOLT;
    public static final ResourceLocation LICH_BOLT;
    public static final ResourceLocation WAND_BOLT;
    public static final ResourceLocation TOME_BOLT;
    public static final ResourceLocation HYDRA_MORTAR;
    public static final ResourceLocation LICH_BOMB;
    public static final ResourceLocation MOONWORM_SHOT;
    public static final ResourceLocation SLIME_BLOB;
    public static final ResourceLocation THROWN_WEP;
    public static final ResourceLocation THROWN_ICE;
    public static final ResourceLocation SEEKER_ARROW;
    public static final ResourceLocation ICE_ARROW;
    public static final ResourceLocation ICE_SNOWBALL;
    
    private static ResourceLocation prefix(final String path) {
        return new ResourceLocation("twilightforest", path);
    }
    
    static {
        WILD_BOAR = prefix("wild_boar");
        BIGHORN_SHEEP = prefix("bighorn_sheep");
        DEER = prefix("deer");
        PENGUIN = prefix("penguin");
        TINY_BIRD = prefix("tiny_bird");
        SQUIRREL = prefix("squirrel");
        BUNNY = prefix("bunny");
        RAVEN = prefix("raven");
        FIREFLY = prefix("firefly");
        QUEST_RAM = prefix("quest_ram");
        SKELETON_DRUID = prefix("skeleton_druid");
        WRAITH = prefix("wraith");
        KOBOLD = prefix("kobold");
        HOSTILE_WOLF = prefix("hostile_wolf");
        REDCAP = prefix("redcap");
        REDCAP_SAPPER = prefix("redcap_sapper");
        SWARM_SPIDER = prefix("swarm_spider");
        HEDGE_SPIDER = prefix("hedge_spider");
        FIRE_BEETLE = prefix("fire_beetle");
        SLIME_BEETLE = prefix("slime_beetle");
        PINCH_BEETLE = prefix("pinch_beetle");
        BOGGARD = prefix("boggard");
        RISING_ZOMBIE = prefix("rising_zombie");
        NAGA = prefix("naga");
        LICH = prefix("lich");
        LICH_MINION = prefix("lich_minion");
        LOYAL_ZOMBIE = prefix("loyal_zombie");
        DEATH_TOME = prefix("death_tome");
        MOSQUITO_SWARM = prefix("mosquito_swarm");
        HYDRA = prefix("hydra");
        MINOTAUR = prefix("minotaur");
        MINOSHROOM = prefix("minoshroom");
        MAZE_SLIME = prefix("maze_slime");
        MIST_WOLF = prefix("mist_wolf");
        KING_SPIDER = prefix("king_spider");
        MINI_GHAST = prefix("mini_ghast");
        TOWER_GHAST = prefix("tower_ghast");
        TOWER_GOLEM = prefix("tower_golem");
        TOWER_TERMITE = prefix("tower_termite");
        TOWER_BROODLING = prefix("tower_broodling");
        UR_GHAST = prefix("ur_ghast");
        BLOCKCHAIN_GOBLIN = prefix("blockchain_goblin");
        GOBLIN_KNIGHT_UPPER = prefix("goblin_knight_upper");
        GOBLIN_KNIGHT_LOWER = prefix("goblin_knight_lower");
        HELMET_CRAB = prefix("helmet_crab");
        KNIGHT_PHANTOM = prefix("knight_phantom");
        YETI = prefix("yeti");
        YETI_ALPHA = prefix("yeti_alpha");
        WINTER_WOLF = prefix("winter_wolf");
        SNOW_GUARDIAN = prefix("snow_guardian");
        STABLE_ICE_CORE = prefix("stable_ice_core");
        UNSTABLE_ICE_CORE = prefix("unstable_ice_core");
        SNOW_QUEEN = prefix("snow_queen");
        ICE_CRYSTAL = prefix("ice_crystal");
        TROLL = prefix("troll");
        GIANT_MINER = prefix("giant_miner");
        ARMORED_GIANT = prefix("armored_giant");
        HARBINGER_CUBE = prefix("harbinger_cube");
        ADHERENT = prefix("adherent");
        ROVING_CUBE = prefix("roving_cube");
        SLIDER = prefix("slider");
        CASTLE_GUARDIAN = prefix("castle_guardian");
        HYDRA_HEAD = prefix("hydra_head");
        CHARM_EFFECT = prefix("charm_effect");
        FALLING_ICE = prefix("falling_ice");
        CHAIN_BLOCK = prefix("chain_block");
        CUBE_OF_ANNIHILATION = prefix("cube_of_annihilation");
        NATURE_BOLT = prefix("nature_bolt");
        LICH_BOLT = prefix("lich_bolt");
        WAND_BOLT = prefix("wand_bolt");
        TOME_BOLT = prefix("tome_bolt");
        HYDRA_MORTAR = prefix("hydra_mortar");
        LICH_BOMB = prefix("lich_bomb");
        MOONWORM_SHOT = prefix("moonworm_shot");
        SLIME_BLOB = prefix("slime_blob");
        THROWN_WEP = prefix("thrown_wep");
        THROWN_ICE = prefix("thrown_ice");
        SEEKER_ARROW = prefix("seeker_arrow");
        ICE_ARROW = prefix("ice_arrow");
        ICE_SNOWBALL = prefix("ice_snowball");
    }
}
