// 
// Decompiled by Procyon v0.6-prerelease
// 

package twilightforest.util;

import twilightforest.TwilightForestMod;
import net.minecraft.util.ResourceLocation;

public class TFEntityNames
{
    public static final ResourceLocation WILD_BOAR;
    public static final ResourceLocation BIGHORN_SHEEP;
    public static final ResourceLocation DEER;
    public static final ResourceLocation PENGUIN;
    public static final ResourceLocation TINY_BIRD;
    public static final ResourceLocation SQUIRREL;
    public static final ResourceLocation BUNNY;
    public static final ResourceLocation RAVEN;
    public static final ResourceLocation QUEST_RAM;
    public static final ResourceLocation SKELETON_DRUID;
    public static final ResourceLocation WRAITH;
    public static final ResourceLocation KOBOLD;
    public static final ResourceLocation HOSTILE_WOLF;
    public static final ResourceLocation REDCAP;
    public static final ResourceLocation REDCAP_SAPPER;
    public static final ResourceLocation SWARM_SPIDER;
    public static final ResourceLocation HEDGE_SPIDER;
    public static final ResourceLocation FIRE_BEETLE;
    public static final ResourceLocation SLIME_BEETLE;
    public static final ResourceLocation PINCH_BEETLE;
    public static final ResourceLocation BOGGARD;
    public static final ResourceLocation RISING_ZOMBIE;
    public static final ResourceLocation NAGA;
    public static final ResourceLocation LICH;
    public static final ResourceLocation LICH_MINION;
    public static final ResourceLocation LOYAL_ZOMBIE;
    public static final ResourceLocation DEATH_TOME;
    public static final ResourceLocation MOSQUITO_SWARM;
    public static final ResourceLocation HYDRA;
    public static final ResourceLocation MINOTAUR;
    public static final ResourceLocation MINOSHROOM;
    public static final ResourceLocation MAZE_SLIME;
    public static final ResourceLocation MIST_WOLF;
    public static final ResourceLocation KING_SPIDER;
    public static final ResourceLocation MINI_GHAST;
    public static final ResourceLocation TOWER_GHAST;
    public static final ResourceLocation TOWER_GOLEM;
    public static final ResourceLocation TOWER_TERMITE;
    public static final ResourceLocation TOWER_BROODLING;
    public static final ResourceLocation UR_GHAST;
    public static final ResourceLocation BLOCKCHAIN_GOBLIN;
    public static final ResourceLocation GOBLIN_KNIGHT_UPPER;
    public static final ResourceLocation GOBLIN_KNIGHT_LOWER;
    public static final ResourceLocation HELMET_CRAB;
    public static final ResourceLocation KNIGHT_PHANTOM;
    public static final ResourceLocation YETI;
    public static final ResourceLocation YETI_ALPHA;
    public static final ResourceLocation WINTER_WOLF;
    public static final ResourceLocation SNOW_GUARDIAN;
    public static final ResourceLocation STABLE_ICE_CORE;
    public static final ResourceLocation UNSTABLE_ICE_CORE;
    public static final ResourceLocation SNOW_QUEEN;
    public static final ResourceLocation ICE_CRYSTAL;
    public static final ResourceLocation TROLL;
    public static final ResourceLocation GIANT_MINER;
    public static final ResourceLocation ARMORED_GIANT;
    public static final ResourceLocation HARBINGER_CUBE;
    public static final ResourceLocation ADHERENT;
    public static final ResourceLocation ROVING_CUBE;
    public static final ResourceLocation SLIDER;
    public static final ResourceLocation CASTLE_GUARDIAN;
    public static final ResourceLocation PLATEAU_BOSS;
    public static final ResourceLocation CHARM_EFFECT;
    public static final ResourceLocation FALLING_ICE;
    public static final ResourceLocation CHAIN_BLOCK;
    public static final ResourceLocation CUBE_OF_ANNIHILATION;
    public static final ResourceLocation PROTECTION_BOX;
    public static final ResourceLocation NATURE_BOLT;
    public static final ResourceLocation LICH_BOLT;
    public static final ResourceLocation WAND_BOLT;
    public static final ResourceLocation TOME_BOLT;
    public static final ResourceLocation HYDRA_MORTAR;
    public static final ResourceLocation LICH_BOMB;
    public static final ResourceLocation CICADA_SHOT;
    public static final ResourceLocation MOONWORM_SHOT;
    public static final ResourceLocation SLIME_BLOB;
    public static final ResourceLocation THROWN_WEP;
    public static final ResourceLocation THROWN_ICE;
    public static final ResourceLocation SEEKER_ARROW;
    public static final ResourceLocation ICE_ARROW;
    public static final ResourceLocation ICE_SNOWBALL;
    
    static {
        WILD_BOAR = TwilightForestMod.prefix("wild_boar");
        BIGHORN_SHEEP = TwilightForestMod.prefix("bighorn_sheep");
        DEER = TwilightForestMod.prefix("deer");
        PENGUIN = TwilightForestMod.prefix("penguin");
        TINY_BIRD = TwilightForestMod.prefix("tiny_bird");
        SQUIRREL = TwilightForestMod.prefix("squirrel");
        BUNNY = TwilightForestMod.prefix("bunny");
        RAVEN = TwilightForestMod.prefix("raven");
        QUEST_RAM = TwilightForestMod.prefix("quest_ram");
        SKELETON_DRUID = TwilightForestMod.prefix("skeleton_druid");
        WRAITH = TwilightForestMod.prefix("wraith");
        KOBOLD = TwilightForestMod.prefix("kobold");
        HOSTILE_WOLF = TwilightForestMod.prefix("hostile_wolf");
        REDCAP = TwilightForestMod.prefix("redcap");
        REDCAP_SAPPER = TwilightForestMod.prefix("redcap_sapper");
        SWARM_SPIDER = TwilightForestMod.prefix("swarm_spider");
        HEDGE_SPIDER = TwilightForestMod.prefix("hedge_spider");
        FIRE_BEETLE = TwilightForestMod.prefix("fire_beetle");
        SLIME_BEETLE = TwilightForestMod.prefix("slime_beetle");
        PINCH_BEETLE = TwilightForestMod.prefix("pinch_beetle");
        BOGGARD = TwilightForestMod.prefix("boggard");
        RISING_ZOMBIE = TwilightForestMod.prefix("rising_zombie");
        NAGA = TwilightForestMod.prefix("naga");
        LICH = TwilightForestMod.prefix("lich");
        LICH_MINION = TwilightForestMod.prefix("lich_minion");
        LOYAL_ZOMBIE = TwilightForestMod.prefix("loyal_zombie");
        DEATH_TOME = TwilightForestMod.prefix("death_tome");
        MOSQUITO_SWARM = TwilightForestMod.prefix("mosquito_swarm");
        HYDRA = TwilightForestMod.prefix("hydra");
        MINOTAUR = TwilightForestMod.prefix("minotaur");
        MINOSHROOM = TwilightForestMod.prefix("minoshroom");
        MAZE_SLIME = TwilightForestMod.prefix("maze_slime");
        MIST_WOLF = TwilightForestMod.prefix("mist_wolf");
        KING_SPIDER = TwilightForestMod.prefix("king_spider");
        MINI_GHAST = TwilightForestMod.prefix("mini_ghast");
        TOWER_GHAST = TwilightForestMod.prefix("tower_ghast");
        TOWER_GOLEM = TwilightForestMod.prefix("tower_golem");
        TOWER_TERMITE = TwilightForestMod.prefix("tower_termite");
        TOWER_BROODLING = TwilightForestMod.prefix("tower_broodling");
        UR_GHAST = TwilightForestMod.prefix("ur_ghast");
        BLOCKCHAIN_GOBLIN = TwilightForestMod.prefix("blockchain_goblin");
        GOBLIN_KNIGHT_UPPER = TwilightForestMod.prefix("goblin_knight_upper");
        GOBLIN_KNIGHT_LOWER = TwilightForestMod.prefix("goblin_knight_lower");
        HELMET_CRAB = TwilightForestMod.prefix("helmet_crab");
        KNIGHT_PHANTOM = TwilightForestMod.prefix("knight_phantom");
        YETI = TwilightForestMod.prefix("yeti");
        YETI_ALPHA = TwilightForestMod.prefix("yeti_alpha");
        WINTER_WOLF = TwilightForestMod.prefix("winter_wolf");
        SNOW_GUARDIAN = TwilightForestMod.prefix("snow_guardian");
        STABLE_ICE_CORE = TwilightForestMod.prefix("stable_ice_core");
        UNSTABLE_ICE_CORE = TwilightForestMod.prefix("unstable_ice_core");
        SNOW_QUEEN = TwilightForestMod.prefix("snow_queen");
        ICE_CRYSTAL = TwilightForestMod.prefix("ice_crystal");
        TROLL = TwilightForestMod.prefix("troll");
        GIANT_MINER = TwilightForestMod.prefix("giant_miner");
        ARMORED_GIANT = TwilightForestMod.prefix("armored_giant");
        HARBINGER_CUBE = TwilightForestMod.prefix("harbinger_cube");
        ADHERENT = TwilightForestMod.prefix("adherent");
        ROVING_CUBE = TwilightForestMod.prefix("roving_cube");
        SLIDER = TwilightForestMod.prefix("slider");
        CASTLE_GUARDIAN = TwilightForestMod.prefix("castle_guardian");
        PLATEAU_BOSS = TwilightForestMod.prefix("plateau_boss");
        CHARM_EFFECT = TwilightForestMod.prefix("charm_effect");
        FALLING_ICE = TwilightForestMod.prefix("falling_ice");
        CHAIN_BLOCK = TwilightForestMod.prefix("chain_block");
        CUBE_OF_ANNIHILATION = TwilightForestMod.prefix("cube_of_annihilation");
        PROTECTION_BOX = TwilightForestMod.prefix("protection_box");
        NATURE_BOLT = TwilightForestMod.prefix("nature_bolt");
        LICH_BOLT = TwilightForestMod.prefix("lich_bolt");
        WAND_BOLT = TwilightForestMod.prefix("wand_bolt");
        TOME_BOLT = TwilightForestMod.prefix("tome_bolt");
        HYDRA_MORTAR = TwilightForestMod.prefix("hydra_mortar");
        LICH_BOMB = TwilightForestMod.prefix("lich_bomb");
        CICADA_SHOT = TwilightForestMod.prefix("cicada_shot");
        MOONWORM_SHOT = TwilightForestMod.prefix("moonworm_shot");
        SLIME_BLOB = TwilightForestMod.prefix("slime_blob");
        THROWN_WEP = TwilightForestMod.prefix("thrown_wep");
        THROWN_ICE = TwilightForestMod.prefix("thrown_ice");
        SEEKER_ARROW = TwilightForestMod.prefix("seeker_arrow");
        ICE_ARROW = TwilightForestMod.prefix("ice_arrow");
        ICE_SNOWBALL = TwilightForestMod.prefix("ice_snowball");
    }
}
